---
title: "Untitled"
author: "Brandon L. Kramer"
date: "1/8/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", 
# "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "linkprediction", "poweRlaw"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot",
              "maditr", "lubridate", "linkprediction", "poweRlaw", "plotly","gridExtra", "rmarkdown")) {library(pkg, character.only = TRUE)}

setwd("~/Documents/OSS/Data")
#setwd("~/intl-dyn-ctr-nets-cum")
global_netstats_cum <- read_rds("global_netstats_cum.rds")
full_nodelist_cum <- read_rds("full_nodelist_cum.rds")
kcore_data_cum <- read_rds("kcore_data_cum.rds")
decomp_data_cum <- read_rds("decomp_data_cum.rds")

global_netstats_cum <- global_netstats_cum %>% 
  transform(dyads = as.numeric(dyads))

setwd("~/Documents/OSS/Data")
#setwd("~/intl-dyn-ctr-nets-cum")
global_netstats_yxy <- read_rds("global_netstats_yxy.rds")
full_nodelist_yxy <- read_rds("full_nodelist_yxy.rds")
kcore_data_yxy <- read_rds("kcore_data_yxy.rds")
decomp_data_yxy <- read_rds("decomp_data_yxy.rds")

```

```{r bar graphs by cum, fig.width=9.5, fig.height=8, echo=FALSE}
network_nodes <- global_netstats_cum %>% 
  ggplot( aes(time, node_count), y=node_count) +
  geom_bar(stat="identity", fill = "#990000", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Node Count")

network_edges <- global_netstats_cum %>% 
  ggplot( aes(time, edge_count), y=edge_count) +
  geom_bar(stat="identity", fill = "#DA3330", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Edge Count")

network_wtd_edges <- global_netstats_cum %>% 
  ggplot( aes(time, wtd_edge_count), y=wtd_edge_count) +
  geom_bar(stat="identity", fill = "#D96403", width = 0.7) +
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Weighted Edge Count")

network_kmax <- global_netstats_cum %>% 
  ggplot( aes(time, kmax), y=kmax) +
  geom_bar(stat="identity", fill = "#eaaa31", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Max K-Core")

network_commits <- global_netstats_cum %>% 
  ggplot( aes(time, commits), y=commits) +
  geom_bar(stat="identity", fill = "#000058", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Total Commits")

network_isolates <- global_netstats_cum %>% 
  ggplot( aes(time, isolates), y=isolates) +
  geom_bar(stat="identity", fill = "#628ed8", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Isolate Count")

network_dyads <- global_netstats_cum %>% 
  ggplot( aes(time, dyads), y=dyads) +
  geom_bar(stat="identity", fill = "#1d7c6b", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Dyad Count")

####

network_nodes_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, node_count), y=node_count) +
  geom_bar(stat="identity", fill = "#990000", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Node Count")

network_edges_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, edge_count), y=edge_count) +
  geom_bar(stat="identity", fill = "#DA3330", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Edge Count")

network_wtd_edges_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, wtd_edge_count), y=wtd_edge_count) +
  geom_bar(stat="identity", fill = "#D96403", width = 0.7) +
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Weighted Edge Count")

network_kmax_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, kmax), y=kmax) +
  geom_bar(stat="identity", fill = "#eaaa31", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Max K-Core")

network_commits_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, commits), y=commits) +
  geom_bar(stat="identity", fill = "#000058", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Total Commits")

network_isolates_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, isolates), y=isolates) +
  geom_bar(stat="identity", fill = "#628ed8", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Isolate Count")

network_dyads_yxy <- global_netstats_yxy %>% 
  ggplot( aes(time, dyads), y=dyads) +
  geom_bar(stat="identity", fill = "#1d7c6b", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank()) +
  labs(y = "Dyad Count")

all_measures_alone <- grid.arrange(network_nodes, network_nodes_yxy, 
             network_edges,  network_edges_yxy,
             network_wtd_edges, network_wtd_edges_yxy,
             network_kmax, network_kmax_yxy,
             network_commits, network_commits_yxy,
             network_isolates,  network_isolates_yxy,
             network_dyads, network_dyads_yxy, 
             nrow=7, ncol=2)

setwd("~/Documents/OSS/oss-2020/src/github-network-analysis")
ggsave(file="all_measures_alone.png", all_measures_alone, width = 8, height = 10)

```

```{r, fig.width=9.5, fig.height=3}

density_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=density,group=1), size=2) + 
  labs(y = "Density (Cumulative)", x = "Year", colour = "#990000") + 
  theme_minimal() + theme(axis.title.x = element_blank())
transitivity_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=transitivity, group=1), size=2) + 
  labs(y = "Transitivity (Cumulative)", x = "Year", colour = "#D96403") + 
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain, group=1), size=2) + 
  labs(y = "Modularity (Cumulative)", x = "Year", colour = "#628ed8") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_cum_scaled<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain_scaled, group=1), size=2) + 
  labs(y = "Modularity (Scaled)", x = "Year", colour = "#1d7c6b") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_cum_logged<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain_logged, group=1), size=2) + 
  labs(y = "Modularity (Logged)", x = "Year", colour = "#600080") + 
  theme_minimal() + theme(axis.title.x = element_blank())

longitudinal_trends<-ggplot(global_netstats_cum, aes(time)) + 
  geom_line(aes(y = node_count, colour = "node_count", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edge_count/100", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "wtd_edge_count/1000", group= 3), size=2) +
  geom_line(aes(y = kmax*100, colour = "kmax*100", group = 4), size=2) +
  geom_line(aes(y = commits/100, colour = "commits/100", group= 5), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 6), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads/100", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c("#990000","#DA3330","#D96403","#eaaa31","#000058","#628ed8","#1d7c6b")) +                   
  #c( "#990000", "#D96403", "#eaaa31", "#628ed8", "#1d7c6b", "#600080", "#DA3330")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Total Change in Cumulative GitHub Networks") +
  theme_minimal() + theme(axis.title.y = element_blank()) +
  theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.15,0.8))

longitudinal_trends_yxy<-ggplot(global_netstats_yxy, aes(time)) + 
  geom_line(aes(y = node_count, colour = "node_count", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edge_count/100", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "wtd_edge_count/1000", group= 3), size=2) +
  geom_line(aes(y = kmax*100, colour = "kmax*100", group = 4), size=2) +
  geom_line(aes(y = commits/100, colour = "commits/100", group= 5), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 6), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads/100", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000","#DA3330","#D96403","#eaaa31","#000058","#628ed8","#1d7c6b")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Total Change in Year-by-Year GitHub Networks") +
  theme_minimal() + theme(axis.title.y = element_blank()) +
  theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.15,0.8))

long_trends <- grid.arrange(longitudinal_trends, longitudinal_trends_yxy, nrow=1, ncol=2)
setwd("~/Documents/OSS/oss-2020/src/github-network-analysis")
ggsave(file="longitudinal_trends.png", long_trends, width = 13, height = 4)

output <- grid.arrange(density_cum, louvain_cum_logged, transitivity_cum, nrow=1, ncol=3)
setwd("~/Documents/OSS/oss-2020/src/github-network-analysis")
ggsave(file="network_descriptives.png", output, width = 13, height = 3)
```

```{r percentage-change, echo=FALSE, fig.width=9.5}

global_netstats_cum <- global_netstats_cum %>% 
  mutate(nodes_pctcng = (node_count/lag(node_count) - 1) * 100) %>% 
  mutate(edges_pctcng = (edge_count/lag(edge_count) - 1) * 100) %>% 
  mutate(wtd_edges_pctcng = (wtd_edge_count/lag(wtd_edge_count) - 1) * 100) %>% 
  mutate(kmax_pctcng = (kmax/lag(kmax) - 1) * 100) %>%
  mutate(commits_pctcng = (commits/lag(commits) - 1) * 100) %>% 
  mutate(isolates_pctcng = (isolates/lag(isolates) - 1) * 100) %>% 
  mutate(dyads_pctcng = (dyads/lag(dyads) - 1) * 100) %>% 
  select(time, year, node_count, nodes_pctcng, edge_count, edges_pctcng, 
         wtd_edge_count, wtd_edges_pctcng, commits, commits_pctcng, 
         isolates, isolates_pctcng, dyads, dyads_pctcng, kmax, kmax_pctcng)
#global_netstats_cum
perc_change_cum <- global_netstats_cum %>% filter(time != 2008) %>% ggplot(aes(time)) + 
  geom_line(aes(y = nodes_pctcng, colour = "Nodes", group= 1), size=2) + 
  geom_line(aes(y = edges_pctcng, colour = "Edges", group= 2), size=2) +
  geom_line(aes(y = wtd_edges_pctcng, colour = "Weighted Edges", group= 3), size=2) +
  geom_line(aes(y = kmax_pctcng, colour = "K-Max Core", group= 4), size=2) +
  geom_line(aes(y = commits_pctcng, colour = "Commits", group= 5), size=2) +   
  geom_line(aes(y = isolates_pctcng, colour = "Isolates", group = 6), size=2) +
  geom_line(aes(y = dyads_pctcng, colour = "Dyads", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c("#990000","#DA3330","#D96403","#eaaa31","#628ed8","#1d7c6b","#600080")) + 
  labs(y = "Percentage Change", x = "Year", colour = "",
       title = "Percentage Change in Cumulative GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.78,0.8))

global_netstats_yxy <- global_netstats_yxy %>% 
  mutate(nodes_pctcng = (node_count/lag(node_count) - 1) * 100) %>% 
  mutate(edges_pctcng = (edge_count/lag(edge_count) - 1) * 100) %>% 
  mutate(wtd_edges_pctcng = (wtd_edge_count/lag(wtd_edge_count) - 1) * 100) %>% 
  mutate(kmax_pctcng = (kmax/lag(kmax) - 1) * 100) %>%
  mutate(commits_pctcng = (commits/lag(commits) - 1) * 100) %>% 
  mutate(isolates_pctcng = (isolates/lag(isolates) - 1) * 100) %>% 
  mutate(dyads_pctcng = (dyads/lag(dyads) - 1) * 100) %>% 
  select(time, year, node_count, nodes_pctcng, edge_count, edges_pctcng, 
         wtd_edge_count, wtd_edges_pctcng, commits, commits_pctcng, 
         isolates, isolates_pctcng, dyads, dyads_pctcng, kmax, kmax_pctcng
         )

#global_netstats_cum
perc_change_yxy <- global_netstats_yxy %>% filter(time != 2008) %>% ggplot(aes(time)) + 
  geom_line(aes(y = nodes_pctcng, colour = "Nodes", group= 1), size=2) + 
  geom_line(aes(y = edges_pctcng, colour = "Edges", group= 2), size=2) +
  geom_line(aes(y = wtd_edges_pctcng, colour = "Weighted Edges", group= 3), size=2) +
  geom_line(aes(y = kmax_pctcng, colour = "K-Max Core", group= 4), size=2) +
  geom_line(aes(y = commits_pctcng, colour = "Commits", group= 5), size=2) +   
  geom_line(aes(y = isolates_pctcng, colour = "Isolates", group = 6), size=2) +
  geom_line(aes(y = dyads_pctcng, colour = "Dyads", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c("#990000","#DA3330","#D96403","#eaaa31","#628ed8","#1d7c6b","#600080")) +
  labs(y = "Percentage Change", x = "Year", colour = "",
       title = "Percentage Change in Year-by-Year GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.78,0.8))

percent_change_comb <- grid.arrange(perc_change_cum, perc_change_yxy, nrow=1, ncol=2)
setwd("~/Documents/OSS/oss-2020/src/github-network-analysis")
ggsave(file="percent_change.png", percent_change_comb, width = 13, height = 4)

```

```{r}

full_nodelist_cum %>% filter(login == "null")
```

