---
title: "Repos per Contributor"
output: html_document
---

Next, let's look at descriptives per contributor. 

First, we have to write a desc_ctrs_summary table to the database... 

```{sql}

CREATE MATERIALIZED VIEW gh.desc_ctrs_intl_summary AS (
SELECT login, country_code, COUNT(DISTINCT slug) AS repos, COUNT(*) AS commits, SUM(additions) AS additions, SUM(deletions) AS deletions
FROM (SELECT slug, sna_intl_ctr_nodelist.login, sna_intl_ctr_nodelist.country_code_vis AS country_code, 
      EXTRACT(YEAR FROM committed_date)::int AS YEAR, additions, deletions
      FROM gh.commits_raw
      FULL JOIN gh.sna_intl_ctr_nodelist
      ON commits_raw.login = sna_intl_ctr_nodelist.login
      WHERE sna_intl_ctr_nodelist.country_code_vis IS NOT NULL) A
GROUP BY login, country_code
); 

```

And pull that into R. 

```{r setup, include=FALSE}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "data.table", "R.utils", "RPostgreSQL",
              "cowplot", "maditr", "lubridate")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get data (in rivanna)
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# grab the licenses data 
ctrs_summary <- dbGetQuery(conn, "SELECT login, repos, country_code, commits, additions, deletions  
                                   FROM gh.desc_ctrs_intl_summary")

# disconnect from postgresql
dbDisconnect(conn)
```

```{r}
# group_by login and get total users_per_repo
repos_per_user <- ctrs_summary %>% 
  group_by(repos) %>% 
  count() %>% 
  rename(totals = n) %>% 
  filter(repos != 0)  

repos_per_user

# recode user ranges into categories  
repos_per_user$repos <- cut(repos_per_user$repos, 
                            breaks=c(0,1,3,5,10,50,100,100000), 
                            labels=c("1", "2-3", "4-5", "6-10", 
                                     "11-50", "51-100", "101+"))
# get the percentage breakdowns
summarized_breakdown <- repos_per_user %>% 
  drop_na() %>% 
  group_by(repos) %>% 
  mutate(new_totals = sum(totals)) %>% 
  select(-totals) %>%   
  distinct(repos, .keep_all = TRUE) %>% 
  mutate(percent = round(new_totals * 100 / sum(repos_per_user$totals), 2))

sum(summarized_breakdown$percent) 

summarized_breakdown
```

Then, we graph those results and beautify the graph a little bit. 

```{r users_per_repo_graph}

# create a color palette
uva_colors <- c(
  `dark red`    = "#990000",
  `orange`      = "#E57200",
  `yellow`      = "#eaaa31",
  `green`       = "#1d7c6b",
  `dark blue`   = "#232D4B", 
  `light blue`  = "#628ed8", 
  #`pink`        = "#7f345a",
  `purple`      = "#4c1f36")

# a function that extracts the hex codes from this vector by name
uva_cols <- function(...) {
  cols <- c(...)
  if (is.null(cols))
    return (uva_colors)
  uva_colors[cols]
}

# create labels for our graph
df <- cbind.data.frame(c("1 repo\n(23.6%)",
                         "2-3 repos\n(23.5%)",
                         "4-5 repos\n(12.0%)",
                         "6-10 repos\n(14.7%)", 
                         "11-50 repos\n(19.9%)",
                         "51-100 (3.4%)",
                         "101+ (3.0%)"),
                         summarized_breakdown$new_totals)
colnames(df) <- c("repos", "totals")

# apply the palette to the graph 
pal <- c(uva_cols("dark blue"),       # 1 ctr
         #uva_cols("pink"),     # 2 ctrs
         uva_cols("green"),
         uva_cols("light blue"),
         uva_cols("dark red"),     # 11-50 ctrs  
         uva_cols("orange"),        # 201-1000
         uva_cols("purple"),
         uva_cols("yellow"))     # 3-5 ctrs

# create the tree map 
treemap::treemap(df, 
        index="repos", 
        vSize="totals",
        palette = pal, 
        title="Number of repositories per contributor (International Data, 2008-19)",
        fontsize.labels=c(12,1,1,1,1,1,1,1), 
        fontsize.title=15)

```





