---
title: "Untitled"
output: html_document
---


```{r cars}
rm(list = ls())

for (pkg in c("tidyverse", "igraph", "data.table", "R.utils", "countrycode",
              "RPostgreSQL", "cowplot", "maditr", "gt", "tidytext")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195",
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

#github user with emails
ctrs_data <- dbGetQuery(conn, "SELECT * FROM gh.ctrs_extra")

# disconnect from postgresql database 
dbDisconnect(conn)
```

```{r}

# FUNCTIONS FOR STANDARDIZING INSTIUTIONS IN ACADEMIC AND GOVERNMENT SECTORS

standardize_gov <- function(df, institution){

  library("tidyverse")
  library("tidytable")

  #institution <- enquo(institution)
 df <- df %>%
    #as.data.table() %>%
    ## this code will be implemented below
    dt_mutate(institution = tolower(!!institution), institution = trimws(institution)) %>%
    separate(institution, ("institution"), "\\(", extra = "drop") %>%
    dt_mutate(institution = str_replace_all(institution, "\\b(united states)\\b", "u.s.")) %>%
    # specific to the us gov manual and a-z index
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)((?<!library of )congress)\\b"),
                                   yes = "u.s. congress", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(judicial branch|federal agency - judicial)\\b"),
                                   yes = "u.s. judicial branch", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(legislative branch|the legislative branch|federal agency - legislative)\\b"),
                                   yes = "u.s. legislative branch", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(federal agency - executive|^executive department sub|executive branch: departments|executive department)\\b"),
                                   yes = "u.s. executive branch", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(executive branch: the president|the executive office of the president|executive office of the president)\\b"),
                                yes = "executive office of the u.s. president", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(quasi-official agencies|u.s. quasi-official agencies)\\b"),
                                   yes = "u.s. quasi-official governmental institution", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(Executive Branch: Independent Agencies and Government Corporations|independent agency)\\b"),
                                yes = "u.s. independent agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(independent board, commission, committee)\\b"),
                                yes = "u.s. independent board, commission, committee", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(international organizations)\\b"),
                                   yes = "u.s. international organizations", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^export bank|export-import bank of the u.s.)\\b"),
                                   yes = "export/import bank of the u.s.", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(geological survey)\\b"),
                                   yes = "u.s. geological survey", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^fossil energy)\\b"),
                                   yes = "u.s. fossil energy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^forest service)\\b"),
                                   yes = "u.s. forest service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^senate)\\b"),
                                   yes = "u.s. senate", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^mint)\\b"),
                                   yes = "u.s. mint", no = institution)) %>%

    # high level departments (non-defense)
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(congress—u.s. house of representatives|house of representatives)\\b"),
                                   yes = "u.s. house of representatives", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(congress—u.s. senate|u.s. senate)\\b"),
                                   yes = "u.s. senate", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(agriculture department|usda|department of agriculture|u.s. department of agriculture|dept of ag|dept of ag.|dept. of ag.|u.s. dept of ag|us dept of ag|u.s. dept. of ag.|u.s. agriculture department)\\b"),
                                   yes = "u.s. department of agriculture", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of commerce|^commerce department)\\b"),
                                   yes = "u.s. department of commerce", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of education|doed|education department)\\b"),
                                   yes = "u.s. department of education", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of energy|doe|energy department)\\b"),
                                   yes = "u.s. department of energy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of health and human services|hhs|u.s. department of health & human services|health and human services department)\\b"),
                                   yes = "u.s. department of health and human services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of homeland security|dhs|homeland security department)\\b"),
                                   yes = "u.s. department of homeland security", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of housing and urban development|hud|housing and urban development, department of)\\b"),
                                   yes = "u.s. department of housing and urban development", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of justice|doj|justice department)\\b"),
                                   yes = "u.s. department of justice", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of labor|dol|labor department)\\b"),
                                   yes = "u.s. department of labor", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of state|state department)\\b"),
                                   yes = "u.s. department of state", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of the interior|interior department)\\b"),
                                   yes = "u.s. department of the interior", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of the treasury|treasury department)\\b"),
                                   yes = "u.s. department of the treasury", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(us department of veterans affairs|department of veterans affairs|veterans affairs department)\\b"),
                                   yes = "u.s. department of veterans affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of transportation|transportation department)\\b"),
                                   yes = "u.s. department of transportation", no = institution)) %>%
    # us intelligence and defense
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(defense department|us dod|u.s. dod|u.s. d.o.d.|dept of defense|department of defense)\\b"),
                                   yes = "u.s. department of defense", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(CIA|central intelligence agency)\\b"),
                                   yes = "u.s. central intelligence agency", no = institution)) %>%
    #dt_mutate(institution = ifelse(test = str_detect(string = institution,
    #                                                 pattern = "\\b(?i)(defense finance and accounting service(?! debt)|dfas|defense finance and accounting service)\\b"),
    #                               yes = "u.s. defense finance and accounting service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(debt and claims management center|defense finance and accounting service debt and claims management center)\\b"),
                                   yes = "u.s. defense finance and accounting service - debt and claims management center", no = institution)) %>%
    #dt_mutate(institution = ifelse(test = str_detect(string = institution,
    #                                                 pattern = "\\b(?i)(air force research laboratory|air force research labs)\\b"),
    #                               yes = "u.s. air force research laboratory", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(air force reserve|us air force reserve command)\\b"),
                                   yes = "u.s. air force reserve command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(air force(?! reserve)|department of the air force|us air force)\\b"),
                                   yes = "u.s. air force", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of the army|us army(?! corps)|army(?! corps)|u.s. army(?! corps))\\b"),
                                   yes = "u.s. department of the army", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(army corps of engineers|corps of engineers)\\b"),
                                   yes = "u.s. army corps of engineers", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(department of the navy|us navy|navy|u.s. navy)\\b"),
                                   yes = "u.s. department of the navy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(cyber and infrastructure security agency|cisa|cybersecurity and infrastructure security agency)\\b"),
                                   yes = "u.s. cybersecurity and infrastructure security agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(director of national intelligence, office of|director of national intelligence|office of director of national intelligence)\\b"),
                                   yes = "u.s. office of director of national intelligence", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(coast guard)\\b"),
                                   yes = "u.s. coast guard", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(health affairs, assistant secretary of defense for|assistant secretary of defense for health affairs)\\b"),
                                   yes = "u.s. assistant secretary of defense for health affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(marine corps|marines|the marines)\\b"),
                                   yes = "u.s. marine corps", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(u.s. military academy, west point|west point military academy|west point)\\b"),
                                   yes = "u.s. military academy, west point", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(european command)\\b"),
                                   yes = "u.s. european command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(northern command)\\b"),
                                   yes = "u.s. northern command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(pacific command)\\b"),
                                   yes = "u.s. pacific command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(southern command)\\b"),
                                   yes = "u.s. southern command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(strategic command)\\b"),
                                   yes = "u.s. strategic command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(central command)\\b"),
                                   yes = "u.s. central command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(special forces operations command)\\b"),
                                   yes = "u.s. special operations command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national guard)\\b"),
                                   yes = "u.s. national guard", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national guard)\\b"),
                                yes = "u.s. national guard", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national defense university)\\b"),
                                   yes = "u.s. national defense university", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(information resource management college|national defense university icollege|college of information and cyberspace|national defense university - college of information and cyberspace)\\b"),
                                   yes = "u.s. national defense university - college of information and cyberspace", no = institution)) %>% 

    # bureaus
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
            pattern = "\\b(?i)(economics and statistics service|economics, statistics, and cooperative service|economic research service)\\b"),
                                   yes = "u.s. economic research service", no = institution)) %>% # ers
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(environmental management|environmental management, office of|office of environmental management)\\b"),
                                   yes = "u.s. office of environmental management", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(engraving and printing, bureau of|bureau of engraving and printing)\\b"),
                                   yes = "u.s. bureau of engraving and printing", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(economic analysis, bureau of|bureau of economic analysis)\\b"), # bea
                                   yes = "u.s. bureau of economic analysis", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(fiscal service, bureau of the|bureau of the fiscal service)\\b"),
                                   yes = "u.s. bureau of the fiscal service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(industry and security, bureau of|bureau of industry and security)\\b"),
                                   yes = "u.s. bureau of industry and security", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(justice statistics, bureau of|bureau of justice statistics)\\b"),
                                   yes = "u.s. bureau of justice statistics", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(labor statistics, bureau of|bureau of labor statistics)\\b"), # bls
                                   yes = "u.s. bureau of labor statistics", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(land management, bureau of|bureau of land management)\\b"), # blm
                                   yes = "u.s. bureau of land management", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(reclamation, bureau of|bureau of reclamation)\\b"),
                                   yes = "u.s. bureau of reclamation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(safety and environmental enforcement, bureau of|bureau of safety and environmental enforcement)\\b"),
                                   yes = "u.s. bureau of safety and environmental enforcement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(transportation statistics, bureau of|bureau of transportation statistics)\\b"),
                                   yes = "u.s. bureau of transportation statistics", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(ca-cst code reuse library|ca/cst/systems integration & innovation division|consular affairs, bureau of|bureau of consular affairs)\\b"),
                                   yes = "u.s. bureau of consular affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
          pattern = "\\b(?i)(bureau of ocean energy management, regulation, & enforcement|ocean energy management, bureau of|bureau of ocean energy management)\\b"),
                                   yes = "u.s. bureau of ocean energy management", no = institution)) %>% # boem
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
    pattern = "\\b(?i)(alcohol, tobacco, firearms and explosives bureau|alcohol, tobacco, and firearms division|alcohol, tobacco, firearms and explosives bureau|bureau of alcohol, tobacco, and firearms|bureau of alcohol, tobacco, firearms and explosives)\\b"), # ATF = acronym
                                   yes = "u.s. bureau of alcohol, tobacco, firearms and explosives", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(international labor affairs, bureau of|bureau of international labor affairs)\\b"), # ATF = acronym
                                   yes = "u.s. bureau of international labor affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(bureau of the census|census bureau|us census bureau)\\b"),
                                   yes = "u.s. census bureau", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(bureau of bureau of indian affairs|indian affairs|bureau of indian affairs)\\b"),
                                   yes = "u.s. bureau of indian affairs", no = institution)) %>%

    # offices
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)((?<!multifamily )housing office|office of housing)\\b"),
                                   yes = "u.s. office of housing", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(Multifamily Housing Office)\\b"),
                                yes = "u.s. office of multifamily housing", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(compliance, office of|office of compliance)\\b"),
                                   yes = "u.s. office of compliance", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(comptroller of the currency, office of|office of comptroller of the currency|office of the comptroller of the currency)\\b"),
                                   yes = "u.s. office of the comptroller of the currency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(disability employment policy, office of|office of disability employment policy)\\b"),
                                   yes = "u.s. office of disability employment policy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
 pattern = "\\b(?i)(Elementary and Secondary Education, Office of|office of elementary and secondary education|u.s. office of elementary and secondary education|innovation and improvement office|office of innovation and improvement)\\b"),
                                   yes = "u.s. office of elementary and secondary education", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(government ethics, office of|office of government ethics)\\b"),
                                   yes = "u.s. office of government ethics", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(justice programs, office of|office of justice programs)\\b"),
                                   yes = "u.s. office of justice programs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(juvenile justice and delinquency prevention, office of|office of juvenile justice and delinquency prevention)\\b"),
                                   yes = "u.s. office of juvenile justice and delinquency prevention", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(manufactured housing programs, office of|office of manufactured housing programs)\\b"),
                                   yes = "u.s. office of manufactured housing programs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(minority health, office of|office of minority health)\\b"),
                                   yes = "u.s. office of minority health", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(natural resources revenue, office of|office of natural resources revenue)\\b"),
                                   yes = "u.s. office of natural resources revenue", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(nuclear energy, office of|office of nuclear energy)\\b"),
                                   yes = "u.s. office of nuclear energy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(pardon attorney, office of|office of pardon attorney)\\b"),
                                   yes = "u.s. office of pardon attorney", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(postsecondary education, office of|office of postsecondary education)\\b"),
                                   yes = "u.s. office of postsecondary education", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(refugee resettlement, office of|office of refugee resettlement)\\b"),
                                   yes = "u.s. office of refugee resettlement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(science and technology policy, office of|office of science and technology policy)\\b"),
                                   yes = "u.s. office of science and technology policy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(servicemember affairs, office of|office of servicemember affairs)\\b"),
                                   yes = "u.s. office of servicemember affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(special counsel, office of|office of special counsel)\\b"),
                                   yes = "u.s. office of special counsel", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(special education and rehabilitative services, office of|office of special education and rehabilitative services)\\b"),
                                   yes = "u.s. office of special education and rehabilitative services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(surface mining, reclamation and enforcement, office of|office of surface mining, reclamation and enforcement)\\b"),
                                   yes = "u.s. office of surface mining, reclamation and enforcement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(child support enforcement, office of|child support enforcement, office of)\\b"),
                                   yes = "u.s. office of child support enforcement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(career, technical, and adult education, office of|office of career, technical, and adult education)\\b"),
                                   yes = "u.s. office of career, technical, and adult education", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                           pattern = "\\b(?i)(scientific and technical information, office of|office of scientific and technical information)\\b"),
                                   yes = "u.s. office of scientific and technical information", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(violence against women, office on|office on violence against women|office on violence against women)\\b"),
                                   yes = "u.s. office on violence against women", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(office of surface mining, reclamation and enforcement|office of surface mining reclamation and enforcement)\\b"),
                                   yes = "u.s. office of surface mining reclamation and enforcement", no = institution)) %>%

    # courts
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
    pattern = "\\b(?i)(supreme court of the u.s.|the supreme court|supreme court of the us|the supreme court of the u.s.|SCOTUS|u.s. supreme court)\\b"),
                                   yes = "supreme court of the u.s.", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(court of appeals for veterans claims)\\b"),
                                   yes = "u.s. court of appeals for veterans claims", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(court of appeals for the armed forces)\\b"),
                                   yes = "u.s. court of appeals for the armed forces", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(court of appeals for the federal circuit)\\b"),
                                   yes = "u.s. court of appeals for the federal circuit", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(court of federal claims)\\b"),
                                   yes = "u.s. court of federal claims", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(court of international trade)\\b"),
                                   yes = "u.s. court of international trade", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(bankruptcy courts)\\b"),
                                   yes = "u.s. bankruptcy courts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(judicial circuit courts of appeal|circuit courts of appeal|u.s. judicial circuit courts of appeal|u.s. circuit courts of appeal|u.s. courts of appeal)\\b"),
                                   yes = "u.s. circuit courts of appeal", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(federal court interpreters)\\b"),
                                   yes = "u.s. federal court interpreters", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(lower courts)\\b"),
                                   yes = "u.s. lower courts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(special courts)\\b"),
                                   yes = "u.s. special courts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(tax court)\\b"),
                                   yes = "u.s. tax court", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(court services and offender supervision|court services and offender supervision agency for the district of columbia|court services and offender supervision agency)\\b"),
                                   yes = "u.s. court services and offender supervision agency", no = institution)) %>%

    # other organizations
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(Fire Administration|USFA)\\b"),
                                   yes = "u.s. fire administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                   pattern = "\\b(?i)(Federal Home Loan Mortgage Corporation|Freddie Mac|federal home loan mortgage corporation)\\b"),
                                 yes = "u.s. federal home loan mortgage corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(federal national mortgage association|Fannie Mae)\\b"),
                                   yes = "u.s. federal national mortgage association", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(Government National Mortgage Association|Ginnie Mae)\\b"),
                                   yes = "u.s. government national mortgage association", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(united states access board|access board)\\b"),
                                   yes = "u.s. access board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(administration for children and families|acf)\\b"),
                                   yes = "u.s. administration for children and families", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(advanced distributed learning|adl|adl-aicc)\\b"), # collaboration
                                   yes = "u.s. advanced distributed learning", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution, # contains a collaboration
                                                     pattern = "\\b(?i)(agency for healthcare research and quality|ahrq|agency for health care policy and research)\\b"),
                                   yes = "u.s. agency for healthcare research and quality", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(agency for international development|usaid)\\b"),
                                   yes = "u.s. agency for international development", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(agricultural marketing service|ams)\\b"),
                                   yes = "u.s. agricultural marketing service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(food and agriculture, national institute of|nifa|national institute of food and agriculture|cooperative state research, education, and extension service|national institute of food and agriculture (nifa))\\b"),
                                   yes = "u.s. national institute of food and agriculture", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(advanced research projects agency-energy|energy transformation acceleration fund|arpa-e)\\b"),
                                   yes = "u.s. advanced research projects agency-energy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(Agricultural Research Service|agriculture research service|usda ars)\\b"), # ARS = acronym
                                   yes = "u.s. agricultural research service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(ames laboratory|ames lab|doe ames laboratory|the ames lab)\\b"),
                                   yes = "ames laboratory", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(ames research center)\\b"),
                                   yes = "nasa ames research center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(tax and trade bureau|bureau of alcohol and tobacco tax and trade|alcohol and tobacco tax and trade bureau)\\b"), # TTB = acronym
                                   yes = "u.s. alcohol and tobacco tax and trade bureau", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(alcohol, drug abuse, and mental health administration|samhsa|substance abuse and mental health services administration)\\b"), # samhsa = acronym
                                   yes = "u.s. substance abuse and mental health services administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national railroad passenger corporation|amtrak)\\b"),
                                   yes = "amtrak", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(animal and plant health inspection service|aphis|animal and plant health inspection service)\\b"),
                                   yes = "u.s. animal and plant health inspection service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(archives, national archives and records administration|nara|national archives and records administration)\\b"),
                                   yes = "u.s. national archives and records administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(arctic llc|arctic landscape conservation cooperative)\\b"),
                                   yes = "u.s. arctic landscape conservation cooperative", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(arctic research commission)\\b"),
                                   yes = "u.s. arctic research commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(argonne national laboratory|argonne national lab|argonne national labs)\\b"),
                                   yes = "argonne national laboratory", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(african development bank|african development foundation|nigeria trust fund|banque africaine de développement|banque africaine de dveloppement|banque africaine de developpement)\\b"),
                                   yes = "african development bank group", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national institute of peace|institute of peace)\\b"), #az-specific
                                   yes = "u.s. institute of peace", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national institute of health|nih|national institutes of health)\\b"),
                                   yes = "u.s. national institutes of health", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(food and agriculture, national institute of|nifa|national institute of food and agriculture)\\b"),
                                   yes = "u.s. national institute of food and agriculture", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(national cancer institute|nci|us nci|national cancer institute)\\b"),
                                   yes = "u.s. national cancer institute", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(barry goldwater scholarship and excellence in education foundation|barry goldwater scholarship|barry goldwater foundation|barry goldwater program)\\b"),
                                   yes = "barry m. goldwater scholarship and excellence in education program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(commission on presidential scholars|presidential scholars commission)\\b"),
                                   yes = "u.s. commission on presidential scholars", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
    pattern = "\\b(?i)(center for parent information and resources|parent information and resources center|parent information and resources center)\\b"),
                                   yes = "center for parent information and resources", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(cdc - public health informatics lab|center for disease control|center for disease control and prevention|centers for disease control and prevention)\\b"),
                                   yes = "u.s. centers for disease control and prevention", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(centers for medicare & medicaid services|centers for medicare and medicaid services)\\b"),
                                   yes = "u.s. centers for medicare and medicaid services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(civil rights division, department of justice|u.s. dept of justice, civil rights division)\\b"),
                                   yes = "u.s. department of justice, civil rights division", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(civil rights, department of health and human services office for)\\b"),
                                   yes = "u.s. department of health and human services, office for civil rights", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(civil rights, department of education office of)\\b"),
                                   yes = "u.s. department of education, office for civil rights", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                  pattern = "\\b(?i)(corporation for national & community service|corporation for national and community service)\\b"),
                                   yes = "u.s. corporation for national and community service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(business usa)\\b"),
                                   yes = "business usa", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(sandia national laboratory)\\b"),
                                   yes = "sandia national laboratories", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(council of inspectors general on integrity and efficiency|council of the inspectors general on integrity and efficiency|inspectors general)\\b"),
                                   yes = "u.s. council of the inspectors general on integrity and efficiency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(global media, agency for|Agency for Global Media)\\b"),
                                   yes = "u.s. agency for global media", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
      pattern = "\\b(?i)(grain inspection, packers, and stockyards administration|grain inspection, packers and stockyards administration|grain inspection packers and stockyards administration)\\b"),
                                   yes = "u.s. grain inspection, packers and stockyards administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(japan-u.s. friendship commission|japan-us friendship commission)\\b"),
                                   yes = "japan-u.s. friendship commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(john f. kennedy center for performing arts|kennedy center)\\b"),
                                   yes = "john f. kennedy center for the performing arts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(medical payment advisory commission|medpac|medicare payment advisory commission)\\b"),
                                   yes = "u.s. medicare payment advisory commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(medicaid and chip payment and access commission|macpac|medicaid and chip payment and access commission)\\b"),
                                   yes = "u.s. medicaid and chip payment and access commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(occupational safety & health review commission|occupational safety and health review commission)\\b"),
                                   yes = "u.s. occupational safety and health review commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(rural business and cooperative programs|rural business-cooperative service)\\b"),
                                   yes = "u.s. rural business-cooperative service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(u.s. abilityone|u.s. abilityone commission|abilityone|abilityone commission)\\b"),
                                   yes = "u.s. abilityone commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(us-cert|us computer emergency readiness team|computer emergency readiness team)\\b"),
                                   yes = "u.s. computer emergency readiness team", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^weather service|^national weather service)\\b"),
                                   yes = "u.s. national weather service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(^secret service$)\\b"),
                                   yes = "u.s. secret service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(postal service|us postal service|usps|u.s. postal service|the u.s. postal service|the us postal service)\\b"),
                                   yes = "u.s. postal service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(noaa fisheries|noaa|nmfs|national marine fisheries service)\\b"),
                                   yes = "u.s. national marine fisheries service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(capitol visitor center)\\b"),
                                   yes = "u.s. capitol visitor center", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(trade representative)\\b"),
                                   yes = "u.s. trade representative", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                     pattern = "\\b(?i)(fedstats|federal interagency council on statistical policy)\\b"),
                                   yes = "u.s. federal interagency council on statistical policy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(federal mediation and conciliation service|mediation and conciliation service|FMCS)\\b"),
                                   yes = "u.s. federal mediation and conciliation service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(agriculture library|us agriculture library|us library of agriculture|national library of agriculture)\\b"), # specific to az-index
                                yes = "u.s. national library of agriculture", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(patent and trademark office)\\b"), # specific to az-index
                                yes = "u.s. patent and trademark office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(industrial college of the armed forces)\\b"),
                                yes = "dwight d. eisenhower school for national security and resource strategy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(fleet forces command)\\b"),
                                yes = "u.s. fleet forces command", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of special education and rehabilitative services)\\b"),
                                yes = "u.s. office of special education and rehabilitative services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of fossil energy|u.s. fossil energy)\\b"),
                                yes = "u.s. office of fossil energy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national prevention information network|prevention information network|cdc npin)\\b"),
                                yes = "cdc - national prevention information network", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of child support enforcement|ocse)\\b"),
                                yes = "u.s. office of child support enforcement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(customs and border protection)\\b"),
                                yes = "u.s. customs and border protection", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(immigration and customs enforcement|us customs)\\b"), # ice
                                yes = "u.s. immigration and customs enforcement", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(citizenship and immigration services|immigration and citizenship services)\\b"),
                                yes = "u.s. citizenship and immigration services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(community planning and development|office of community planning and development)\\b"),
                                yes = "u.s. office of community planning and development", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(fair housing and equal opportunity|office of fair housing and equal opportunity)\\b"),
                                yes = "u.s. office of fair housing and equal opportunity", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of policy development and research|policy development and research)\\b"),
                                yes = "u.s. office of policy development and research", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(bureau of prisons|federal bureau of prisons)\\b"),
                                yes = "u.s. federal bureau of prisons", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(immigrant and employee rights section|office of immigrant and employee rights)\\b"),
                                yes = "u.s. office of immigrant and employee rights", no = institution)) %>%
   # specific to az-index
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(interpol)\\b"),
                                yes = "u.s. national central bureau - interpol", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of the pardon attorney|office of pardon attorney)\\b"),
                                yes = "u.s. office of the pardon attorney", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(marshals service)\\b"),
                                yes = "u.s. marshals service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(parole commission)\\b"),
                                yes = "u.s. parole commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(hour and wage division|wage and hour division)\\b"),
                                yes = "u.s. wage and hour division", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of disability employment policy)\\b"),
                                yes = "u.s. office of disability employment policy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(agency for toxic substances and disease registry|ATSDR)\\b"),
                                yes = "cdc - agency for toxic substances and disease registry", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of occupational safety and health|NIOSH)\\b"),
                                yes = "cdc - national institute of occupational safety and health", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(environmental protection agency|EPA)\\b"),
                                yes = "u.s. environmental protection ageny", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(general services administration|GSA)\\b"),
                                yes = "u.s. general services administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(securities and exchange commission|SEC)\\b"),
                                yes = "u.s. securities and exchange commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of personnel management|OPM)\\b"),
                                yes = "u.s. office of personnel management", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense intelligence agency|DIA)\\b"),
                                yes = "u.s. defense intelligence agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(consumer financial protection bureau|CFPB|u.s. bureau of consumer financial protection|Bureau of Consumer Financial Protection)\\b"),
                                yes = "u.s. consumer financial protection bureau", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(botanic garden)\\b"),
                                yes = "u.s. botanic garden", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(capitol police)\\b"),
                                yes = "u.s. capitol police", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal register|office of the federal register)\\b"),
                                yes = "u.s. office of the federal register", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(postal inspection service)\\b"),
                                yes = "u.s. postal inspection service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(commission of fine arts)\\b"),
                                yes = "u.s. commission of fine arts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(commodity futures trading commission)\\b"),
                                yes = "u.s. commodity futures trading commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(bureau of consumer financial protection)\\b"),
                                yes = "u.s. bureau of consumer financial protection", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(chemical safety board)\\b"),
                                yes = "u.s. chemical safety board", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(commission on security and cooperation in europe|helsinki commission)\\b"),
                                yes = "u.s. commission on security and cooperation in europe", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(election assistance commission)\\b"),
                                yes = "u.s. election assistance commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(nuclear regulatory commission)\\b"),
                                yes = "u.s. nuclear regulatory commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
           pattern = "\\b(?i)(northwest power and conservation council|northwest power planning council|pacific northwest electric power and conservation planning council)\\b"),
                              yes = "u.s. northwest power and conservation council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of cuba broadcasting)\\b"),
                                yes = "radio and tv martí", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(commission on international religious freedom)\\b"),
                                yes = "u.s. commission on international religious freedom", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(international trade commission)\\b"),
                                yes = "u.s. international trade commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(international trade administration)\\b"),
                                yes = "u.s. international trade administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(sentencing commission)\\b"),
                                yes = "u.s. sentencing commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(trade and development agency)\\b"),
                                yes = "u.s. trade and development agency", no = institution)) %>%

    # white house
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(council of economic advisers)\\b"),
                                yes = "u.s. council of economic advisers", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(council on environmental quality)\\b"),
                                yes = "u.s. council on environmental quality", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national security council)\\b"),
                                yes = "u.s. national security council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of management and budget)\\b"),
                                yes = "u.s. office of management and budget", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of national drug control policy)\\b"),
                                yes = "u.s. office of national drug control policy", no = institution)) %>%

    # exec
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(marketing and regulatory programs)\\b"),
                                yes = "usda - marketing and regulatory programs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(rural development)\\b"),
                                yes = "usda - rural development", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of standards and technology)\\b"),
                                yes = "u.s. national institute of standards and technology", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national oceanic and atmospheric administration)\\b"),
                                yes = "u.s. national oceanic and atmospheric administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(unified combatant commands)\\b"),
                                yes = "u.s. unified combatant commands", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)((?<!sandia )national laboratories)\\b"),
                                yes = "u.s. national laboratories", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(power administrations)\\b"),
                                yes = "u.s. power administrations", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(science office|office of science(?! and technology policy))\\b"),
                                yes = "u.s. office of science", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(food and drug administration)\\b"),
                                yes = "u.s. food and drug administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal emergency management agency|FEMA)\\b"),
                                yes = "u.s. federal emergency management agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(administration for native americans|ANA)\\b"),
                                yes = "u.s. administration for native americans", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national passport information center|NPIC)\\b"),
                                yes = "u.s. national passport information center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal emergency management agency|FEMA)\\b"),
                                yes = "u.s. federal emergency management agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint military intelligence college|national defense intelligence college|national intelligence university)\\b"),
                                yes = "u.s. national intelligence university", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint program executive office for chemical and biological defense|JPEO-CBRND)\\b"),
                                yes = "u.s. joint program executive office for chemical and biological defense", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of corrections)\\b"),
                                yes = "u.s. national institute of corrections", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national flood insurance program)\\b"),
                                yes = "u.s. national flood insurance program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(center for food safety and applied nutrition)\\b"),
                                yes = "u.s. center for food safety and applied nutrition", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(committee for the implementation of textile agreements)\\b"),
                                yes = "u.s. committee for the implementation of textile agreements", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint forces staff college)\\b"),
                                yes = "u.s. joint forces staff college", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national war college)\\b"),
                                yes = "u.s. national war college", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(weights and measures division)\\b"),
                                yes = "u.s. weights and measures division", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national heart, lung, and blood institute)\\b"),
                                yes = "nih - national heart, lung, and blood institute", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of diabetes and digestive and kidney diseases)\\b"),
                                yes = "nih - national institute of diabetes and digestive and kidney diseases", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of mental health)\\b"),
                                yes = "nih - national institute of mental health", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of neurological disorders and stroke)\\b"),
                                yes = "nih - national institute of neurological disorders and stroke", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(arthritis, musculoskeletal and skin diseases, national institute of|niams|national institute of arthritis, musculoskeletal and skin diseases|national institute of arthritis musculoskeletal and skin diseases)\\b"),
                                yes = "nih - national institute of arthritis, musculoskeletal and skin diseases", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of deafness and other communication disorders)\\b"),
                                yes = "nih - national institute of deafness and other communication disorders", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national ocean service)\\b"),
                                yes = "u.s. national ocean service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(seafood inspection program)\\b"),
                                yes = "u.s. seafood inspection program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal housing administration)\\b"),
                                yes = "u.s. federal housing administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national institute of justice)\\b"),
                                yes = "u.s. national institute of justice", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(center for parent information and resources)\\b"),
                                yes = "u.s. center for parent information and resources", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(rehabilitation services administration)\\b"),
                                yes = "u.s. rehabilitation services administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(bonneville power administration)\\b"),
                                yes = "u.s.  bonneville power administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(southeastern power administration)\\b"),
                                yes = "u.s. southeastern power administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(southwestern power administration)\\b"),
                                yes = "u.s. southwestern power administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(western area power administration)\\b"),
                                yes = "u.s. western area power administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(rural housing service)\\b"),
                                yes = "u.s. rural housing service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(rural utilities service)\\b"),
                                yes = "u.s. rural utilities service", no = institution)) %>%
    #USDA
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(natural resources conservation service)\\b"),
                                yes = "u.s. natural resources conservation service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(risk management agency)\\b"),
                                yes = "u.s. risk management agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(center for nutrition policy and promotion)\\b"),
                                yes = "u.s. center for nutrition policy and promotion", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(farm service agency)\\b"),
                                yes = "u.s. farm service agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(food and nutrition service)\\b"),
                                yes = "u.s. food and nutrition service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(food safety and inspection service)\\b"),
                                yes = "u.s. food safety and inspection service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(foreign agricultural service)\\b"),
                                yes = "u.s. foreign agricultural service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national agricultural statistics service)\\b"),
                                yes = "u.s. national agricultural statistics service", no = institution)) %>%
    #DOC
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(economic development administration)\\b"),
                                yes = "u.s. economic development administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(minority business development agency)\\b"),
                                yes = "u.s. minority business development agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national technical information service)\\b"),
                                yes = "u.s. national technical information service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national telecommunications and information administration)\\b"),
                                yes = "u.s. national telecommunications and information administration", no = institution)) %>%
    #DOD
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense acquisition university)\\b"),
                                yes = "u.s. defense acquisition university", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense advanced research projects agency)\\b"),
                                yes = "u.s. defense advanced research projects agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense commissary agency)\\b"),
                                yes = "u.s. defense commissary agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense contract audit agency)\\b"),
                                yes = "u.s. defense contract audit agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense contract management agency)\\b"),
                                yes = "u.s. defense contract management agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense health agency)\\b"),
                                yes = "u.s. defense health agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense information systems agency)\\b"),
                                yes = "u.s. defense information systems agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense logistics agency)\\b"),
                                yes = "u.s. defense logistics agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense security cooperation agency)\\b"),
                                yes = "u.s. defense security cooperation agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense security service)\\b"),
                                yes = "u.s. defense security service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense technical information center)\\b"),
                                yes = "u.s. defense technical information center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense threat reduction agency)\\b"),
                                yes = "u.s. defense threat reduction agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal voting assistance program)\\b"),
                                yes = "u.s. federal voting assistance program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint chiefs of staff)\\b"),
                                yes = "u.s. joint chiefs of staff", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(missile defense agency)\\b"),
                                yes = "u.s. missile defense agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national geospatial-intelligence agency)\\b"),
                                yes = "u.s. national geospatial-intelligence agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national reconnaissance office)\\b"),
                                yes = "u.s. national reconnaissance office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national security agency|NSA)\\b"),
                                yes = "u.s. national security agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(pentagon force protection agency)\\b"),
                                yes = "u.s. pentagon force protection agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of economic adjustment)\\b"),
                                yes = "u.s. office of economic adjustment", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(prisoner of war and missing in action accounting agency)\\b"),
                                yes = "u.s. prisoner of war and missing in action accounting agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(uniformed services university of the health sciences)\\b"),
                                yes = "u.s. uniformed services university of the health sciences", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(washington headquarters services)\\b"),
                                yes = "u.s. washington headquarters services", no = institution)) %>%
    # DOE
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(english language acquisition office)\\b"),
                                yes = "u.s. english language acquisition office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal student aid information center)\\b"),
                                yes = "u.s. federal student aid information center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(institute of education sciences)\\b"),
                                yes = "u.s. institute of education sciences", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(energy information administration)\\b"),
                                yes = "u.s. energy information administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal energy regulatory commission)\\b"),
                                yes = "u.s. federal energy regulatory commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national nuclear security administration)\\b"),
                                yes = "u.s. national nuclear security administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(administration for community living)\\b"),
                                yes = "u.s. administration for community living", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(indian health service)\\b"),
                                yes = "u.s. indian health service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national health information center)\\b"),
                                yes = "u.s. national health information center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(president's council on fitness, sports and nutrition)\\b"),
                                yes = "u.s. president's council on fitness, sports and nutrition", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal law enforcement training center)\\b"),
                                yes = "u.s. federal law enforcement training center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal protective service)\\b"),
                                yes = "u.s. federal protective service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(transportation security administration)\\b"),
                                yes = "u.s. transportation security administration", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of lead hazard control and healthy homes)\\b"),
                                yes = "u.s. office of lead hazard control and healthy homes", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(public and indian housing)\\b"),
                                yes = "u.s. public and indian housing", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(antitrust division)\\b"),
                                yes = "u.s. antitrust division", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(community oriented policing services)\\b"),
                                yes = "u.s. community oriented policing services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(drug enforcement administration)\\b"),
                                yes = "u.s. drug enforcement administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(elder justice initiative)\\b"),
                                yes = "u.s. elder justice initiative", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(executive office for immigration review)\\b"),
                                yes = "u.s. executive office for immigration review", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal bureau of investigation)\\b"),
                                yes = "u.s. federal bureau of investigation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(foreign claims settlement commission)\\b"),
                                yes = "u.s. foreign claims settlement commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(trustee program)\\b"),
                                yes = "u.s. trustee program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(employee benefits security administration)\\b"),
                                yes = "u.s. employee benefits security administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(employment and training administration)\\b"),
                                yes = "u.s. employment and training administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(mine safety and health administration)\\b"),
                                yes = "u.s. mine safety and health administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(job corps)\\b"),
                                yes = "u.s. job corps", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(mine safety and health administration)\\b"),
                                yes = "u.s. mine safety and health administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(occupational safety and health administration|OSHA)\\b"),
                                yes = "u.s. occupational safety and health administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(veterans' employment and training service)\\b"),
                                yes = "u.s. veterans' employment and training service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(women's bureau)\\b"),
                                yes = "u.s. women's bureau", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(arms control and international security)\\b"),
                                yes = "u.s. arms control and international security", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(economic growth, energy, and the environment)\\b"),
                                yes = "u.s. economic growth, energy, and the environment", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(political affairs)\\b"),
                                yes = "u.s. political affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(public diplomacy and public affairs)\\b"),
                                yes = "u.s. public diplomacy and public affairs", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal consulting group)\\b"),
                                yes = "u.s. federal consulting group", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(fish and wildlife service)\\b"),
                                yes = "u.s. fish and wildlife service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national park service)\\b"),
                                yes = "u.s. national park service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(internal revenue service|IRS)\\b"),
                                yes = "u.s. internal revenue service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(taxpayer advocacy panel)\\b"),
                                yes = "u.s. taxpayer advocacy panel", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal aviation administration)\\b"),
                                yes = "u.s. federal aviation administration", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal highway administration)\\b"),
                                yes = "u.s. federal highway administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal motor carrier safety administration)\\b"),
                                yes = "u.s. federal motor carrier safety administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal railroad administration)\\b"),
                                yes = "u.s. federal railroad administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal transit administration)\\b"),
                                yes = "u.s. federal transit administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(maritime administration)\\b"),
                                yes = "u.s. maritime administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national highway traffic safety administration)\\b"),
                                yes = "u.s. national highway traffic safety administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of the assistant secretary for research and technology)\\b"),
                                yes = "u.s. office of the assistant secretary for research and technology", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(pipeline and hazardous materials safety administration)\\b"),
                                yes = "u.s. pipeline and hazardous materials safety administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(saint lawrence seaway development corporation)\\b"),
                                yes = "saint lawrence seaway development corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national cemetery administration)\\b"),
                                yes = "u.s. national cemetery administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(veterans benefits administration)\\b"),
                                yes = "u.s. veterans benefits administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(veterans health administration)\\b"),
                                yes = "u.s. veterans health administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
    pattern = "\\b(?i)((?<!mental )health resources administration|(?<!mental )health services administration|hrsa|health resources and services administration)\\b"),
                                yes = "u.s. health resources and services administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(architect of the capitol)\\b"),
                                yes = "u.s. architect of the capitol", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(library of congress)\\b"),
                                yes = "u.s. library of congress", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(congressional budget office)\\b"),
                                yes = "u.s. congressional budget office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(government accountability office)\\b"),
                                yes = "u.s. government accountability office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(government publishing office)\\b"),
                                yes = "u.s. government publishing office", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(house office of inspector general)\\b"),
                                yes = "u.s. house office of inspector general", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(house office of the clerk)\\b"),
                                yes = "u.s. house office of the clerk", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(open world leadership center)\\b"),
                                yes = "u.s. open world leadership center", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(congressional research service)\\b"),
                                yes = "u.s. congressional research service", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                pattern = "\\b(?i)(copyright office)\\b"),
                              yes = "u.s. copyright office", no = institution)) %>%
    ##
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal communications commission|FCC)\\b"),
                                yes = "u.s. federal communications commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal housing finance agency|FHFA)\\b"),
                                yes = "u.s. federal housing finance agency", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(endangered species program)\\b"),
                                yes = "u.s. endangered species program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(migratory bird conservation commission)\\b"),
                                yes = "u.s. migratory bird conservation commission", no = institution)) %>%
    ##
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(legal services corporation)\\b"),
                                yes = "u.s. legal services corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national constitution center)\\b"),
                                yes = "u.s. national constitution center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national gallery of art)\\b"),
                                yes = "u.s. national gallery of art", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(state justice institute)\\b"),
                                yes = "u.s. state justice institute", no = institution)) %>%
    ##
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(advisory council on historic preservation)\\b"),
                                yes = "u.s. advisory council on historic preservation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(citizens' stamp advisory committee)\\b"),
                                yes = "u.s. citizens' stamp advisory committee", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(coordinating council on juvenile justice and delinquency prevention)\\b"),
                                yes = "u.s. coordinating council on juvenile justice and delinquency prevention", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal financial institutions examination council)\\b"),
                                yes = "u.s. federal financial institutions examination council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal geographic data committee)\\b"),
                                yes = "u.s. federal geographic data committee", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal laboratory consortium for technology transfer)\\b"),
                                yes = "u.s. federal laboratory consortium for technology transfer", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal library and information center committee)\\b"),
                                yes = "u.s. federal library and information center committee", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(interagency alternative dispute resolution working group)\\b"),
                                yes = "u.s. interagency alternative dispute resolution working group", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(interagency committee for the management of noxious and exotic weeds)\\b"),
                                yes = "u.s. interagency committee for the management of noxious and exotic weeds", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(interagency council on homelessness)\\b"),
                                yes = "u.s. interagency council on homelessness", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(chief acquisition officers council)\\b"),
                                yes = "u.s. chief acquisition officers council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(chief financial officers council)\\b"),
                                yes = "u.s. chief financial officers council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(chief human capital officers council)\\b"),
                                yes = "u.s. chief human capital officers council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(chief information officers council)\\b"),
                                yes = "u.s. chief information officers council", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(commission on civil rights)\\b"),
                                yes = "u.s. commission on civil rights", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(consumer product safety commission)\\b"),
                                yes = "u.s. consumer product safety commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(defense nuclear facilities safety board)\\b"),
                                yes = "u.s. defense nuclear facilities safety board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(equal employment opportunity commission)\\b"),
                                yes = "u.s. equal employment opportunity commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(farm credit administration)\\b"),
                                yes = "u.s. farm credit administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal deposit insurance corporation)\\b"),
                                yes = "u.s. federal deposit insurance corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal election commission)\\b"),
                                yes = "u.s. federal election commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal labor relations authority)\\b"),
                                yes = "u.s. federal labor relations authority", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal maritime commission)\\b"),
                                yes = "u.s. federal maritime commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal mine safety and health review commission)\\b"),
                                yes = "u.s. federal mine safety and health review commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal reserve system)\\b"),
                                yes = "u.s. federal reserve system", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal retirement thrift investment board)\\b"),
                                yes = "u.s. federal retirement thrift investment board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal trade commission|FTC)\\b"),
                                yes = "u.s. federal trade commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(institute of museum and library services)\\b"),
                                yes = "u.s. institute of museum and library services", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(merit systems protection board)\\b"),
                                yes = "u.s. merit systems protection board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(institute of museum and library services)\\b"),
                                yes = "u.s. institute of museum and library services", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national aeronautics and space administration)\\b"),
                                yes = "u.s. national aeronautics and space administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national capital planning commission)\\b"),
                                yes = "u.s. national capital planning commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national credit union administration)\\b"),
                                yes = "u.s. national credit union administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national endowment for the arts)\\b"),
                                yes = "u.s. national endowment for the arts", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national endowment for the humanities)\\b"),
                                yes = "u.s. national endowment for the humanities", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national labor relations board)\\b"),
                                yes = "u.s. national labor relations board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national mediation board)\\b"),
                                yes = "u.s. national mediation board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national science foundation|BMI)\\b"),
                                yes = "u.s. national science foundation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national transportation safety board)\\b"),
                                yes = "u.s. national transportation safety board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(peace corps)\\b"),
                                yes = "u.s. peace corps", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(pension benefit guaranty corporation)\\b"),
                                yes = "u.s. pension benefit guaranty corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(postal regulatory commission)\\b"),
                                yes = "u.s. postal regulatory commission", no = institution)) %>%


    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(privacy and civil liberties oversight board)\\b"),
                                yes = "u.s. privacy and civil liberties oversight board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(railroad retirement board)\\b"),
                                yes = "u.s. railroad retirement board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(selective service system)\\b"),
                                yes = "u.s. selective service system", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(small business administration)\\b"),
                                yes = "u.s. small business administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(social security administration)\\b"),
                                yes = "u.s. social security administration", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(surface transportation board)\\b"),
                                yes = "u.s. surface transportation board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal interagency committee on education)\\b"),
                                yes = "u.s. federal interagency committee on education", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(marine mammal commission)\\b"),
                                yes = "u.s. marine mammal commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national council on disability)\\b"),
                                yes = "u.s. national council on disability", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national park foundation)\\b"),
                                yes = "u.s. national park foundation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(northern border regional commission)\\b"),
                                yes = "u.s. northern border regional commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(nuclear waste technical review board)\\b"),
                                yes = "u.s. nuclear waste technical review board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(social security advisory board)\\b"),
                                yes = "u.s. social security advisory board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(indian arts and crafts board)\\b"),
                                yes = "u.s. indian arts and crafts board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal financing bank)\\b"),
                                yes = "u.s. federal financing bank", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(indoor air quality)\\b"),
                                yes = "u.s. indoor air quality", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national pesticide information center)\\b"),
                                yes = "u.s. national pesticide information center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(wireless telecommunications bureau)\\b"),
                                yes = "u.s. wireless telecommunications bureau", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(office of investor education and advocacy)\\b"),
                                yes = "u.s. office of investor education and advocacy", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal executive boards)\\b"),
                                yes = "u.s. federal executive boards", no = institution)) %>%

    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(armed forces retirement home)\\b"),
                                yes = "u.s. armed forces retirement home", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal accounting standards advisory board)\\b"),
                                yes = "u.s. federal accounting standards advisory board", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(holocaust memorial museum)\\b"),
                                yes = "u.s. holocaust memorial museum", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint board for the enrollment of actuaries)\\b"),
                                yes = "u.s. joint board for the enrollment of actuaries", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint fire science program)\\b"),
                                yes = "u.s. joint fire science program", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(meat and poultry hotline)\\b"),
                                yes = "u.s. meat and poultry hotline", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national indian gaming commission)\\b"),
                                yes = "u.s. national indian gaming commission", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national interagency fire center)\\b"),
                                yes = "u.s. national interagency fire center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(judicial panel on multidistrict litigation)\\b"),
                                yes = "u.s. judicial panel on multidistrict litigation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(joint congressional committee on inaugural ceremonies)\\b"),
                                yes = "u.s. joint congressional committee on inaugural ceremonies", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(farm credit system insurance corporation)\\b"),
                                yes = "u.s. farm credit system insurance corporation", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(federal judicial center)\\b"),
                                yes = "u.s. federal judicial center", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(national foundation on the arts and the humanities)\\b"),
                                yes = "u.s. national foundation on the arts and the humanities", no = institution)) %>%
    dt_mutate(institution = ifelse(test = str_detect(string = institution,
                                                  pattern = "\\b(?i)(overseas private investment corporation)\\b"),
                                yes = "u.s. overseas private investment corporation", no = institution)) %>%


    df
}

```


```{r}
# load local functions 
#source("/sfs/qumulo/qhome/kb7hp/git/oss-2020/scripts/standardize_gov.R")

ctrs_gov <- ctrs_data %>% 
  standardize_gov(ctrs_data$company) %>% 
  select(login, institution, email)
ctrs_gov


```











































