---
title: "International Repo Networks"
author: "Brandon L. Kramer"
date: "11/6/2019"
output: html_document
---

```{r loading edgelist data}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(),
                 dbname = "sdad_data",
                 host = "postgis_2",
                 port = 5432L,
                 user = Sys.getenv("db_userid"),
                 password = Sys.getenv("db_pwd"))

# query the bipartite edgelist data from github data  
bp_edgelist <- dbGetQuery(conn, "SELECT login, slug, weight FROM github.intl_st_bp_edges")

# disconnect from postgresql
dbDisconnect(conn)
```

# Constructing Single Mode Networks 

```{r}
# this code is taken from network scientists to reduce bipartite networks to single mode networks 
oss_matrix <- spMatrix(nrow=length(unique(bp_edgelist$login)),
              ncol=length(unique(bp_edgelist$slug)),
              i = as.numeric(factor(bp_edgelist$login)),
              j = as.numeric(factor(bp_edgelist$slug)),
              x = rep(1, length(as.numeric(bp_edgelist$login))))
row.names(oss_matrix) <- levels(factor(bp_edgelist$login))
colnames(oss_matrix) <- levels(factor(bp_edgelist$slug))
rm(bp_edgelist)
```

```{r}
# we then multiply these incidence matrices and impute zeroes to prevent self loops 
login_matrix <- tcrossprod(oss_matrix)
diag(login_matrix) <- 0
rm(oss_matrix)

# convert it into a network 
login_network <- graph_from_adjacency_matrix(login_matrix, mode = "undirected", weighted = TRUE)

# examining the network statistics 
login_network <- simplify(login_network, remove.loops = TRUE)
plot(login_network, vertex.size=.02, vertex.label=NA)

gsize(login_network); gorder(login_network)
login_nodelist$degree <- igraph::degree(login_network) 
arrange(login_nodelist, desc(degree))
```














