---
title: "05 Data Map Collapsible Tree"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(collapsibleTree)
library(dplyr)
library(tidyr)
```

# Construct Dataframe
```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
OSS <- data.frame(
    Sector = c(
        "Academic", "Academic","Academic", "Academic", "Academic",    
        "Academic","Academic","Academic","Academic","Academic",
        "Academic","Academic","Academic","Academic","Academic", 
        "Academic",
      
        
        "Business","Business","Business","Business","Business", 
        "Business", "Business", "Business", "Business", "Business",
          "Business","Business","Business","Business","Business", 
        "Business", "Business", "Business", "Business", "Business",
          "Business","Business","Business","Business","Business", 
        "Business", "Business", "Business", "Business", "Business",
        "Business","Business",
       
        "Household", "Household", "Household", "Household", "Household", "Household", "Household",
      "Household","Household", "Household","Household", "Household",
        
        "Government", "Government","Government","Government","Government",
        "Government","Government", "Government", "Government","Government",
        "Government", "Government","Government", "Government","Government",
        "Government","Government","Government","Government", "Government",
        "Government","Government", "Government",  "Government",
        
        "Nonprofit","Nonprofit","Nonprofit","Nonprofit","Nonprofit",
         "Nonprofit","Nonprofit","Nonprofit","Nonprofit","Nonprofit",  
        "Nonprofit","Nonprofit","Nonprofit","Nonprofit","Nonprofit",
         "Nonprofit","Nonprofit","Nonprofit","Nonprofit","Nonprofit",
        "Nonprofit",
        
        "Geographic","Geographic","Geographic",  "Geographic","Geographic",
        "Geographic","Geographic","Geographic",  "Geographic","Geographic",
        "Geographic","Geographic","Geographic",  "Geographic"
    ),
    DataSource = c(
         #academic
        "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
        "GitHub","GitHub", "GitHub","GitHub","GitHub",
        "Hipo Labs", "Hipo Labs","Hipo Labs","Hipo Labs",
        
      #business
      "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
      "GitHub","GitHub", "GitHub","GitHub","GitHub",

      
      "Forbes 2018 Fortune-1000",  "Forbes 2018 Fortune-1000", "Forbes 2018 Fortune-1000", "Forbes 2018 Fortune-1000","Forbes 2018 Fortune-1000","Forbes 2018 Fortune-1000","Forbes 2018 Fortune-1000",
      
      "Forbes 2019 Fortune-1000",  "Forbes 2019 Fortune-1000", "Forbes 2019 Fortune-1000", "Forbes 2019 Fortune-1000","Forbes 2019 Fortune-1000","Forbes 2019 Fortune-1000","Forbes 2019 Fortune-1000",
      
      "Forbes 2020 Global-2000", "Forbes 2020 Global-2000", "Forbes 2020 Global-2000", "Forbes 2020 Global-2000", "Forbes 2020 Global-2000", "Forbes 2020 Global-2000",
     
      #household
       "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
      "GitHub","GitHub", "GitHub","GitHub","GitHub",
      
    #gov  
      "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
      "GitHub","GitHub", "GitHub","GitHub","GitHub",
      "US Gov A-Z Index", "US Gov A-Z Index", "US Gov A-Z Index", "US Gov A-Z Index",
      "US Gov FFRDCs", "US Gov FFRDCs", "US Gov FFRDCs", "US Gov FFRDCs", "US Gov FFRDCs", "US Gov FFRDCs",
      "US Gov Manual", "US Gov Manual",
    
    #non profit
      "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
      "GitHub","GitHub", "GitHub","GitHub","GitHub",
   
      "Forbes Top-100 Charities","Forbes Top-100 Charities","Forbes Top-100 Charities", "Forbes Top-100 Charities", "Forbes Top-100 Charities", 
   
      "United Nation NGOs", "United Nation NGOs", 
      "US Gov FFRDCs", "US Gov FFRDCs",
    
     #international
      "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent", "GHTorrent",
      "GitHub","GitHub", "GitHub","GitHub","GitHub",
      "DataHub" , "DataHub" 
    ),
    Variables = c(
       #academic
        "login(rename, username)", "company (affiliation)", "city", "state","country code", "latitude",  "longitude",  #7
        "username","commits", "additions", "deletions", "created at", #5
        "institution name", "country code", "email domain", "website",  #4
        
        #business
         "login(rename, username)","company (affiliation)","city","state","country code",  "latitude",  "longitude",  #7 
        "username","commits", "additions", "deletions", "created at", #5
        
        "company", "industry", "location", "revenue", "profits", "assets", "market value",  #7
         "company", "industry", "location", "revenue", "profits", "assets", "market value",  #7
         "company", "country", "sales", "profits", "assets",  "market value", #6
        
        #household
         "login(rename, username)", "company (affiliation)", "city", "state","country code", "latitude",  "longitude",  #7
        "username","commits", "additions", "deletions", "created at", 
        
        #gov
        "login(rename, username)","company (affiliation)","city","state","country code",  "latitude",  "longitude", 
        "username","commits", "additions", "deletions", "created at",
        "gov branch", "gov agency", "gov subagency", "website",
        "ffrdc", "ffrdc admin", "ffrdc url", "ffrdc location", "gov agency", "gov subagency",
        "gov branch", "gov agency",
        
         #nonprofit
        "login(rename, username)","company (affiliation)","city","state","country code",  "latitude",  "longitude", 
        "username","commits", "additions", "deletions", "created at",
        
        "organization","acronym", "private support", "total revenue", "donor dependency", 
   
      "organization", "acronym", 
      "ffrdc", "ffrdc admin", 
      
        "login(rename, username)","company (affiliation)","city","state","country code",  "latitude",  "longitude", 
        "username","commits", "additions", "deletions", "created at",
        "continent name", "country code"
    )
)

#check whether the number of each sector-datasource are correct
check <- OSS %>%
  group_by(Sector, DataSource)%>%
  summarize(N=n())
```

# Collapsible Tree
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
collapsibleTree(OSS, 
                c("Sector", "DataSource", "Variables"), 
                collapsed = T,
                fill ="#E57200"
)
```

