---
title: "CRAN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
rm(list = ls())
# load packages 
for (pkg in c("tidyverse",  "RPostgreSQL", "maditr", "dlstats", "fuzzywuzzyR", "tm", "Hmisc")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195",
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# query the users_gh data from github data 
cran_data <- dbGetQuery(conn, "SELECT * FROM cran.cran_maintainers")

# disconnect from postgresql
dbDisconnect(conn)
```

We want to de-duplicate the data so that we are sending maintainers all the information in one email and at the most recent email 
Step 1: Fix the duplicate emails 
Step 2: Fix the discrepencies in slighly different names 

```{r}
fix_emails <- function(data_frame){
         data_frame %>% 
         mutate(email = trimws(email),
         email = tolower(email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(acoppola@college.harvard.edu)\\b"), yes = "acoppola@alumni.harvard.edu", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(aim@stats.uwo.ca)\\b"), yes = "aimcleod@uwo.ca", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(ajesusmp@cibio.up.pt)\\b"), yes = "ajesusmp@ugr.es", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(alberto.arcagni@unimib.it)\\b"), yes = "alberto.arcagni@uniroma1.it", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(alexander.duerre@udo.edu)\\b"), yes = "alexander.duerre@tu-dortmund.de", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(andrew.parnell@ucd.ie)\\b"), yes = "andrew.parnell@mu.ie", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(andy.teucher@gov.bc.ca)\\b"), yes = "andy.teucher@gmail.com", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(arnima@hafro.is)\\b"), yes = "arni.magnusson@ices.dk", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(h.wickham@gmail.com)\\b"), yes = "hadley@rstudio.com", no = email),
         email = ifelse(test = str_detect(string = email, pattern = "\\b(?i)(myrmecocystus\\+r@gmail.com|sckott@protonmail.com)\\b"), 
                        yes = "myrmecocystus@gmail.com", no = email)
             )
         }

email_count <- cran_data %>% 
    mutate(email = trimws(email),
           email = tolower(email)) %>% 
    fix_emails() %>% 
    group_by(email) %>% 
    count() %>% arrange(-n)

totals <- cran_data %>%
  mutate(
    maintainer = str_replace_all(maintainer, "\'", ""),
    maintainer = str_replace_all(maintainer, "\"", ""),
    maintainer = str_replace_all(maintainer, "\\.", ""),
    maintainer = str_replace_all(maintainer, "\\,", ""),
    #maintainer = iconv(maintainer, to='ASCII//TRANSLIT'),
    maintainer = trimws(maintainer),
    maintainer = tolower(maintainer),
    maintainer = str_replace_all(maintainer, " (a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z) ", " "),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(Gabor Csardi)\\b"), yes = "gábor csárdi", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(Jing Xu)\\b"), yes = "xu jing", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(a c del re|a del re)\\b"), yes = "ac del re", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(artem kelvtsov)\\b"), yes = "artem klevtsov", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(ai mcleod|a i mcleod|a.i. mcleod|ian mcleod|ian mcleod|a mcleod)\\b"), 
                             yes = "adam sparks", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(a. j. muñoz-pajares|a.j. muñoz-pajares|a muñoz-pajares)\\b"), 
                        yes = "aj muñoz-pajares", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(alejandro saavedra nieves)\\b"), 
                             yes = "alejandro saavedra-nieves", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(alessandrobarbiero)\\b"), yes = "alessandro barbiero", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(alejandro jimenez rico)\\b"), yes = "alejandro jiménez rico", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(ali santacruz)\\b"), yes = "alí santacruz", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(j a torres-matallana|j.a. torres-matallana|j torres-matallana)\\b"), 
                          yes = "ja torres-matallana", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(aurelie siberchicot)\\b"), yes = "aurélie siberchicot", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(james joseph balamuta)\\b"), yes = "james balamuta", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, 
                                            pattern = "\\b(?i)(mohamed el fodil ihaddaden ihaddaden)\\b"), yes = "mohamed el fodil ihaddaden", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(os keyes)\\b"), yes = "oliver keyes", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(greg jefferis)\\b"), yes = "gregory jefferis", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(przemyslaw biecek)\\b"), yes = "przemysław biecek", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(rich fitzjohn|richard j fitzjohn)\\b"), yes = "richard fitzjohn", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(richie cotton)\\b"), yes = "richard cotton", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(gertjanssenswillen@uhasseltbe)\\b"), 
                          yes = "gert janssenswillen", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(gergely daroczi)\\b"), yes = "gergely daróczi", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(kent russell)\\b"), yes = "kenton russell", no = maintainer),
      maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(b n mandal|b mandal)\\b"), yes = "baidya nath mandal", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(alexis sarda)\\b"), yes = "alexis sarda-espinosa", no = maintainer),
     maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(alicja wolny-dominiak)\\b"), yes = "alicja wolny–dominiak", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(andrew thomas jones)\\b"), yes = "andrew jones", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(bjorn andersson)\\b"), yes = "björn andersson", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(brad boehmke)\\b"), yes = "bradley boehmke", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(benjamin baumer)\\b"), yes = "ben baumer", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(bettina grün)\\b"), yes = "bettina gruen", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(p lafaye de micheaux)\\b"), yes = "pierre lafaye de micheaux", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(marcelino de la cruz rot)\\b"), yes = "marcelino de la cruz", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(ha kestler)\\b"), yes = "hans kestler", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(zaghdoudi taha)\\b"), yes = "taha zaghdoudi", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(claus thorn ekstrøm)\\b"), yes = "claus ekstrom", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(michael wayne kearney)\\b"), yes = "michael kearney", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(schumacher dirk)\\b"), yes = "dirk schumacher", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(ks srikanth|srikanth komala sheshachala|srikanth ks)\\b"), 
                        yes = "komala sheshachala srikanth", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(li jun)\\b"), yes = "jun li", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(oyvind langsrud)\\b"), yes = "øyvind langsrud", no = maintainer),
    
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(de troyer ewoud)\\b"), yes = "ewoud de troyer", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(joshua ulrich)\\b"), yes = "josh ulrich", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(kjetil bhalvorsen)\\b"), yes = "kjetil halvorsen", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(hufkens koen)\\b"), yes = "koen hufkens", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(^markus loecher)\\b"), 
                        yes = "markus loecher", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(oldemar rodriguez r)\\b"), yes = "oldemar rodriguez", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(neeraj dhanraj bokde)\\b"), yes = "neeraj bokde", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(dr ranjit kumar paul)\\b"), yes = "ranjit kumar paul", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(^robert myles)\\b"), yes = "robert myles mcdonnell", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(sahir rai bhatnagar)\\b"), yes = "sahir bhatnagar", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(yifan \\(ethan\\) xu)\\b"), yes = "yifan xu", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(sy han \\(steven\\) chiou)\\b"), yes = "sy han chiou", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(s iacus|stefano maria iacus|stefano miacus)\\b"), yes = "stefano iacus", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(thomas alexander gerds)\\b"), yes = "thomas gerds", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(tim keitt)\\b"), yes = "timothy keitt", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(vakili kaveh)\\b"), yes = "kaveh vakili", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(virgilio gomez-rubio)\\b"), yes = "virgilio gómez-rubio", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(yihui zhou|yihui zhou$)\\b"), yes = "yi-hui zhou", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(c helbert)\\b"), yes = "celine helbert", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(c helbert)\\b"), yes = "celine helbert", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(d labes)\\b"), yes = "detlew labes", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(k domijan)\\b"), yes = "katarina domijan", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(dj bennett)\\b"), yes = "dom bennett", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(baker ed)\\b"), yes = "ed baker", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(daniel rodriguez)\\b"), yes = "daniel rodriguez-perez", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(elizabeth gonzalez estrada)\\b"), yes = "elizabeth gonzalez-estrada", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(helios de rosario)\\b"), yes = "helios de rosario-martinez", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(gilligan jonathan m)\\b"), yes = "gilligan jonathan", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(kevin allan sales rodrigues)\\b"), yes = "kevin rodrigues", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(w kyle hamilton)\\b"), yes = "william kyle hamilton", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(l finos)\\b"), yes = "livio finos", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(kidzinski l)\\b"), yes = "lukasz kidzinski", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(m j zondervan-zwijnenburg)\\b"), yes = "maj zondervan-zwijnenburg", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(p filzmoser)\\b"), yes = "peter filzmoser", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(dr rob briers)\\b"), yes = "rob briers", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(r wayne oldford)\\b"), yes = "wayne oldford", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(s kovalchik)\\b"), yes = "stephanie kovalchik", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(stephen h-t lihn)\\b"), yes = "stephen horng-twu lihn", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(sumathi|sumathi r)\\b"), yes = "r sumathi", no = maintainer),
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(y foucher)\\b"), yes = "yohann foucher", no = maintainer), 
    maintainer = ifelse(test = str_detect(string = maintainer, pattern = "\\b(?i)(m binois)\\b"), yes = "mickael binois", no = maintainer)
         ) %>%
  fix_emails() %>% 
  group_by(maintainer, email) %>% 
  summarise(pkgs = paste(pkg, collapse = ", ")) %>% 
  select(maintainer, email, pkgs) %>% 
  full_join(email_count, by = "email") %>% 
  select(maintainer, email, n, pkgs) %>% 
  arrange(-n) #%>% filter(n > 1) #) 25 & n > 7)
# Artem Kelvtsov, 

deduped_names_df <- totals %>% 
  janitor::get_dupes(email, n) %>% 
  group_by(email, n) %>% 
  summarise(pkgs = paste(pkgs, collapse = ", "),
            maintainer = paste(maintainer, collapse = "; ")) %>% 
  separate(col = maintainer, into = "maintainer", sep = ";", extra = "drop") %>% 
  select(maintainer, email, n, pkgs)
deduped_names <- deduped_names_df %>% select(email) 

totals_cleaned <- totals %>% 
  filter(!email %in% deduped_names$email) %>% 
  bind_rows(deduped_names_df) %>% 
  arrange(-n)

multiple_emails <- totals_cleaned %>% 
  janitor::get_dupes(maintainer, n) %>% 
  arrange(-n) %>% 
  group_by(maintainer) %>% 
  summarise(n = sum(n),
            pkgs = paste(pkgs, collapse = ", "),
            email = paste(email, collapse = ", ")) %>% 
  select(maintainer, email, n, pkgs) %>% 
  arrange(-n) %>% 
  mutate(multiple_emails = 1)

multiple_emails_list <- totals_cleaned %>% 
  janitor::get_dupes(maintainer, n) %>% 
  arrange(-n) %>% 
  select(email)

cran_all <- totals_cleaned %>% 
  filter(!email %in% multiple_emails_list$email) %>% 
  mutate(multiple_emails = 0) %>% 
  bind_rows(multiple_emails) %>% 
  arrange(-n)

cran_dup_emails <- cran_all %>% 
  filter(multiple_emails == 1) %>% 
  unnest(email = strsplit(email, ", "))

cran_all_final <- cran_all %>% 
  filter(multiple_emails == 0) %>%
  bind_rows(cran_dup_emails) %>% 
  arrange(-n)
  
# let's capitalize all of the names now 
cran_all_final$maintainer <- str_to_title(cran_all_final$maintainer)

# and get rid accents in case Qualtrics doesn't like those 
cran_all_final$maintainer_asc <- iconv(cran_all_final$maintainer, to='ASCII//TRANSLIT')

cran_all_final <- cran_all_final %>% select(maintainer, maintainer_asc, everything())

write_csv(cran_all_final, "/sfs/qumulo/qhome/kb7hp/oss-2020/data/cran_all_maintainers_final.csv")

```

```{r}








# testing 
dedup <- totals %>% 
  janitor::get_dupes(email, n) 

dedup <- dedup %>% 
  filter(grepl("alex", maintainer))

choices <- dedup$maintainer
word <- "alexis sarda"

init_proc = FuzzUtils$new()      
PROC = init_proc$Full_process    
PROC1 = tolower                  

init_scor = FuzzMatcher$new()    
SCOR = init_scor$WRATIO          

init <- FuzzExtract$new()        

init$Extract(string = word, 
             sequence_strings = choices, 
             processor = PROC, 
             scorer = SCOR)

# deduplicate 
test_dd <- init$Dedupe(contains_dupes = dedup$maintainer, threshold = 89L, scorer = SCOR)
class(test_dd)


```
```{r}
library(RecordLinkage)

zotero<-data.frame(
   Year=c(2016,2016,2010,2010,2010,2010),
   Author=c("Jones, Erik","Hassner, Pierre;","Adams, Laura L.;","Tichý, Lukáš;","Tichý, Lukáš;","Tichy, L.;"),
   Title=c("Book Reviews","Book Reviews","Book Reviews","Can Iran Reduce EU Dependence on Russian Gas?","Can Iran Reduce EU Dependence on Russian Gas?","can iran reduce eu dependence onrussian gas")
)
 
# Converting the special characters
zotero$Author_new <- iconv(zotero$Author, from = '', to = "ASCII//TRANSLIT")
zotero$Author_new <- tolower(zotero$Author_new)
zotero$Author_new <- gsub("[[:punct:]]", "", zotero$Author_new)
 
# Removing punctuation making it lowercase
zotero$Title_new <- gsub("[[:punct:]]", "", zotero$Title)
zotero$Title_new <- tolower(zotero$Title_new)
 
# Removing exact duplicates
dups <- duplicated(zotero[,c("Title_new", "Author_new", "Year")])
zotero <- zotero[!dups,]
zotero

zotero$Title_dist <- sapply(zotero$Title_new, function(x) sort(levenshteinDist(x, zotero$Title_new))[2])
zotero$Author_dist <- sapply(zotero$Author_new, function(x) sort(levenshteinDist(x, zotero$Author_new))[2])

check <- zotero %>%
   group_by(Year) %>%
   filter(!between(Title_dist, 1, 5) | 
          !between(Author_dist, 1, 5))
check

### 

# testing 
dedup <- totals %>% 
  janitor::get_dupes(email, n) 

dedup <- dedup %>% 
  filter(grepl("alex", maintainer))

dedup$maintainer_dist <- sapply(dedup$maintainer, function(x) sort(levenshteinDist(x, dedup$maintainer))[2])
dedup$email_dist <- sapply(dedup$email, function(x) sort(levenshteinDist(x, dedup$email))[2])

dedup %>%
   group_by(maintainer) %>%
   filter(!between(maintainer_dist, 1, 10))
zotero

## 

df1 <- data.frame(id = c(1, 2, 3, 4, 5, 6),
              entry = c("Apple", 
                        "I love apples", 
                        "appls",
                        "Bannanas",
                        "banana", 
                        "An apple a day keeps..."))
df1$entry <- as.character(df1$entry)

df2 <- data.frame(fruit=c("apple",
                          "banana",
                          "pineapple"),
                  code=c(11, 12, 13))
df2$fruit <- as.character(df2$fruit)

library(dplyr)
library(fuzzyjoin)

df1 %>%
  stringdist_left_join(df2, by=c(entry="fruit"), ignore_case=T, method="jw", distance_col="dist") %>%
  group_by(entry) %>%
  top_n(-1) 

```



```{r}
new_totals <- totals %>% 
  rename(no_of_packages = n) %>% 
  group_by(no_of_packages) %>% 
  count() %>% 
  rename(no_of_maintainers = n) 

sum(new_totals %>% filter(no_of_packages > 4)) 

ggplot(new_totals, aes(no_of_packages, no_of_maintainers)) +
  geom_point() +
  #geom_bar(stat="identity") +
  theme_minimal() 


new_totals %>% 
  ggplot(data=new_totals) +
  geom_bar(stat="identity", aes(x=no_of_packages, y=no_of_maintainers)) +
  scale_x_discrete(limits = positions) +
  theme_minimal() 
  theme(plot.title = element_text(size=23, hjust = 0.45),
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size = 16),
        axis.title =element_text(size=18),
        axis.title.x=element_blank()) +
  labs(y = "Number of GitHub Users") +
  ggtitle("Total GitHub Users Classified by Economic Sector")

```

```{r}
cran_data



mtr_emails_clpsd <- cran_data %>% 
  mutate(maintainer = str_replace_all(maintainer, "\'", ""),
         maintainer = str_replace_all(maintainer, "\"", ""),
         maintainer = trimws(maintainer),
         email = trimws(email)) %>%
  group_by(maintainer, email) %>% 
  summarise(emails = paste(email, collapse = ", ")) %>% 
  arrange(maintainer) %>% 
  select(maintainer, emails)

mtr_pkgs_clpsd <- cran_data %>% 
  mutate(maintainer = str_replace_all(maintainer, "\'", ""),
         maintainer = str_replace_all(maintainer, "\"", ""),
         maintainer = trimws(maintainer),
         email = trimws(email)) %>%
  group_by(maintainer, email) %>% 
  summarise(pkgs = paste(pkg, collapse = ", ")) %>% 
  arrange(maintainer) %>% 
  select(maintainer, pkgs)

mtr_pkgs_clpsd %>% 
  group_by(maintainer) %>% 
  count() %>% 
  filter(n > 1) %>% 
  arrange(-n)


cran_data %>% 
  mutate(maintainer = str_replace_all(maintainer, "\'", ""),
         maintainer = str_replace_all(maintainer, "\"", ""),
         maintainer = trimws(maintainer),
         email = trimws(email)) %>%
  group_by(email, maintainer)



    
cran_data %>% group_by(email) %>% count() %>% arrange(-n)
```


```{r}

cran_downloads <- cran_stats(c("A3","aaSEA","AATtools","ABACUS","abbyyR","abc","abc.data","ABC.RAP","abcADM","ABCanalysis"))
cran_downloads
write_rds(cran_downloads, "cran_download_data.rds")


x %>% 
  
  group_by(package) %>% 
  summarize(total = sum(downloads)) %>% 
  arrange(-total)

?cran_stats

```










