---
title: "International Collaboration Networks"
author: "Brandon Kramer, José Bayoán Santiago Calderón and Gizem Korkmaz"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", 
# "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "linkprediction", "poweRlaw"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", 
              "data.table", "R.utils", "RPostgreSQL", "cowplot",
              "maditr", "lubridate", "linkprediction", "poweRlaw", 
              "plotly","gridExtra", "rmarkdown")) {library(pkg, character.only = TRUE)}

setwd("~/Documents/OSS/Data")
#setwd("~/intl-dyn-ctr-nets-cum")
global_netstats_yxy <- read_rds("global_netstats_yxy.rds")
full_nodelist_yxy <- read_rds("full_nodelist_yxy.rds")
kcore_data <- read_rds("kcore_data_yxy.rds")
decomp_data <- read_rds("decomp_data_yxy.rds")

```

```{r bar graphs by cum, fig.width=9.5, fig.height=8, echo=FALSE}
network_nodes <- global_netstats_yxy %>% 
  ggplot( aes(time, node_count), y=node_count) +
  geom_bar(stat="identity", fill = "#990000", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_edges <- global_netstats_yxy %>% 
  ggplot( aes(time, edge_count), y=edge_count) +
  geom_bar(stat="identity", fill = "#DA3330", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_wtd_edges <- global_netstats_yxy %>% 
  ggplot( aes(time, wtd_edge_count), y=wtd_edge_count) +
  geom_bar(stat="identity", fill = "#D96403", width = 0.7) +
  theme_bw() + theme(axis.title.x = element_blank())

network_kmax <- global_netstats_yxy %>% 
  ggplot( aes(time, kmax), y=kmax) +
  geom_bar(stat="identity", fill = "#eaaa31", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_commits <- global_netstats_yxy %>% 
  ggplot( aes(time, commits), y=commits) +
  geom_bar(stat="identity", fill = "#000058", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_isolates <- global_netstats_yxy %>% 
  ggplot( aes(time, isolates), y=isolates) +
  geom_bar(stat="identity", fill = "#628ed8", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_dyads <- global_netstats_yxy %>% 
  ggplot( aes(time, dyads), y=dyads) +
  geom_bar(stat="identity", fill = "#1d7c6b", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

grid.arrange(network_nodes, network_commits, 
             network_edges,  network_isolates,  
             network_wtd_edges, network_dyads, 
             network_kmax, nrow=4, ncol=2,
             top="Year-by-Year Growth in Node, Edge and Commit Counts for GitHub Networks")
```

```{r global_networks_cum descriptive trends, fig.width=9.5, echo=FALSE, layout="l-body-outset"}

ggplot(global_netstats_yxy, aes(time)) + 
  geom_line(aes(y = node_count, colour = "node_count", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edge_count/100", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "wtd_edge_count/1000", group= 3), size=2) +
  geom_line(aes(y = kmax*100, colour = "kmax*100", group = 4), size=2) +
  geom_line(aes(y = commits/100, colour = "commits/100", group= 5), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 6), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads/100", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000","#DA3330","#D96403","#eaaa31","#000058","#628ed8","#1d7c6b")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Year-by-Year Growth in GitHub Networks") +
  theme_minimal() + theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.15,0.8))

descriptives <- global_netstats_yxy %>% select(year, node_count, edge_count, 
                               wtd_edge_count, commits, isolates, dyads, kmax)
paged_table(descriptives, options = list(rows.print = 15))
```

```{r density yxy, fig.width=9.5, fig.height=8, echo=FALSE, layout="l-body-outset"}
density_yxy<-ggplot(global_netstats_yxy) + 
  geom_line(aes(x=time, y=density,group=1), size=2) + 
  labs(y = "Density (YxY)", x = "Year", colour = "#990000") + 
  theme_minimal() + theme(axis.title.x = element_blank())
transitivity_yxy<-ggplot(global_netstats_yxy) + 
  geom_line(aes(x=time, y=transitivity, group=1), size=2) + 
  labs(y = "Transitivity (YxY)", x = "Year", colour = "#D96403") + 
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_yxy<-ggplot(global_netstats_yxy) + 
  geom_line(aes(x=time, y=louvain, group=1), size=2) + 
  labs(y = "Modularity (YxY)", x = "Year", colour = "#628ed8") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_yxy_scaled<-ggplot(global_netstats_yxy) + 
  geom_line(aes(x=time, y=louvain_scaled, group=1), size=2) + 
  labs(y = "Modularity (YxY Scaled)", x = "Year", colour = "#1d7c6b") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_yxy_logged<-ggplot(global_netstats_yxy) + 
  geom_line(aes(x=time, y=louvain_logged, group=1), size=2) + 
  labs(y = "Modularity (YxY Logged)", x = "Year", colour = "#600080") + 
  theme_minimal() + theme(axis.title.x = element_blank())

all_others<-ggplot(global_netstats_yxy, aes(time)) + 
  geom_line(aes(y = node_count, colour = "node_count", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edge_count/100", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "wtd_edge_count/1000", group= 3), size=2) +
  geom_line(aes(y = kmax*100, colour = "kmax*100", group = 4), size=2) +
  geom_line(aes(y = commits/100, colour = "commits/100", group= 5), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 6), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads/100", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000","#DA3330","#D96403","#eaaa31","#000058","#628ed8","#1d7c6b")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Year-by-Year Growth in GitHub Networks") +
  theme_minimal() + theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.25,0.65))

grid.arrange(density_yxy, louvain_yxy, 
             transitivity_yxy, louvain_yxy_scaled,  
             all_others, louvain_yxy_logged, nrow=3, ncol=2,
             top="Network Measures")

network_descriptives <- global_netstats_yxy %>% 
  select(year, density, transitivity,louvain, louvain_logged, louvain_scaled)
paged_table(network_descriptives, options = list(rows.print = 15))
```

```{r percentage-change, echo=FALSE, fig.width=9.5}

global_netstats_yxy <- global_netstats_yxy %>% 
  mutate(nodes_pctcng = (node_count/lag(node_count) - 1) * 100) %>% 
  mutate(edges_pctcng = (edge_count/lag(edge_count) - 1) * 100) %>% 
  mutate(wtd_edges_pctcng = (wtd_edge_count/lag(wtd_edge_count) - 1) * 100) %>% 
  mutate(kmax_pctcng = (kmax/lag(kmax) - 1) * 100) %>%
  mutate(commits_pctcng = (commits/lag(commits) - 1) * 100) %>% 
  mutate(isolates_pctcng = (isolates/lag(isolates) - 1) * 100) %>% 
  mutate(dyads_pctcng = (dyads/lag(dyads) - 1) * 100) %>% 
  select(time, year, node_count, nodes_pctcng, edge_count, edges_pctcng, 
         wtd_edge_count, wtd_edges_pctcng, commits, commits_pctcng, 
         isolates, isolates_pctcng, dyads, dyads_pctcng, kmax, kmax_pctcng
         )
#global_netstats_cum
global_netstats_yxy %>% filter(time != 2008) %>% ggplot(aes(time)) + 
  geom_line(aes(y = nodes_pctcng, colour = "nodes_pctcng", group= 1), size=2) + 
  geom_line(aes(y = edges_pctcng, colour = "edges_pctcng", group= 2), size=2) +
  geom_line(aes(y = wtd_edges_pctcng, colour = "wtd_edges_pctcng", group= 3), size=2) +
  geom_line(aes(y = kmax_pctcng, colour = "kmax_pctcng", group= 4), size=2) +
  geom_line(aes(y = commits_pctcng, colour = "commits_pctcng", group= 5), size=2) +   
  geom_line(aes(y = isolates_pctcng, colour = "isolates_pctcng", group = 6), size=2) +
  geom_line(aes(y = dyads_pctcng, colour = "dyads_pctcng", group = 7), size=0.5) + 
  scale_colour_manual(values = 
  c("#990000","#DA3330","#D96403","#eaaa31","#628ed8","#1d7c6b","#600080")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Year-by-Year Change in Descriptive Measures for GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.78,0.8))

percentage_change <- global_netstats_yxy %>% 
  filter(year != 2008) %>% 
  select(year, nodes_pctcng, edges_pctcng, 
         wtd_edges_pctcng,commits_pctcng, 
         isolates_pctcng, dyads_pctcng, kmax_pctcng
         )
paged_table(percentage_change, options= list(rows.print = 15))
```

```{r k_core_graph, echo=FALSE, fig.width=9.5}
# graph all values 
kcore_graph <- kcore_data %>% 
  #drop_na() %>%
  ggplot(aes(core)) + 
  geom_line(aes(y = k08, colour = "k08", group= 1), size=0.5) + 
  geom_line(aes(y = k09, colour = "k09", group= 2), size=0.5) +
  geom_line(aes(y = k10, colour = "k10", group= 3), size=0.5) +
  geom_line(aes(y = k11, colour = "k11", group= 4), size=0.5) +
  geom_line(aes(y = k12, colour = "k12", group= 5), size=0.5) +
  geom_line(aes(y = k13, colour = "k13", group= 6), size=0.5) +
  geom_line(aes(y = k14, colour = "k14", group= 7), size=0.5) +
  geom_line(aes(y = k15, colour = "k15", group= 8), size=0.5) +
  geom_line(aes(y = k16, colour = "k16", group= 9), size=0.5) +
  geom_line(aes(y = k17, colour = "k17", group= 10), size=0.5) +
  geom_line(aes(y = k18, colour = "k18", group= 11), size=0.5) +
  labs(title = "K-Core Distributions for Year-by-Year GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.85,0.8)); ggplotly()
```

```{r k_core_graph_2, echo=FALSE, fig.width=9.5}
kcore_graph <- kcore_data %>% 
  drop_na() %>%
  ggplot(aes(core)) + 
  geom_line(aes(y = k08, colour = "k08", group= 1), size=0.5) + 
  geom_line(aes(y = k09, colour = "k09", group= 2), size=0.5) +
  geom_line(aes(y = k10, colour = "k10", group= 3), size=0.5) +
  geom_line(aes(y = k11, colour = "k11", group= 4), size=0.5) +
  geom_line(aes(y = k12, colour = "k12", group= 5), size=0.5) +
  geom_line(aes(y = k13, colour = "k13", group= 6), size=0.5) +
  geom_line(aes(y = k14, colour = "k14", group= 7), size=0.5) +
  geom_line(aes(y = k15, colour = "k15", group= 8), size=0.5) +
  geom_line(aes(y = k16, colour = "k16", group= 9), size=0.5) +
  geom_line(aes(y = k17, colour = "k17", group= 10), size=0.5) +
  geom_line(aes(y = k18, colour = "k18", group= 11), size=0.5) +
  labs(title = "K-Core Distributions for Year-by-Year GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.85,0.8)); ggplotly()
```
```{r decomp_graph, echo=FALSE, fig.width=9.5}
# graph all values 
decomp_graph <- decomp_data %>% 
  #drop_na() %>%
  ggplot(aes(order(decomp))) + 
  geom_point(aes(y = dc08, colour = "dc08", group= 1), size=0.5) + 
  geom_point(aes(y = dc09, colour = "dc09", group= 2), size=0.5) +
  geom_point(aes(y = dc10, colour = "dc10", group= 3), size=0.5) +
  geom_point(aes(y = dc11, colour = "dc11", group= 4), size=0.5) +
  geom_point(aes(y = dc12, colour = "dc12", group= 5), size=0.5) +
  geom_point(aes(y = dc13, colour = "dc13", group= 6), size=0.5) +
  geom_point(aes(y = dc14, colour = "dc14", group= 7), size=0.5) +
  geom_point(aes(y = dc15, colour = "dc15", group= 8), size=0.5) +
  geom_point(aes(y = dc16, colour = "dc16", group= 9), size=0.5) +
  geom_point(aes(y = dc17, colour = "dc17", group= 10), size=0.5) +
  geom_point(aes(y = dc18, colour = "dc18", group= 11), size=0.5) +
  labs(title = "Decomposition Tendencies for Cumulative GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.85,0.8)); ggplotly()
```
```{r decomp_graph_2, echo=FALSE, fig.width=9.5}
# graph all values 
decomp_graph <- decomp_data %>% 
  drop_na() %>%
  ggplot(aes(decomp)) + 
  geom_line(aes(y = dc08, colour = "dc08", group= 1), size=0.5) + 
  geom_line(aes(y = dc09, colour = "dc09", group= 2), size=0.5) +
  geom_line(aes(y = dc10, colour = "dc10", group= 3), size=0.5) +
  geom_line(aes(y = dc11, colour = "dc11", group= 4), size=0.5) +
  geom_line(aes(y = dc12, colour = "dc12", group= 5), size=0.5) +
  geom_line(aes(y = dc13, colour = "dc13", group= 6), size=0.5) +
  geom_line(aes(y = dc14, colour = "dc14", group= 7), size=0.5) +
  geom_line(aes(y = dc15, colour = "dc15", group= 8), size=0.5) +
  geom_line(aes(y = dc16, colour = "dc16", group= 9), size=0.5) +
  geom_line(aes(y = dc17, colour = "dc17", group= 10), size=0.5) +
  geom_line(aes(y = dc18, colour = "dc18", group= 11), size=0.5) +
  labs(title = "Decomposition Tendencies for Cumulative GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.85,0.8)); ggplotly()
```














