---
title: "International Collaboration Networks"
author: "Brandon Kramer, José Bayoán Santiago Calderón and Gizem Korkmaz"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", 
# "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "linkprediction", "poweRlaw"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot",
              "maditr", "lubridate", "linkprediction", "poweRlaw", "plotly","gridExtra", "rmarkdown")) {library(pkg, character.only = TRUE)}

setwd("~/Documents/OSS/Data")
#setwd("~/intl-dyn-ctr-nets-cum")
global_netstats_cum <- read_rds("global_netstats_cum.rds")
full_nodelist_cum <- read_rds("full_nodelist_cum.rds")
#setwd("~/Documents/OSS/oss-2020")
#setwd("~/intl-dyn-ctr-nets-cum")

global_netstats_cum <- global_netstats_cum %>% 
  transform(dyads = as.numeric(dyads))

```

```{r}
full_nodelist_cum %>% drop_na(kcore08) %>% count(kcore08) 

full_nodelist_cum %>% drop_na(kcore0809) %>% count(kcore0809)

global_netstats_cum
```

```{r bar graphs by cum, fig.width=9.5, fig.height=8, echo=FALSE}
network_nodes <- global_netstats_cum %>% 
  ggplot( aes(time, node_count), y=node_count) +
  geom_bar(stat="identity", fill = "#990000", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_edges <- global_netstats_cum %>% 
  ggplot( aes(time, edge_count), y=edge_count) +
  geom_bar(stat="identity", fill = "#D96403", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_wtd_edges <- global_netstats_cum %>% 
  ggplot( aes(time, wtd_edge_count), y=wtd_edge_count) +
  geom_bar(stat="identity", fill = "#eaaa31", width = 0.7) +
  theme_bw() + theme(axis.title.x = element_blank())

network_commits <- global_netstats_cum %>% 
  ggplot( aes(time, commits), y=commits) +
  geom_bar(stat="identity", fill = "#628ed8", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_isolates <- global_netstats_cum %>% 
  ggplot( aes(time, isolates), y=isolates) +
  geom_bar(stat="identity", fill = "#1d7c6b", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

network_dyads <- global_netstats_cum %>% 
  ggplot( aes(time, dyads), y=dyads) +
  geom_bar(stat="identity", fill = "#600080", width = 0.7) + 
  theme_bw() + theme(axis.title.x = element_blank())

grid.arrange(network_nodes, network_commits, 
             network_edges,  network_isolates,  
             network_wtd_edges, network_dyads, nrow=3, ncol=2,
             top="Cumulative Growth in Node, Edge and Commit Counts for GitHub Networks")
```

```{r global_networks_cum descriptive trends, fig.width=9.5, echo=FALSE, layout="l-body-outset"}

ggplot(global_netstats_cum, aes(time)) + 
  geom_line(aes(y = node_count, colour = "node_count", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edge_count/100", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "wtd_edge_count/1000", group= 2), size=2) +
  geom_line(aes(y = commits/100, colour = "commits/100", group= 3), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 4), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads/100", group = 5), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000", "#D96403", "#eaaa31", "#628ed8", "#1d7c6b", "#600080")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Cumulative Growth in GitHub Networks") +
  theme_minimal() + theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.15,0.8))

descriptives <- global_netstats_cum %>% select(year, node_count, edge_count, 
                               wtd_edge_count, commits, isolates, dyads)
paged_table(descriptives, options = list(rows.print = 15))
```

```{r density yxy & cum, fig.width=9.5, fig.height=8, echo=FALSE, layout="l-body-outset"}
density_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=density,group=1), size=2) + 
  labs(y = "Density (Cumulative)", x = "Year", colour = "#990000") + 
  theme_minimal() + theme(axis.title.x = element_blank())

transitivity_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=transitivity, group=1), size=2) + 
  labs(y = "Transitivity (Cumulative)", x = "Year", colour = "#D96403") + 
  theme_minimal() + theme(axis.title.x = element_blank())

all_others<-ggplot(global_netstats_cum, aes(time)) + 
  geom_line(aes(y = node_count, colour = "nodes", group= 1), size=2) + 
  geom_line(aes(y = edge_count/100, colour = "edges", group= 2), size=2) +
  geom_line(aes(y = wtd_edge_count/1000, colour = "weighted", group= 2), size=2) +
  geom_line(aes(y = commits/100, colour = "commits", group= 3), size=2) +   
  geom_line(aes(y = isolates, colour = "isolates", group = 4), size=2) +
  geom_line(aes(y = dyads/100, colour = "dyads", group = 5), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000", "#D96403", "#eaaa31", "#628ed8", "#1d7c6b", "#600080")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Cumulative Growth in GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + 
  theme(legend.position = c(0.15,0.69))

louvain_cum<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain, group=1), size=2) + 
  labs(y = "Modularity (Cumulative)", x = "Year", colour = "#628ed8") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_cum_scaled<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain_scaled, group=1), size=2) + 
  labs(y = "Modularity (Scaled)", x = "Year", colour = "#1d7c6b") +
  theme_minimal() + theme(axis.title.x = element_blank())
louvain_cum_logged<-ggplot(global_netstats_cum) + 
  geom_line(aes(x=time, y=louvain_logged, group=1), size=2) + 
  labs(y = "Modularity (Logged)", x = "Year", colour = "#600080") + 
  theme_minimal() + theme(axis.title.x = element_blank())

grid.arrange(density_cum, louvain_cum, 
             transitivity_cum, louvain_cum_scaled,  
             all_others, louvain_cum_logged, nrow=3, ncol=2,
             top="Network Measures")

network_descriptives <- global_netstats_cum %>% select(year, density, transitivity,
                                               louvain, louvain_logged, louvain_scaled)
paged_table(network_descriptives, options = list(rows.print = 15))
```

```{r percentage-change, echo=FALSE, fig.width=9.5}

global_netstats_cum <- global_netstats_cum %>% 
  mutate(nodes_pctcng = (node_count/lag(node_count) - 1) * 100) %>% 
  mutate(edges_pctcng = (edge_count/lag(edge_count) - 1) * 100) %>% 
  mutate(wtd_edges_pctcng = (wtd_edge_count/lag(wtd_edge_count) - 1) * 100) %>% 
  mutate(commits_pctcng = (commits/lag(commits) - 1) * 100) %>% 
  mutate(isolates_pctcng = (isolates/lag(isolates) - 1) * 100) %>% 
  mutate(dyads_pctcng = (dyads/lag(dyads) - 1) * 100) %>% 
  select(time, year, node_count, nodes_pctcng, edge_count, edges_pctcng, 
         wtd_edge_count, wtd_edges_pctcng, commits, commits_pctcng, 
         isolates, isolates_pctcng, dyads, dyads_pctcng)
#global_netstats_cum
global_netstats_cum %>% filter(time != 2008) %>% ggplot(aes(time)) + 
  geom_line(aes(y = nodes_pctcng, colour = "nodes_pctcng", group= 1), size=2) + 
  geom_line(aes(y = edges_pctcng, colour = "edges_pctcng", group= 2), size=2) +
  geom_line(aes(y = wtd_edges_pctcng, colour = "wtd_edges_pctcng", group= 2), size=2) +
  geom_line(aes(y = commits_pctcng, colour = "commits_pctcng", group= 3), size=2) +   
  geom_line(aes(y = isolates_pctcng, colour = "isolates_pctcng", group = 4), size=2) +
  geom_line(aes(y = dyads_pctcng, colour = "dyads_pctcng", group = 5), size=0.5) + 
  scale_colour_manual(values = 
  c( "#990000", "#D96403", "#eaaa31", "#628ed8", "#1d7c6b", "#600080")) + 
  labs(y = "Node Count", x = "Year", colour = "",
       title = "Percent Change in Descriptive Measures for GitHub Networks") + 
  theme_minimal() + theme(axis.title.x = element_blank()) + theme(legend.position = c(0.85,0.8))

percentage_change <- global_netstats_cum %>% 
  filter(year != 2008) %>% 
  select(year, nodes_pctcng, edges_pctcng, 
         wtd_edges_pctcng, commits_pctcng, 
         isolates_pctcng, dyads_pctcng)
paged_table(percentage_change, options = list(rows.print = 15))
```

```{r global_networks_yxy power law fitting, eval=FALSE, echo=FALSE }

data <- full_nodelist_yxy %>% select(deg08) %>% drop_na(deg08)
data.dist <- data.frame(k=0:max(data),p_k=degree_distribution(login_network))
data.dist <- data.dist[data.dist$p_k>0,]
ggplot(data.dist) + geom_point(aes(x=k, y=p_k)) + theme_bw()

m_pl <- displ$new(data)
est_pl <- estimate_xmin(m_pl)
est_pl$xmin # initial estimation of kmin 
est_pl$pars # initial estimation of γ
est_pl$gof # calculate D with Kolgomorov-Smirnov test

# finish remainder of process using https://rpubs.com/lgadar/power-law

power_law_end <- data.frame(event="power_law_end", time=now("EST"))
time_log <- rbind(time_log, power_law_end); rm(power_law_end)


```




















