---
title: "Company Counts on GitHub"
author: "Brandon L. Kramer"
date: "11/26/2019"
output: html_document
---

```{r loading data}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(),
                 dbname = "sdad_data",
                 host = "postgis_2",
                 port = 5432L,
                 user = Sys.getenv("db_userid"),
                 password = Sys.getenv("db_pwd"))

# query the users_gh data from github data 
users_gh <- dbGetQuery(conn, "SELECT login, company, created_at 
                              FROM github.users_gh")

# disconnect from postgresql database 
dbDisconnect(conn)
```

```{r company counts}
hyphen <- "[-]"
parentheses <- "[()]"
ellipses <- "[...]"

organization_counts <- users_gh %>% 
  # remove all na's 
  drop_na(company) %>% 
  # convert to lower case 
  mutate(organization = str_to_lower(company)) %>% 
  # remove @ from start of names 
  mutate(organization = str_replace_all(organization, "@", " ")) %>% 
  mutate(organization = str_replace_all(organization, "\\b(inc.|inc)\\b", "")) %>%
  mutate(organization = str_trim(organization)) %>% 
  # variations on major corporations 
  # these regex patterns were developed by (1) looking through the list and consolidating duplicate names and (2) using grepl to find lines with matching strings 
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^microsoft|microsoftedge|microsoftdocs|microsoftresearch|microsoftazure|microsoftdocs magfest|microsoftdotcom|microsoftgraph|microsoftleap|microsoftresearchasia|microsoftstudentpartners|microsoftwareltd|nextmicrosoft)\\b"), 
                              yes = "microsoft", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^google|googlecloudplatform|googlechrome|googlecreativelab|googleapis|googlebd|googlecreativelab|googledevelopers|googlefonts|googlei18n|googlepixel2rom|livegoogle|mlgoogle)\\b"), 
                              yes = "google", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(ibm|ibm research|ibmresearch|ibmstreams|ibmruntimes|ibmets)\\b"), 
                              yes = "ibm", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(red hat|red hat, inc.|redhat|red hat, inc|red hat inc.|red hat inc|redhatofficial)\\b"), 
                              yes = "red hat", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(amazon|amazon web services|aws|amazon.com|amzn|amazonwebservice|awslabs|awsdocs|awssat|awscloud|awsteams|mobileaws)\\b"), 
                              yes = "amazon/aws", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^facebook|^facebook,|facebookresearch|facebook$|facebbok)\\b"), 
                              yes = "facebook", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^instagram|instagram$)\\b"), 
                              yes = "instagram", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(thoughtworks|thoughtworksinc|thoughtworksstudios)\\b"), 
                              yes = "thoughtworks", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(alibaba|alibaba group|alibabab|alibabab.|alibabacloud|alibabadp|alibabagroup|alibabapai)\\b"), 
                              yes = "alibaba", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(sap|sap se)\\b"), 
                              yes = "sap", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(tencent|^tencent|tencentafrica|tencentopen|tencentxtest)\\b"), 
                              yes = "tencent", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(mozilla|mozilla corporation|mozillafoundation|mozillabrasil raincorn|mozillahispano|mozillaitalia|mozillaonline|mozillareality|mozillascience|mozillaslovenija|mozillatn)\\b"), 
                              yes = "mozilla", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
pattern = "\\b(?i)(cisco|^cisco systems|ciscosystems|ciscodevnet|ciscoemerge|ciscocloud|ciscospark|ciscosystems datacenter|ciscosytems)\\b"), 
                              yes = "cisco systems", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(apple|apple inc.|apple inc)\\b"), 
                              yes = "apple", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(adobe|adobe systems)\\b"), 
                              yes = "adobe", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^oracle |^oracle,)\\b"), 
                              yes = "oracle", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^esri |^esri,|esri-es|esri-devcenter-beijing|esricanada|esriuk)\\b"), 
                              yes = "esri", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(salesforce|salesforce.com|salesforcefoundation|salesforceiq|salesforcesaturdaytokyo)\\b"), 
                              yes = "salesforce", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^shopify)\\b"), 
                              yes = "shopify", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(samsung|samsung electronics|samsungartik|samsungaccelerator|samsung360vr|samsunginternet|samsungsds)\\b"), 
                              yes = "samsung", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(yahoo|yahoo!|yahoojapan)\\b"), 
                              yes = "yahoo", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(uber|uber technologies|uberresearch|uber technologies,)\\b"), 
                              yes = "uber", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^twitter|^twitter,|^twitter:|twitter$)\\b"), 
                              yes = "twitter", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^pivotal|^pivotal-cf|pivotal$|pivotal-cf$|pivotal labs$|pivotal-energy-solutions|pivotal-japan|^pivotalservices|pivotalsoftware|pivotaltracker)\\b"), 
                              yes = "pivotal", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(intel|intel coroporation)\\b"), 
                              yes = "intel", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^linkedin|linkedin$|contato-linkedin|^linkedin,)\\b"), 
                              yes = "linkedin", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(wix|wix.com)\\b"), 
                              yes = "wix", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^hewlett packard|hewlett packard$|^hewlett-packard|^hewlettpackard|hewlettpackard$|hewlett-packard$)\\b"), 
                              yes = "hewlett packard", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^yandex|^yandex,|yandex$|yandex-money|yandexclassifieds|yandex-money-tech)\\b"), 
                              yes = "yandex", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^vmware|^vmware,|vmware$|vmware/lightwave)\\b"), 
                              yes = "vmware", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^accenture|accenture$|^accenture,)\\b"), 
                              yes = "accenture", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(cyberagent|cyberagent, .)\\b"), 
                              yes = "cyberagent", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(baidu .|baidu|baidu, .)\\b"), 
                              yes = "baidu", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^bloomberg|bloomberg l.p.)\\b"), 
                              yes = "bloomberg", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(slack|slackhq)\\b"), 
                              yes = "slack", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)($airbnb|airbnb$|$air bnb|air bnb$)\\b"), 
                              yes = "airbnb", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)($netlfix|$netlfix,|netflix$)\\b"), 
                              yes = "netflix", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^andela|^andela,|andela$)\\b"), 
                              yes = "andela", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^epam|^epam,|epam$)\\b"), 
                              yes = "epam systems", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^spotify|spotify$)\\b"), 
                              yes = "spotify", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^zendesk|zendesk$)\\b"), 
                              yes = "zendesk", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^netease|^netease,|netease$)\\b"), 
                              yes = "netease", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^suse| suse$)\\b"), 
                              yes = "suse", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^naver|naver$|naverlabs|naverbusinessplatform|uwnlp naver)\\b"), 
                              yes = "naver", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^preferred networks|^preferred networks,|preferred networks$)\\b"), 
                              yes = "preferred networks", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^red ventures|^redventures|red ventures$)\\b"), 
                              yes = "red ventures", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^credit karma|creditkarma)\\b"), 
                              yes = "credit karma", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^yelp|yelp!|yelp$|^yelp,)\\b"), 
                              yes = "yelp", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^atlassian|atlassian$)\\b"), 
                              yes = "atlassian", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^nvidia|nvidia$)\\b"), 
                              yes = "nvidia", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^zalando|zalando$)\\b"), 
                              yes = "zalando", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^automattic|automattic$)\\b"), 
                              yes = "automattic", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^huawei|^huawei,|huawei$)\\b"), 
                              yes = "huawei", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^rackspace|rackspace$)\\b"), 
                              yes = "rackspace", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^capgemini|capgemini$)\\b"), 
                              yes = "capgemini", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^jetbrains|jetbrains$)\\b"), 
                              yes = "jetbrains", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^cern|^cern,|cern$)\\b"), 
                              yes = "cern", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^bbc|^bbc,|bbc$|british broadcasting corporation)\\b"), 
                              yes = "bbc", no = organization)) %>%
  # universities and research institutes 
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(duke university|duke|duke university libraries|dukeuniversity)\\b"), 
                              yes = "duke university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(stanford university|stanford|stanfordmlgroup|stanfordvl|stanfordgeospatialcenter|stanfordhci|stanfordjournalism|stanfordmsl|stanfordnlp)\\b"), 
                              yes = "stanford university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(massachusetts institute of technology|mit|mitmedialab|mit media lab)\\b"), 
                              yes = "massachusetts institute of technology", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(harvard medical school|harvard|harvard university|harvardagileroboticslab|harvardnlp|harvardx)\\b"), 
                              yes = "harvard university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^princeton university|princeton university$|princetonuniversity|princeton)\\b"), 
                              yes = "princeton university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^columbia university|columbia university$|barnard college|columbia-university)\\b"), 
                              yes = "columbia university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^northeastern university|northeastern university$|northeastern)\\b"), 
                              yes = "northeastern university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^northwestern university|northwestern university$|northwestern)\\b"), 
                              yes = "northwestern university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^cornell university|cornell university$|northwestern|^cornell tech|cornell tech$|cornelltech|^weill cornell|weill cornell$|weill cornell medicine$|cornell|cornell lab of ornithology|cornell-dti|cornell-rpal|cornell asl|weillcornell nygenome|cornell cs|cornell unveristy|cs, cornell)\\b"), 
                              yes = "cornell university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(carnegie mellon|carnegie mellon university|carnegie mellon university software engineering institute|carnegie mellon university, silicon valley)\\b"), 
                              yes = "carnegie mellon university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(john hopkins|john hopkins university|johns hopkins university applied physics laboratory)\\b"), 
                              yes = "john hopkins university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(penn|upenn|pennlabs|university of pennsylvania|the university of pennsylvania|penn medicine)\\b"), 
                              yes = "university of pennsylvania", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(university of washington|university of washington(?! state)|univerisity of washington|univeristy of washington|universityofwashington|univesity of washington)\\b"),
                              yes = "university of washington system", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(university of california, san diego|university of california san diego|ucsd|university of california berkeley|uc berkeley|ucla|university of california, berkeley|university of california davis|university of california, davis|university of california irvine|university of california, irvine|california digital library, ucop|california digital library|university of california, san francisco|uc san francisco|university of california san francisco)\\b"), 
                              yes = "university of california system", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^california state|california state$|california state university$|^california polytechnic|california polytechnic$)\\b"), 
                              yes = "california state university system", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^georgia institute of technology|^georgia tech|georgia institute of technology$|georgia tech$)\\b"), 
                              yes = "georgia institute of technology", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(university of british columbia|ubc)\\b"), 
                              yes = "university of british columbia", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(indiana university|indiana university bloomington|indiana university, bloomington)\\b"), 
                              yes = "indiana university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(university of texas at austin|university of texas|the university of texas at austin)\\b"), 
                              yes = "university of texas", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^texas a&m|^texas a & m|texas a&m university)\\b"), 
                              yes = "texas a&m university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(university of college london|ucl|university college london)\\b"), 
                              yes = "university of college london", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(new york university|nyu|nyulibraries|nyueserv|itpnyu)\\b"), 
                              yes = "new york university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(penn state|penn state university|pennsylvania state university|the pennsylvania state university|pennstate)\\b"), 
                              yes = "pennsylvania state university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(fred hutchinson cancer research center|fredhutch|fred hutch|fred hutchinson|fred hutchinson center|fred hutch cancer research center)\\b"), 
                              yes = "fred hutchinson cancer research center", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(shanghai jiao tong university|sjtu|jiao tong university|jiao tong)\\b"), 
                              yes = "shanghai jiao tong university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^tsinghua|tsinghua$|tsinghua university$|tsinghua univ$|tsinghua unviersity|tsinghuauniversity|tsinghua_university|tsinghuau)\\b"), 
                              yes = "tsinghua university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of michigan|university of michigan$|^the university of michigan|university of michigan, ann arbor)\\b"), 
                              yes = "university of michigan", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of virginia|university of virginia$|^uva|uva$)\\b"), 
                              yes = "university of virginia", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^virginia tech|virginia tech$|virginia tech university$|^Virginia Polytechnic)\\b"), 
                              yes = "virginia polytechnic institute and state university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of tokyo|^the university of tokyo|university of tokyo$)\\b"), 
                              yes = "university of tokyo", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of waterloo|^the university of waterloo|university of waterloo$)\\b"), 
                              yes = "university of waterloo", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^zhejiang|zhejiang university$)\\b"), 
                              yes = "zhejiang university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of toronto|university of toronto$)\\b"), 
                              yes = "university of toronto", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^imperial college london|imperial college london$)\\b"), 
                              yes = "imperial college london", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of cambridge|university of cambridge$|^cambridge university|cambridge university$)\\b"), 
                              yes = "university of cambridge", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of oxford|university of oxford$|^oxford university|oxford university$|^the university of oxford|^university of oxford,)\\b"), 
                              yes = "university of oxford", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^peking university|peking university$|^peking university,)\\b"), 
                              yes = "peking university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of southern california|university of southern california$|^university of southern california,)\\b"), 
                              yes = "university of southern california", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^nanjing university|^nanjing univ|nanjing university$|^nanjing university,)\\b"), 
                              yes = "nanjing university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of edinburgh|university of edinburgh$|^the university of edinburgh)\\b"), 
                              yes = "university of edinburgh", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^purdue university|^purdue university,|purdue university$|department of statistics,purdue university|purdue univeristy)\\b"), 
                              yes = "purdue university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of florida|^university of florida,|university of florida$|universityofflorida)\\b"), 
                              yes = "university of florida", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of chicago|^university of chicago,|^the university of chicago|university of chicago$|^uchicago|uchicago$|^u of chicago|u of chicago$)\\b"), 
                              yes = "university of chicago", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of illinois|^university of illinois,|^the university of illinois|university of illinois$|university of illinois at chicago|at urbana-champaign$)\\b"), 
                              yes = "university of illinois system", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^national university of singapore|^national university of singapore,|national university of singapore$)\\b"), 
                              yes = "national university of singapore", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^fudan|fudan university$|fudan university)\\b"), 
                              yes = "fudan university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^boston university|boston university$)\\b"), 
                              yes = "boston university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^arizona state|^arizona state,|arizona state university$|arizona state$)\\b"), 
                              yes = "arizona state university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^mcgill|mcgill university$|mcgill$)\\b"), 
                              yes = "mcgill university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^oregon state|^oregon state,|oregon state university$|oregon state$)\\b"), 
                              yes = "oregon state university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^stony brook|stony brook university$|stony brook$|^state university of new york)\\b"), 
                              yes = "state university of new york system", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of minnesota|university of minnesota$|^university of minnesota,)\\b"), 
                              yes = "university of minnesota", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^sun yat-sen university|sun yat-sen university$|^sun yat-sen university,)\\b"), 
                              yes = "sun yat-sen university", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(^university of alberta|university of alberta$|^university of alberta,)\\b"), 
                              yes = "university of alberta", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
  pattern = "\\b(?i)(^university of wisconsin-madison|^university of wisconsin|university of wisconsin$|university of wisconsin-madison$|university of wisconsinmadison|^university of wisconsin,|^uw-madison|uw-madison$)\\b"), yes = "university of wisconsin-madison", no = organization)) %>%
  # freelancer, individual, null, etc.
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(freelancer|freelance)\\b"), 
                              yes = "freelancer", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(self|personal|home|private|individual|myself|me|independent|independent contractor)\\b"), 
                              yes = "individual", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(school|university student|a university student|student)\\b"), 
                              yes = "student", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = "\\b(?i)(n/a|none|null|no|na)\\b"),      
                              yes = "none/null", no = organization)) %>% 
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = parentheses),      
                              yes = "none/null", no = organization)) %>%
  mutate(organization = ifelse(test = str_detect(string = organization, 
                              pattern = ellipses),      
                              yes = "none/null", no = organization)) %>%
  #filter(organization != "none/null") %>% filter(organization != "") %>% filter(organization != "-") %>%
  #filter(organization != "china") %>% filter(organization != "japan") %>%
  group_by(organization) %>% count() %>% arrange(-n) 

organization_counts 

```

```{r editing refusal data}

# getting the totals before refusals 
sum(organization_counts$n)
sum(organization_counts$n) / 2143407

# getting the totals of refusals (none/null) 
organization_counts %>% 
  filter(organization == "none/null"|organization == ""|organization == "-") 
39803+3851+311 # total of all three 

# removing country codes in org code column 
organization_counts %>%
  filter(organization == "china"|organization == "japan")
334+183

```

```{r creating final totals }
# removing refusals and countries from dataset 
organization_counts <- organization_counts %>% 
  filter(organization != "none/null") %>% filter(organization != "") %>% filter(organization != "-") %>% 
  filter(organization != "china") %>% filter(organization != "japan")
  
# i used this snippet of code to search through all of the top-50 academic and top-50 non-academic organizations to catch variations 
# filter(organization_counts, grepl('google', organization))

# this gets the total number and percentage of logins with organization codes 
sum(organization_counts$n)
sum(organization_counts$n) / 2143407

# output to a csv file 
write.csv(organization_counts, "organization_counts.csv")
#saveRDS(company_counts, "company_counts.rds")
```

```{r}

# non-academic institutions 
non_academic_counts <- organization_counts %>% 
  filter(!grepl('(university|college|institute)', organization))
sum(non_academic_counts$n)

write.csv(non_academic_counts, "non_academic_counts.csv")

# academic institutions 
academic_counts <- organization_counts %>% 
  filter(grepl('(university|college|institute)', organization))
sum(academic_counts$n)

write.csv(academic_counts, "academic_counts.csv")

```












