---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
library("janitor")

intl_collabs_df <- function(analysis_year){
  
  #analysis_year <- "2008"
  
  # load data 
  raw_collab_matrix <- read.csv(str_c("~/git/oss-2020/data/intl-indicator-output/oss_intl_collaborations_matrix_", analysis_year,".csv"), sep=";")

  # calculate total collaborations 
  total_collaboration_counts <- raw_collab_matrix %>%
    clean_names() %>% 
    replace(is.na(.), 0) %>%
    select_if(is.numeric) %>%
    summarise_all(funs(sum(.))) %>% 
    t %>% as.data.frame %>% 
    rownames_to_column() %>% 
    rename(country = rowname, num_collabs = V1)

  # impute zeroes into the matrix now 
  # this recodes all of the domestic collaborations to 0
  country_names <- raw_collab_matrix %>% select(Country)
  imputed_collab_matrix <- raw_collab_matrix %>% select(-Country)
  diag(imputed_collab_matrix) <- 0
  imputed_collab_matrix <- cbind(country_names, imputed_collab_matrix)
  #imputed_collab_matrix

  # calculate non-self collaborations 
  foreign_collaboration_counts <- imputed_collab_matrix %>%
    clean_names() %>% 
    replace(is.na(.), 0) %>%
    select_if(is.numeric) %>%
    summarise_all(funs(sum(.))) %>% 
    t %>% as.data.frame %>% 
    rownames_to_column() %>% 
    rename(country = rowname, num_foreign = V1)

  wo_us_matrix <- raw_collab_matrix %>%
    clean_names() %>% 
    replace(is.na(.), 0) %>% 
    filter(country == "United States") %>% 
    select_if(is.numeric) %>%
    summarise_all(funs(sum(.))) %>% 
    t %>% as.data.frame %>% 
    rownames_to_column() %>% 
    rename(country = rowname, num_us = V1)
  #wo_us_matrix

  # we want the nice names names in the country col, not the var.names()
  country_names <- raw_collab_matrix %>% select(Country) %>% 
    mutate(Country = as.character(Country))

  # combine all and foreign collaborations to calculate domestic calcs
  collab_df <- total_collaboration_counts %>% 
    left_join(foreign_collaboration_counts, by = "country") %>% 
    left_join(wo_us_matrix, by = "country") %>% 
    mutate(num_domestic = num_collabs - num_foreign,
          prc_foreign = round(num_foreign / num_collabs * 100, 2),
          prc_domestic = 100.00 - prc_foreign,
          num_non_us = num_foreign - num_us,
          prc_us = round(num_us / num_collabs * 100, 2),
          prc_non_us = round(num_non_us / num_collabs * 100, 2)) %>% 
    select(country, starts_with("prc_"), everything()) 

  collab_df <- cbind(country_names, collab_df) %>% select(-country) %>% 
    rename(country = Country) %>% 
    mutate(year = analysis_year,
           year = as.numeric(year)) %>% 
    select(country, year, everything())

  return(collab_df) #%>% arrange(-num_foreign)

}

collabs_2008 <- intl_collabs_df("2008")
collabs_2009 <- intl_collabs_df("2009")
collabs_2010 <- intl_collabs_df("2010")
collabs_2011 <- intl_collabs_df("2011")
collabs_2012 <- intl_collabs_df("2012")
collabs_2013 <- intl_collabs_df("2013")
collabs_2014 <- intl_collabs_df("2014")
collabs_2015 <- intl_collabs_df("2015")
collabs_2016 <- intl_collabs_df("2016")
collabs_2017 <- intl_collabs_df("2017")
collabs_2018 <- intl_collabs_df("2018")
collabs_2019 <- intl_collabs_df("2019")

collabs_0819 <- rbind(collabs_2008, collabs_2009, collabs_2010, collabs_2011, collabs_2012, collabs_2013, 
                      collabs_2014, collabs_2015, collabs_2016, collabs_2017, collabs_2018, collabs_2019)

setwd("~/git/oss-2020/data/intl-indicator-output/")
write_csv(collabs_0819, "oss_intl_collaborations_df_200819.csv")
```

```{r, fig.width=7, fig.height=5}
collabs_0819 <- read_csv("~/git/oss-2020/data/intl-indicator-output/oss_intl_collaborations_df_200819.csv")

top_10_by_collabs <- collabs_0819 %>%
  filter(year == "2019") %>% 
  arrange(-num_collabs) %>% 
  top_n(10, num_collabs)
top_10_by_collabs <- as.character(top_10_by_collabs$country)

collabs_0819 %>% 
  filter(country %in% top_10_by_collabs) %>% 
  ggplot() + 
  geom_line(aes(y = prc_domestic, x = year, colour = country), size = 1, stat="identity") + 
  theme_minimal() + 
  labs(title = " Change in Percentage of Domestic Collaborations \n for Top-10 Countries Over Time (GitHub, 2008-2019)", 
       color =  "Country") + 
  ylab("Percentage of All Collaborations") +
  theme(axis.title.x = element_blank(), 
        legend.position = "bottom",
        legend.title = element_text(size = 10, hjust = 0.5, face="bold"),
        plot.title = element_text(size=13, hjust = 0.5)) +
  scale_color_manual(labels=c("Canada", "China",   "France",  "Germany", "India",   "Japan", "Netherlands","Russia","United Kingdom", "United States"),
                     values=c("#990000","#0AA18C", "#5BC21C", "#628ed8", "#232D4B", "#E6CE3A",  "#D9E12B", "#0E879C", "#89cff0",     "#ff7f00")) +
  scale_x_continuous(limits = c(2008, 2019),
                     breaks = c(2008, 2010, 2013, 2016, 2019))

```

