---
title: "Untitled"
output: html_document
---

Click on "SQL Command" in the database and copy this whole snippet. Takes 10 minutes.

```{sql }
CREATE MATERIALIZED VIEW AS gh.cost_
by_ctr AS (
SELECT slug, login, country_code, COUNT(*) AS commits, SUM(additions) AS additions, SUM(deletions) AS deletions
FROM (SELECT slug, 
	  commits.login, 
	  EXTRACT(YEAR FROM committed_date)::int AS YEAR, 
	  users_gh_cc.country_code AS country_code, 
	  additions, deletions
	  FROM gh.commits 
	  FULL JOIN github.users_gh_cc 
	  ON commits.login = users_gh_cc.login) A
GROUP BY slug, login, A.country_code
);
```

Click on "SQL Command" in the database and copy this whole snippet. Takes 10 minutes.

```{sql }
CREATE MATERIALIZED VIEW AS gh.repos_by_ctry AS (
SELECT slug, country_code, COUNT(*) AS commits, SUM(additions) AS additions, SUM(deletions) AS deletions
FROM (SELECT slug, 
	  commits.login, 
	  EXTRACT(YEAR FROM committed_date)::int AS YEAR, 
	  users_gh_cc.country_code AS country_code, 
	  additions, deletions
	  FROM gh.commits 
	  FULL JOIN github.users_gh_cc 
	  ON commits.login = users_gh_cc.login) A
GROUP BY slug, A.country_code
); 
```

```{r setup, include=FALSE}
#rm(list = ls())
# load packages 
for (pkg in c("tidyverse", "data.table", 
              "R.utils", "RPostgreSQL")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get data (in rivanna)
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

repos_by_ctry <- dbGetQuery(conn, "SELECT slug, country_code, commits, additions, deletions
                                   FROM gh.repos_by_ctry")

# disconnect from postgresql
dbDisconnect(conn)
```

```{r}
# recodes all of the countries with multiple names into one "multiple" category 
repos_by_ctry <- repos_by_ctry %>% 
  dplyr::mutate(old_cc = country_code) %>% 
  dplyr::mutate(country_code = ifelse(
    test = str_detect(string = country_code, 
                      pattern = "_"), paste("multiple"), no = country_code)) 

repos_by_ctry %>% 
  filter(country_code == "multiple")

repos_by_ctry$country_code <- trimws(repos_by_ctry$country_code)
```

```{r}
# total repos by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  count() %>% rename(repos = n) %>% 
  arrange(-repos)

# total commits by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  summarise(commits = sum(commits)) %>% 
  right_join(stats_by_country, by = "country_code") %>%    # might need to clean the strings 
  select(country_code, repos, commits) %>% 
  arrange(-commits)
  
# total additions by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  summarise(additions = sum(additions)) %>% 
  right_join(stats_by_country, by = "country_code") %>% 
  arrange(-additions) %>% 
  select(country_code, repos, commits, additions)

# total deletions by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  summarise(deletions = sum(deletions)) %>% 
  right_join(stats_by_country, by = "country_code") %>% 
  arrange(-deletions) %>% 
  select(country_code, repos, commits, additions, deletions)

# total additions + deletions by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  summarise(adds_plus_dels = sum(additions + deletions)) %>% 
  right_join(stats_by_country, by = "country_code") %>% 
  arrange(-adds_plus_dels) %>% 
  select(country_code, repos, commits, additions, 
         deletions, adds_plus_dels)

# total additions - deletions by country 
stats_by_country <- repos_by_ctry %>% 
  group_by(country_code) %>% 
  summarise(adds_sub_dels = sum(additions - deletions)) %>% 
  right_join(stats_by_country, by = "country_code") %>% 
  arrange(-adds_sub_dels) %>%
  select(country_code, repos, commits, additions, 
         deletions, adds_plus_dels, adds_sub_dels)

stats_by_country <- stats_by_country %>% 
  #drop_na(country_code) %>% 
  arrange(-repos)

# total additions 
stats_by_country <- stats_by_country %>% 
  mutate(adds_per_repo = additions / 5188818)
  #mutate(adds_per_521M = freq_adds / 5216947) 

stats_by_country <- stats_by_country %>% 
  mutate(add_plus_dels_per_repo= add_plus_dels / 5188818) 
  #mutate(add_plus_dels_per_521M = add_plus_dels / 5216947) 

stats_by_country <- stats_by_country %>% 
  mutate(add_sub_dels_per_repo = add_sub_dels / 5188818) 
  #mutate(add_sub_dels_per_521M = add_sub_dels / 5216947) 

write.csv(data, "oss-repos-per-country.csv")
```

















