---
title: "New Repos Created Over Time (GitHub, 2008-2018)"
output: html_document
---

```{r, include=FALSE}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "data.table", "R.utils", "RPostgreSQL", "treemap",
              "cowplot", "maditr", "lubridate")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get data (in rivanna)
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# grab the repos data 
repos <- dbGetQuery(conn, "SELECT slug, spdx, created
                           FROM gh.repos")

# disconnect from postgresql
dbDisconnect(conn)
```

The first step is to graph the number of new repos created on GitHub each year. 

```{r, fig.width=8.5}
# extract the year from the created column 
repos <- repos %>% 
  mutate(year = format(as.Date(created, format="%Y/%m/%d"),"%Y")) 

# filter out those before 2007 and after 2018
repo_totals <- repos %>% 
  filter(year > 2007 & year < 2019) %>%
  group_by(year) %>% 
  count(); repo_totals

repo_totals

# graph those totals by year 
ggplot(data=repo_totals, aes(x=year, y=n)) +
  geom_bar(stat="identity", fill = "#232D4B")+
  theme(plot.title = (element_text("Number of New Repositories Created on GitHub (2008-2018)", 
                                   colour="#232D4B", hjust = 2, size = 18)),
        panel.background = element_rect(fill = "white", colour = "white",
                                        size = 2, linetype = "solid"),
        panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                        colour = "white"),
        panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                        colour = "white"),
        axis.title.x = element_blank(),
        axis.text=element_text(colour="#232D4B", size = 18),
        axis.title = element_text(colour="#232D4B", size = 20)) + 
  scale_x_discrete(breaks = c(2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018), 
                     labels = c(2008,"","","","",2013,"","","","",2018)) +
  labs(title="Number of New Repositories Created on GitHub (2008-2018)", x="Year", y = "Repositories (in Millions)") +
  scale_y_continuous(limits = c(0, 1750000), breaks = seq(0, 1750000, by = 250000),
                     labels = c("0","0.25","0.5","0.75","1.0","1.25","1.5","1.75")) 

#setwd("~/")
#ggsave("bar_version1.png", width = 9.5)
```






























