---
title: "International Country Networks: Supernode Analyses"
author: "Brandon L. Kramer"
output: html_document
---

## Loading Data 

We used this code to pull data for the construction of Github network data (cumulatively.

```{r loading edgelist data, warning=FALSE, echo=FALSE}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", 
# "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "linkprediction", "poweRlaw"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL",
              "cowplot", "maditr", "lubridate", "linkprediction", "poweRlaw", 
              "countrycode")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get data (in rivanna)
conn <- dbConnect(drv = PostgreSQL(), dbname = "sdad_data", 
                  host = "sdad.policy-analytics.net", port = 5436, 
                  user = Sys.getenv("db_userid"), password = Sys.getenv("db_pwd"))

# query the bipartite edgelist data from github data  
bp_edgelist <- dbGetQuery(conn, "SELECT login, slug, year, weight 
                                 FROM github.intl_dyn_bp_edges
                                WHERE year > 2007 AND year < 2019")
                                 #WHERE year = 2008")
                                 #WHERE year > 2007 AND year < 2019")
                                
# disconnect from postgresql
dbDisconnect(conn)

conn <- dbConnect(drv = PostgreSQL(), dbname = "sdad_data", 
                  host = "sdad.policy-analytics.net", port = 5436, 
                  user = Sys.getenv("db_userid"), password = Sys.getenv("db_pwd"))

# query the bipartite edgelist data from github data  
country_codes <- dbGetQuery(conn, "SELECT login, country_code
                                   FROM github.users_gh_cc")

dbDisconnect(conn)

country_codes <- country_codes %>% 
  filter(!grepl(",", country_code)) %>% 
  filter(!grepl("europe", country_code)) %>% 
  filter(!grepl("americas", country_code)) %>% 
  filter(!grepl("asia", country_code)) %>% 
  filter(!grepl("africa", country_code)) %>% 
  mutate(country_code = trimws(country_code))

country_codes %>% 
  group_by(country_code) %>% 
  count() %>% 
  arrange(-n)

# changing country codes to country name 
country_codes$country <- countrycode(country_codes$country, origin = 'iso2c', destination = 'country.name')

# changing Kosovo to have a valid country name 
country_codes <- country_codes %>% 
  mutate(country = ifelse(test = str_detect(string = country_code, pattern = "xk"), yes = "Kosovo", no = country)) 

country_codes %>% 
  #rename(country = country_code) %>% 
  group_by(country) %>% 
  count() %>% 
  rename(repos = n) %>% 
  arrange(-repos)

bp_edgelist <- inner_join(bp_edgelist, country_codes, by = "login") %>% 
  select(-login) %>% rename(login = country) %>% 
  select(login, slug, year, weight)


bp_edgelist <- bp_edgelist %>% select(-weight)

# disconnect from postgresql
dbDisconnect(conn)

write_csv(country_codes, "country_codes.csv")

```

```{r, fig.width=11.5, fig.height=5, echo=FALSE}

ctrs_per_country <- country_codes %>% 
  #rename(country = country_code) %>% 
  group_by(country) %>% 
  count() %>% 
  rename(repos = n) %>% 
  arrange(-repos)


ctrs_per_country$country <- recode(ctrs_per_country$country, `United States` = "USA", `United Kingdom` = "UK")

positions <- c("USA", "China", "UK","Germany","India","Canada","France", "Brazil","Russia","Japan" )

ctrs_per_country %>% 
  filter(repos > 15000) %>%  
  ggplot( aes(x = country, y = repos)) +
  geom_bar(stat="identity", fill = "#000058", width = 0.6) + 
  theme_minimal() + 
  scale_x_discrete (limits = positions) + 
  theme(axis.title.x = element_blank(),
                          axis.text=element_text(size=16),
                          axis.title=element_text(size=20)) +
  labs(y = "Contributors (in Thousands)") +
  scale_y_continuous(breaks = c(0, 50000, 100000, 150000, 200000), 
                                labels = c(0,  50, 100, 150,  200))


```


```{r network stats}
# in this snippet, we will be logging start/end times 
mat_start <- data.frame(event="mat_start", time=now("EST"))

# this code is taken from network scientists to reduce bipartite networks to single mode networks 
bp_matrix <- spMatrix(nrow=length(unique(bp_edgelist$login)),
              ncol=length(unique(bp_edgelist$slug)),
              i = as.numeric(factor(bp_edgelist$login)),
              j = as.numeric(factor(bp_edgelist$slug)),
              x = rep(1, length(as.numeric(bp_edgelist$login))))
row.names(bp_matrix) <- levels(factor(bp_edgelist$login))
colnames(bp_matrix) <- levels(factor(bp_edgelist$slug))
#rm(bp_edgelist) # trying to minimize weight on RAM 

# logging the times and saving the work in RDS files 
mat_end <- data.frame(event="mat_end", time=now("EST"))
time_log <- rbind(mat_start, mat_end); rm(mat_start, mat_end)
#saveRDS(bp_matrix, "bp_matrix.rds")
saveRDS(time_log, "time_log.rds")

# logging the times 
mm_start <- data.frame(event="mm_start", time=now("EST"))
time_log <- rbind(time_log, mm_start)

# we then multiply these incidence matrices and impute zeroes to prevent self loops 
login_matrix <- tcrossprod(bp_matrix)
#diag(login_matrix) <- 0
rm(bp_matrix)

# logging the times and saving the work in RDS files 
mm_end <- data.frame(event="mm_end", time=now("EST"))
time_log <- rbind(time_log, mm_end); rm(mm_start, mm_end)
#saveRDS(login_matrix, "login_matrix.rds")
saveRDS(time_log, "time_log.rds")

# convert it into a network and removing the loops 
net_start <- data.frame(event="net_start", time=now("EST"))
time_log <- rbind(time_log, net_start); rm(net_start)
login_network <- graph_from_adjacency_matrix(login_matrix, mode = "undirected", weighted = TRUE)
login_network <- simplify(login_network, remove.loops = TRUE)

# logging the times and saving the work in RDS files 
net_end <- data.frame(event="net_end", time=now("EST"))
time_log <- rbind(time_log, net_end); rm(net_end)
#saveRDS(login_network, "login_network.rds")
saveRDS(time_log, "time_log.rds")
```

```{r}

# getting the weighted edgelist from 
g  <- graph.adjacency(login_matrix, mode = "undirected", weighted=TRUE)
df <- get.data.frame(g)
head(df)
df <- df %>% 
  filter(weight != 0) %>% 
  rename(Source = from, Target = to, Weight = weight)
df %>% arrange(-Weight)


g2  <- graph.adjacency(login_matrix, mode = "undirected", weighted=TRUE)
g2 <- simplify(g2, remove.loops = TRUE)
df2 <- get.data.frame(g2)
head(df2)
df2 <- df2 %>% 
  filter(weight != 0) %>% 
  rename(Source = from, Target = to, Weight = weight)
df2 %>% arrange(-Weight)

bp_edgelist %>% group_by(login) %>% count() %>% mutate(share = round(n / 230 / 100)) %>% arrange(-share)


setwd("~/intl-dyn-ctry")
write_csv(df, "country_edgelist_2008-17.csv")

```

```{r global network stats}
# loading the network (if the instance crashes while doing network_stats)
#login_network <- readRDS("login_network.rds")
#time_log <- readRDS("time_log.rds")
net_stats_start <- data.frame(event="net_stats_start", time=now("EST"))
time_log <- rbind(time_log, net_stats_start); rm(net_stats_start)
network_stats <- data.frame(year="2008-18")                                          

# node and edge counts  
network_stats$node_count <- gorder(login_network)  
network_stats$edge_count <- gsize(login_network)
network_stats$commits <- sum(bp_edgelist$weight)

# isolates, dyads and triads 
network_stats$isolates <- sum(degree(login_network)==0)
network_stats$dyads <- dyad_census(login_network)[1]
oss_triads <- triad.census(login_network)
network_stats$triads_003 <- oss_triads[1] 
network_stats$triads_102 <- oss_triads[3]
network_stats$triads_201 <- oss_triads[11]
network_stats$triads_300 <- oss_triads[16]
net_counts <- data.frame(event="net_counts", time=now("EST"))
time_log <- rbind(time_log, net_counts); rm(net_counts)

# density and transitivity
network_stats$density <- edge_density(login_network, loops=FALSE) 
network_stats$transitivity <- transitivity(login_network)
net_globals <- data.frame(event="net_globals", time=now("EST"))
time_log <- rbind(time_log, net_globals); rm(net_globals)

# diameter and mean distance (very computationally intensive)
network_stats$diameter <- diameter(login_network, directed = FALSE)
network_stats$mean_distance <- mean_distance(login_network, directed = FALSE)
louvain <- cluster_louvain(login_network)
network_stats$louvain <- modularity(louvain, weights = TRUE)
 
# community detection (using louvain method)
louvain <- cluster_louvain(login_network)
network_stats$louvain <- modularity(louvain)
network_stats$louvain_scaled <- modularity(louvain) / gorder(login_network)
network_stats$louvain_logged <- modularity(louvain) / log(gorder(login_network))
# community detection (using fast & greedy method)
fstgrdy <- fastgreedy.community(login_network)
network_stats$fstgrdy <- modularity(fstgrdy)
network_stats$fstgrdy_scaled <- modularity(fstgrdy) / gorder(login_network)
network_stats$fstgrdy_logged <- modularity(fstgrdy) / log(gorder(login_network))

# decomposition statistics 
decomposition_stats <- table(sapply(decompose.graph(login_network), vcount))

net_comm_det <- data.frame(event="net_comm_det", time=now("EST"))
time_log <- rbind(time_log, net_comm_det); rm(net_comm_det)

# now, we need to construct a nodelist 
nodelist <- data.frame(id = c(1:(igraph::vcount(login_network))), login = igraph::V(login_network)$name)

# degree, weighted degree, k core and modularity 
node_stats_start <- data.frame(event="node_stats_start", time=now("EST"))
time_log <- rbind(time_log, node_stats_start); rm(node_stats_start)
nodelist$degree <- degree(login_network)
nodelist$wtd_degree <- strength(login_network)
nodelist$k_core <- coreness(login_network)
#louvain <- cluster_louvain(login_network)
nodelist$louvain_comm <- louvain$membership
#fstgrdy <- fastgreedy.community(login_network)
nodelist$fstgrdy_comm <- fstgrdy$membership
components <- components(login_network)
nodelist$component <- components$membership


nodelist <- nodelist %>% rename(country = login)

#nodelist <- nodelist %>% rename(country_code = login)
#nodelist$country_code <- toupper(nodelist$country_code)
#nodelist$country <- countrycode(nodelist$country_code, origin = 'iso2c', destination = 'country.name')
#nodelist <- nodelist %>% select(id, country_code, country, everything())
#setwd("~/intl-dyn-ctry")
#write_csv(nodelist, "country_nodelist_all_years.csv")

node_stats_end <- data.frame(event="node_stats_end", time=now("EST"))
time_log <- rbind(time_log, node_stats_end); rm(node_stats_end, louvain, components)

#setwd("~/intl-dyn-ctry")
#saveRDS(network_stats, "global_netstats_2008-17.rds")  
#saveRDS(decomposition_stats, "decomposition_stats_2008-17.rds") 
#saveRDS(nodelist, "nodelist_2008-17.rds")  
#saveRDS(time_log, "timelog_2008-17.rds")

```

```{r binding nodelists}
# read nodelists
rm(list = ls())
setwd("~/intl-dyn-ctry")
#setwd("~/oss_networks_cum/2008")
nodelist_2008 <- readRDS("nodelist_2008.rds") 
#setwd("~/oss_networks_cum/2008-09")
nodelist_200809 <- readRDS("nodelist_2008-09.rds")
#setwd("~/oss_networks_cum/2008-10")
nodelist_200810 <- readRDS("nodelist_2008-10.rds")
#setwd("~/oss_networks_cum/2008-11")
nodelist_200811 <- readRDS("nodelist_2008-11.rds") 
#setwd("~/oss_networks_cum/2008-12")
nodelist_200812 <- readRDS("nodelist_2008-12.rds") 
#setwd("~/oss_networks_cum/2008-13")
nodelist_200813 <- readRDS("nodelist_2008-13.rds")
#setwd("~/oss_networks_cum/2008-14")
nodelist_200814 <- readRDS("nodelist_2008-14.rds")
#setwd("~/oss_networks_cum/2008-15")
nodelist_200815 <- readRDS("nodelist_2008-15.rds")
#setwd("~/oss_networks_cum/2008-16")
nodelist_200816 <- readRDS("nodelist_2008-16.rds")
#setwd("~/oss_networks_cum/2008-17")
nodelist_200817 <- readRDS("nodelist_2008-17.rds")
#setwd("~/oss_networks_cum/2008-18")
nodelist_200818 <- readRDS("nodelist_2008-18.rds")

full_nodelist <- nodelist_2008 %>% 
  select(-id) %>% 
  mutate(country = as.character(country)) %>% 
  rename(deg08 = degree,
         wtddeg08 = wtd_degree, 
         kcore08 = k_core,
         louvain08 = louvain_comm,
         fstgrdy08 = fstgrdy_comm, 
         comp08 = component) %>%     
  right_join(nodelist_200809, by = "country") %>% 
  select(-id) %>% 
  rename(deg0809 = degree,
         wtddeg0809 = wtd_degree, 
         kcore0809 = k_core,
         louvain0809 = louvain_comm,
         fstgrdy0809 = fstgrdy_comm,
         comp0809 = component) %>% 
  right_join(nodelist_200810, by = "country") %>% 
  select(-id) %>% 
  rename(deg0810 = degree,
         wtddeg0810 = wtd_degree, 
         kcore0810 = k_core,
         louvain0810 = louvain_comm,
         fstgrdy0810 = fstgrdy_comm,
         comp0810 = component) %>% 
  right_join(nodelist_200811, by = "country") %>% 
  select(-id) %>% 
  rename(deg0811 = degree,
         wtddeg0811 = wtd_degree, 
         kcore0811 = k_core,
         louvain0811 = louvain_comm,
         fstgrdy0811 = fstgrdy_comm,
         comp0811 = component) %>% 
  right_join(nodelist_200812, by = "country") %>% 
  select(-id) %>% 
  rename(deg0812 = degree,
         wtddeg0812 = wtd_degree, 
         kcore0812 = k_core,
         louvain0812 = louvain_comm,
         fstgrdy0812 = fstgrdy_comm,
         comp0812 = component) %>% 
  right_join(nodelist_200813, by = "country") %>% 
  select(-id) %>% 
  rename(deg0813 = degree,
         wtddeg0813 = wtd_degree, 
         kcore0813 = k_core,
         louvain0813 = louvain_comm,
         fstgrdy0813 = fstgrdy_comm,
         comp0813 = component) %>% 
  right_join(nodelist_200814, by = "country") %>% 
  select(-id) %>% 
  rename(deg0814 = degree,
         wtddeg0814 = wtd_degree, 
         kcore0814 = k_core,
         louvain0814 = louvain_comm,
         fstgrdy0814 = fstgrdy_comm,
         comp0814 = component) %>% 
  right_join(nodelist_200815, by = "country") %>% 
  select(-id) %>% 
  rename(deg0815 = degree,
         wtddeg0815 = wtd_degree, 
         kcore0815 = k_core,
         louvain0815 = louvain_comm,
         fstgrdy0815 = fstgrdy_comm,
         comp0815 = component) %>% 
  right_join(nodelist_200816, by = "country") %>% 
  select(-id) %>% 
  rename(deg0816 = degree,
         wtddeg0816 = wtd_degree, 
         kcore0816 = k_core,
         louvain0816 = louvain_comm,
         fstgrdy0816 = fstgrdy_comm,
         comp0816 = component) %>% 
  right_join(nodelist_200817, by = "country") %>% 
  select(-id) %>% 
  rename(deg0817 = degree,
         wtddeg0817 = wtd_degree, 
         kcore0817 = k_core,
         louvain0817 = louvain_comm,
         fstgrdy0817 = fstgrdy_comm,
         comp0817 = component) %>% 
  right_join(nodelist_200818, by = "country") %>% 
  select(-id) %>% 
  rename(deg0818 = degree,
         wtddeg0818 = wtd_degree, 
         kcore0818 = k_core,
         louvain0818 = louvain_comm,
         fstgrdy0818 = fstgrdy_comm,
         comp0818 = component) 

# changing country codes to country name 
full_nodelist$country_code <- countrycode(full_nodelist$country, origin = 'country.name', destination = 'iso2c')

full_nodelist <- full_nodelist %>% 
  mutate(country_code = ifelse(test = str_detect(string = country, pattern = "Kosovo"), yes = "XK", no = country_code)) %>% 
  select(country, country_code, everything())

setwd("~/intl-dyn-ctry")
saveRDS(full_nodelist, "full_ctry_nodelist.rds")

# only for the full static nodelist 
country_nodelist_allyears <- full_nodelist %>% 
  select(country, country_code, deg0818, wtddeg0818, kcore0818, louvain0818, fstgrdy0818, comp0818) %>% 
  rename(degree = deg0818,
         wtd_degree = wtddeg0818, 
         k_core = kcore0818,
         louvain_comm = louvain0818,
         fstgrdy_comm = fstgrdy0818,
         component = comp0818) 

setwd("~/intl-dyn-ctry")
write_csv(country_nodelist_allyears, "country_nodelist_allyears.csv")
```

```{r concatenating global_netstats_cum}

setwd("~/intl-dyn-ctry")
#setwd("~/2008")
global_netstats_2008 <- readRDS("global_netstats_2008.rds") 
#setwd("~/2008-09")
global_netstats_200809 <- readRDS("global_netstats_2008-09.rds") 
#setwd("~/2008-10")
global_netstats_200810 <- readRDS("global_netstats_2008-10.rds") 
#setwd("~/2008-11")
global_netstats_200811 <- readRDS("global_netstats_2008-11.rds") 
#setwd("~/2008-12")
global_netstats_200812 <- readRDS("global_netstats_2008-12.rds")
#setwd("~/2008-13")
global_netstats_200813 <- readRDS("global_netstats_2008-13.rds")
#setwd("~/2008-14")
global_netstats_200814 <- readRDS("global_netstats_2008-14.rds")
#setwd("~/2008-15")
global_netstats_200815 <- readRDS("global_netstats_2008-15.rds")
#setwd("~/2008-16")
global_netstats_200816 <- readRDS("global_netstats_2008-16.rds")
#setwd("~/2008-17")
global_netstats_200817 <- readRDS("global_netstats_2008-17.rds")
#setwd("~/2008-18")
global_netstats_200818 <- readRDS("global_netstats_2008-18.rds")

global_netstats <- rbind(global_netstats_2008, global_netstats_200809, 
                         global_netstats_200810, global_netstats_200811, 
                         global_netstats_200812, global_netstats_200813,
                         global_netstats_200814, global_netstats_200815, 
                         global_netstats_200816, global_netstats_200817, global_netstats_200818)
                         
global_netstats <- as_tibble(c("2008", "2009", "2010", "2011", "2012", 
                                   "2013", "2014", "2015", "2016", "2017", "2018")) %>% 
  bind_cols(global_netstats) %>% # select(-year) %>% 
  rename(time = value)

# adding in weighted degree counts 
setwd("~/intl-dyn-ctry")
full_nodelist_cum <- readRDS("full_ctry_nodelist.rds")

edges <- as_tibble(c(sum(full_nodelist_cum$deg08/ 2, na.rm = TRUE), sum(full_nodelist_cum$deg0809/ 2, na.rm = TRUE),
            sum(full_nodelist_cum$deg0810/ 2, na.rm = TRUE), sum(full_nodelist_cum$deg0811/ 2, na.rm = TRUE),
            sum(full_nodelist_cum$deg0812/ 2, na.rm = TRUE), sum(full_nodelist_cum$deg0813/ 2, na.rm = TRUE),
            sum(full_nodelist_cum$deg0814/ 2, na.rm = TRUE), sum(full_nodelist_cum$deg0815/ 2, na.rm = TRUE),
            sum(full_nodelist_cum$deg0816/ 2, na.rm = TRUE), sum(full_nodelist_cum$deg0817/ 2, na.rm = TRUE), 
            sum(full_nodelist_cum$deg0818/ 2, na.rm = TRUE))) 

weighted <- as_tibble(c(sum(full_nodelist_cum$wtddeg08, na.rm = TRUE), sum(full_nodelist_cum$wtddeg0809, na.rm = TRUE),
            sum(full_nodelist_cum$wtddeg0810, na.rm = TRUE), sum(full_nodelist_cum$wtddeg0811, na.rm = TRUE),
            sum(full_nodelist_cum$wtddeg0812, na.rm = TRUE), sum(full_nodelist_cum$wtddeg0813, na.rm = TRUE),
            sum(full_nodelist_cum$wtddeg0814, na.rm = TRUE), sum(full_nodelist_cum$wtddeg0815, na.rm = TRUE),
            sum(full_nodelist_cum$wtddeg0816, na.rm = TRUE), sum(full_nodelist_cum$wtddeg0817, na.rm = TRUE), 
            sum(full_nodelist_cum$wtddeg0818, na.rm = TRUE))) 

colnames(weighted) <- "wtd_edge_count"
global_netstats <- cbind(global_netstats, weighted) 
global_netstats <- global_netstats %>% 
  select(time, year, node_count, edge_count, wtd_edge_count, everything()) %>% 
  transform(dyads = as.numeric(dyads))

global_netstats

setwd("~/intl-dyn-ctry")
write_csv(global_netstats, "country_global_netstats_allyears.csv")

```

```{r}

for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL",
              "cowplot", "maditr", "lubridate", "linkprediction", "poweRlaw", 
              "countrycode")) {library(pkg, character.only = TRUE)}

conn <- dbConnect(drv = PostgreSQL(), dbname = "sdad_data", 
                  host = "sdad.policy-analytics.net", port = 5436, 
                  user = Sys.getenv("db_userid"), password = Sys.getenv("db_pwd"))

# query the bipartite edgelist data from github data  
country_codes <- dbGetQuery(conn, "SELECT login, country_code
                                   FROM github.users_gh_cc")

# disconnect from postgresql
dbDisconnect(conn)

country_codes

country_codes$country_code <- trimws(country_codes$country_code)

country_codes <- country_codes %>% 
  mutate(country_code = ifelse(test = str_detect(string = country_code, pattern = ","), yes = "multiple", no = country_code)) 


totals <- country_codes %>% 
  group_by(country_code) %>% 
  count() %>% 
  arrange(-n)

totals

# changing country codes to country name 
totals$country <- countrycode(totals$country_code, origin = 'iso2c', destination = 'country.name')

# changing Kosovo to have a valid country name 
totals <- totals %>% 
  mutate(country = ifelse(test = str_detect(string = country_code, pattern = "xk"), yes = "Kosovo", no = country)) 

totals <- totals %>% 
  select(country, country_code, n)

totals

totals <- totals %>% 
  mutate(shares = n / 2143407) %>% 
  mutate(shares = round(shares, 3) * 100)

totals

setwd("~/intl-dyn-ctry")
write_csv(totals, "contributors_by_country.csv")
```








