---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
#rm(list = ls())
# load packages 
for (pkg in c("tidyverse", "data.table", "countrycode", "tidyorgs",
              "R.utils", "RPostgreSQL")) {library(pkg, character.only = TRUE)}

setwd("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data")
raw_ctr_data <- readRDS("../data/github_sectored_101321.rds") 

eg_table <- raw_ctr_data %>% 
  filter(!is.na(company) & !is.na(location) & !is.na(email) & grepl("Chime|chime", company))
```

```{r}
# implementing daniel's approaches 
legal_entities <- read.csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/ossPy-files/curatedLegalEntitesRaw.csv", header=FALSE)
legal_entities <- legal_entities %>% 
  rename(strings = V1) %>% 
  mutate(strings = as.character(strings))
legal_entities$strings <- substring(legal_entities$strings, 2)
legal_entities$strings <- substr(legal_entities$strings,1, nchar(legal_entities$strings)-1)

symbol_strings <- read.csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/ossPy-files/symbolRemove.csv", header=FALSE)
symbol_strings <- symbol_strings %>% 
  rename(strings = V1) %>% 
  mutate(strings = as.character(strings))
symbol_strings$strings <- substring(symbol_strings$strings, 2)
symbol_strings$strings <- substr(symbol_strings$strings,1, nchar(symbol_strings$strings)-1)
symbol_strings <- symbol_strings %>% slice(-17:-20)

curated_domains <- read.csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/ossPy-files/curatedDomains.csv", header=FALSE)
curated_domains <- curated_domains %>% 
  rename(strings = V1) %>% 
  mutate(strings = as.character(strings))
curated_domains$strings <- substring(curated_domains$strings, 2)
curated_domains$strings <- substr(curated_domains$strings,1, nchar(curated_domains$strings)-1)

data_for_countries <- raw_ctr_data %>% 
  select(login, company, location, email) %>% 
  mutate(email = tolower(email)) %>% 
  filter(!is.na(company) | !is.na(location) | (!is.na(email) & 
         !grepl("gmail.com$|hotmail.com$|protonmail.com$|qq.com$|yahoo.com$|163.com$|126.com$|outlook.com$|live.com$|foxmail.com$|me.com$|icloud.com$", email)))

data_to_classify <- raw_ctr_data %>% 
  select(login, company, location, email) %>% 
  mutate(email = tolower(email)) %>% 
  filter(!is.na(company) | (!is.na(email) & 
         !grepl("gmail.com$|hotmail.com$|protonmail.com$|qq.com$|yahoo.com$|163.com$|126.com$|outlook.com$|live.com$|foxmail.com$|me.com$|icloud.com$", email)))

data_to_classify <- data_to_classify %>%
  mutate(company = trimws(company),
         company = tolower(company)) %>% 
  mutate(company = str_replace_all(company, paste(c("(?i)(zqx", na.omit(legal_entities$strings), 
                                                    "zqx|, Inc.)"), collapse = "|"), "")) %>% 
  mutate(company = str_replace_all(company, paste(c("(?i)(zqx", na.omit(symbol_strings$strings), 
                                                    ", $|,$|zqx)"), collapse = "|"), "")) %>%
  mutate(company = str_replace_all(company, paste(c("(?i)(zqx", na.omit(curated_domains$strings), 
                                                    "zqx)"), collapse = "|"), "")) 
# null values 
null_values <- read.csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/ossPy-files/nullKeys.csv", header=FALSE)
null_values <- null_values %>% 
  rename(strings = V1) %>% 
  mutate(strings = as.character(strings))
null_values$strings <- substring(null_values$strings, 2)
null_values$strings <- substr(null_values$strings,1, nchar(null_values$strings)-1)

data_to_classify <- data_to_classify %>% 
  mutate(is_null = ifelse(test = str_detect(string = company, 
         pattern = paste(c("\\b(?i)(z3x", na.omit(null_values$strings), "z3x)\\b"), collapse = "|")), 
         yes = 1, no = NA)) %>% 
  mutate(is_null = ifelse(!str_detect(company, "[a-z]"), 1, is_null)) %>% 
  mutate(is_null = ifelse(str_detect(company, "\\b(?i)(^china$|^japan$|^taiwan$|^indonesia$|^beijing$|^retired$|^germany$|^test$|^anonymous$|^open source$|^full stack developer$|^developer$|^software engineer$|^software$|^undefined$|^own$|^secret$|^nope$|^nil$|^unknown$|^nothing$|^non$|^dev$|^localhost$|^confidential$|^data scientist$|^null$|null|data scientist|localhost|dev|confidential|internet|(?<![a-z])no(?![a-z]))\\b"), 1, is_null)) %>% mutate(is_null = replace_na(is_null, 0)) #%>% 
  #filter(is_null != 1)

null_users <- data_to_classify %>% 
  filter(is_null == 1)
null_users; rm(null_values, legal_entities, curated_domains, symbol_strings)

# household 
household <- read.csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/ossPy-files/individualKeys.csv", header=FALSE)
household <- household %>% 
  rename(strings = V1) %>% 
  mutate(strings = as.character(strings))
household$strings <- substring(household$strings, 2)
household$strings <- substr(household$strings,1, nchar(household$strings)-1)

data_to_classify <- data_to_classify %>% 
  mutate(company = tolower(company),
         #company = str_replace_all(company, "\\/", " "),
         is_household = ifelse(test = str_detect(string = company, 
         pattern = paste(c("\\b(?i)(z3x", na.omit(household$strings), 
         "^self-employed$|self-employed|^self employed$|^unemployed$|^available for hire$|for hire$|^home office$|free|my own|^home$|^independant$|^private$|private|^self$|self|independent|indie|independiente)\\b"), collapse = "|")), yes = 1, no = 0)) %>% 
  mutate(is_household = replace_na(is_household, 0))  

household_users <- data_to_classify %>% 
  filter(is_household == 1)
household_users; rm(household)

data_to_classify <- data_to_classify %>% 
  detect_academic(login, company, organization, email) %>% 
  rename(is_academic = academic) 

academic_users <- data_to_classify %>% 
  filter(is_academic == 1); academic_users 

data_to_classify <- data_to_classify %>% 
  select(-organization) %>% 
  detect_nonprofit(login, company, organization, email) %>% 
  rename(is_nonprofit = nonprofit) 

nonprofit_users <- data_to_classify %>% 
  filter(is_nonprofit == 1); nonprofit_users 

#data_to_classify <- data_to_classify %>% select(-organization, -is_gov)

data_to_classify <- data_to_classify %>% 
  select(-organization) %>% 
  detect_government(login, company, organization, email) %>% 
  rename(is_gov = government) 

government_users <- data_to_classify %>% 
  filter(is_gov == 1); government_users

# data_to_classify <- data_to_classify %>% select(-organization, -is_business)

data_to_classify <- data_to_classify %>% 
  select(-organization) %>% 
  mutate(company = sub(".*\\|", "", company),
         company = trimws(company, which = "both")) %>% 
  detect_business(login, company, organization, email) %>% 
  rename(is_business = business) %>% 
  select(everything(), organization)

business_users <- data_to_classify %>% 
  filter(is_business == 1); business_users

leftovers <- data_to_classify %>% 
  filter(!is.na(company) & is_academic != 1 & is_null != 1 & is_nonprofit != 1 
         & is_gov != 1 & is_business != 1 & is_household != 1 
         & !grepl("blockchain|hse|hust|none|mail group|unam|uiuc", company))

leftover_counts <- leftovers %>% 
  mutate(company = sub(".*\\|", "", company),
         company = trimws(company, which = "both")) %>% 
  count(company) %>% 
  filter(n < 26) %>% 
  arrange(-n); leftover_counts

# 
above_five <- leftover_counts %>% 
  filter(n > 5) 

data_to_classify <- data_to_classify %>% 
  mutate(company = sub(".*\\|", "", company)) %>% 
  mutate(is_business = ifelse(test = str_detect(string = company, 
         pattern = paste(c("\\b(?i)(z3x", na.omit(above_five$company), "z3x)\\b"), collapse = "$|^")), 
         yes = 1, no = is_business))

business_users <- data_to_classify %>% 
  mutate(company = sub(".*\\|", "", company),
         company = trimws(company, which = "both")) %>%
  filter(is_business == 1)

business_users <- business_users %>% 
  mutate(organization = replace_na(organization, "Misc. Business"))
business_users

leftovers <- data_to_classify %>% 
  filter(is_academic != 1 & is_null != 1 & is_nonprofit != 1 
         & is_gov != 1 & is_business != 1 & is_household != 1)
leftover_counts <- leftovers %>% 
  count(company) %>% 
  arrange(-n); leftover_counts

sum(leftover_counts$n)
```

```{r}
nrow(academic_users)
nrow(business_users)
nrow(government_users)
nrow(nonprofit_users)
nrow(household_users)
```

```{r}
orgs_combined <- bind_rows(
  academic_users %>% select(login, organization),
  business_users %>% select(login, organization),
  government_users %>% select(login, organization),
  nonprofit_users %>% select(login, organization)
) %>% group_by(login) %>% 
  summarise(organization = paste(organization, collapse = "|"))

orgs_combined <- data_to_classify %>%
  select(login, starts_with("is_")) %>% 
  left_join(orgs_combined, by = "login") %>% 
  mutate(is_business = replace_na(is_business, 0))

write_rds(orgs_combined, "/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/github_sectors_110521.rds")
```


```{r}
orgs_combined <- readRDS("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/github_sectors_110521.rds") 

library(RPostgreSQL)
conn <- dbConnect(drv = PostgreSQL(), dbname = "sdad",
                  host = "10.250.124.195", port = 5432,
                  user = Sys.getenv("db_userid"), password = Sys.getenv("db_pwd"))
users_with_countries <- dbGetQuery(conn, "SELECT * FROM gh_cost.users_geo_102021;")
dbDisconnect(conn)

users_with_countries_collapsed <- users_with_countries %>% 
  mutate(is_us = if_else(country == "United States", 1, 0)) %>% 
  group_by(login) %>% 
  summarise(country = paste(country, collapse = "|"),
            is_us = sum(is_us)) %>% 
  mutate(us_fraction = (is_us / (str_count(country, "\\|") + 1)),
         frgn_fraction = 1 - us_fraction)

user_with_org_data <- raw_ctr_data %>% 
  select(login) %>% 
  left_join(users_with_countries_collapsed, by = "login") %>% 
  mutate(is_us = replace_na(is_us, 0),
         us_fraction = replace_na(us_fraction, 0),
         frgn_fraction = replace_na(frgn_fraction, 0),
         na_fraction = country,
         na_fraction = replace_na(country, 1),
         na_fraction = if_else(na_fraction == 1, 1, 0)) %>% 
  left_join(orgs_combined, by = "login") %>% 
  select(login, organization, country, is_us, is_null, 
         contains("academic"), contains("business"), contains("gov"), 
         contains("nonprofit"), contains("household"), contains("fraction")) %>% 
  mutate_at(vars(is_null:is_household),  ~ if_else(is.na(.), 0, .)) 

table_for_postgres <- user_with_org_data %>%
  mutate(sector_n = is_business + is_gov + is_nonprofit + is_household, 
         # academic is an addendum so it does NOT get fractionated 
         business_frac = is_business / sector_n,
         gov_frac = is_gov / sector_n,
         nonprofit_frac = is_nonprofit / sector_n,
         household_frac = is_household / sector_n) %>% 
  mutate_all(~replace(., is.infinite(.), 0)) %>% 
  mutate_all(~replace(., is.nan(.), 0)) %>% 
  mutate(us_academic = is_academic * us_fraction,
         frgn_academic = 1 - us_academic,
         us_business = business_frac * us_fraction,
         frgn_business = 1 - us_business,
         us_gov = gov_frac * us_fraction,
         frgn_gov = 1 - us_gov,
         us_nonprofit = nonprofit_frac * us_fraction,
         frgn_nonprofit = 1 - us_nonprofit,
         us_household = household_frac * us_fraction,
         frgn_household = 1 - us_household) %>% 
  mutate_all(~replace(., is.infinite(.), 0)) %>% 
  mutate_all(~replace(., is.nan(.), 0)) %>% 
  select(login, organization, country, is_null, is_us, 
         contains("academic"), contains("business"), contains("gov"), 
         contains("nonprofit"), contains("household"), contains("fraction")) 

us_table_for_postgres <- table_for_postgres %>% 
  select(login, organization, country, is_us, starts_with("us_")) %>% 
  filter(is_us == 1)
us_table_for_postgres
```

```{r}
counts_by_country <- table_for_postgres
  
sum(counts_by_country$us_academic) 
sum(counts_by_country$us_business) 
sum(counts_by_country$us_gov)
sum(counts_by_country$us_nonprofit)
sum(counts_by_country$us_household)

sum(counts_by_country$frgn_academic)
sum(counts_by_country$frgn_business)
sum(counts_by_country$frgn_gov)
sum(counts_by_country$frgn_nonprofit)
sum(counts_by_country$frgn_household)
```

```{r}

conn <- dbConnect(drv = PostgreSQL(),
                  dbname = "sdad",
                  host = "10.250.124.195",
                  port = 5432,
                  user = Sys.getenv("db_userid"),
                  password = Sys.getenv("db_pwd"))
dbWriteTable(conn, c("gh_cost", "sectored_fractioned_110521"), us_table_for_postgres, row.names = FALSE)
dbWriteTable(conn, c("gh_cost", "us_sectored_fractioned_110521"), us_table_for_postgres, row.names = FALSE)
dbDisconnect(conn)

write_csv(table_for_postgres, "/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/github_sectored_103121.csv")
```


```{r}

conn <- dbConnect(drv = PostgreSQL(), dbname = "sdad",
                  host = "10.250.124.195", port = 5432,
                  user = Sys.getenv("db_userid"), password = Sys.getenv("db_pwd"))
sectored_fractioned <- dbGetQuery(conn, "SELECT * FROM gh_cost.sectored_fractioned_103121")
dbDisconnect(conn)

```

```{r}

orgs_combined <- sectored_fractioned %>% 
  select(login, email, company, organization, location, country, starts_with("is_"))

```


```{r}
sum(sectored_fractioned$is_academic)
sum(sectored_fractioned$academic_frac)
sum(sectored_fractioned$us_academic)

sum(sectored_fractioned$is_business)
sum(sectored_fractioned$us_business)

```


```{r}
sectored_fractioned %>% 
  slice(1:100) %>%
  select(login, company, contains("us_"), contains("nonus_")) %>% 
  rowwise() %>% 
  mutate(total = sum(us_academic+nonus_academic+us_business+nonus_business+us_gov+nonus_gov+
                       us_nonprofit+nonus_nonprofit+us_household+nonus_household))
```

```{r}
library(tidyverse)
github_sectored_110221 <- read_csv("/sfs/qumulo/qhome/kb7hp/git/oss-2020/data/github_sectored_110221.rds")

github_sectored_110221 %>% 
  #filter(is_nonprofit == 1) %>% 
  group_by(country) %>% 
  count() %>% 
  arrange(-n)
#96858+69396+66186+58987+43582 = 335009
```

```{r}
bus_n <- sum(github_sectored_110221$business_frac)
ac_n <- sum(github_sectored_110221$academic_frac)
hh_n <- sum(github_sectored_110221$household_frac)
gov_n <- sum(github_sectored_110221$gov_frac)
np_n <- sum(github_sectored_110221$nonprofit_frac)

sector_counts <- data.frame(sector = c("business", "academic", "household", "government", "nonprofit"),
                            total = c(bus_n, ac_n, hh_n, gov_n, np_n))
sector_counts
```
```{r, fig.height = 7, fig.width=9}
positions <- c("business", "academic","household","government", "nonprofit")
ggplot(data=sector_counts, aes(x=sector, y=total)) +
  geom_bar(stat="identity", width = 0.5, fill = c("#232D4B", "#E57200", "#628ed8", "#E1AD01", "#990000")) +
  scale_x_discrete(limits = positions) +
  theme_minimal() +
  theme(plot.title = element_text(size=22),
        plot.subtitle = element_text(size=16),
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size = 16),
        axis.title =element_text(size=18),
        axis.title.x=element_blank()) +
  labs(subtitle = "Based on 27.2% of Total GitHub Users Classified into Sectors",
       caption = "Note: Totals Fractioned When Multiple Sectors or Countries Reported") +
  ggtitle("Total GitHub Users Classified by Economic Sector") +
  scale_y_continuous(name="Total GitHub Users within Sector", limits=c(0, 275000), breaks = c(0, 50000, 100000, 150000, 200000, 250000))
```

```{r}
total_users <- nrow(github_sectored_110221)
users_with_info <- nrow(data_to_classify)
with_countries <- github_sectored_110221 %>% drop_na(country)
country_total <- nrow(with_countries)
with_geo_info <- nrow(data_for_countries)

total_counts <- data.frame(label = c("Total Users", "With Potential Geographic Data", "With Country Code", 
                                     "With Potential Sector Data", "Business", "Academic", "Household", "Government", "Non-Profit"),
                           totals = c(total_users, with_geo_info, country_total, users_with_info, 
                                      bus_n, ac_n, hh_n, gov_n, np_n),
                           of_total = c(100, (with_geo_info/total_users*100), country_total/total_users*100, 
                                        (users_with_info/total_users*100), bus_n/total_users*100, 
                                        ac_n/total_users*100, hh_n/total_users*100, 
                                        gov_n/total_users*100, np_n/total_users*100 ),
                           of_classifiable = c(NA, 100, country_total/with_geo_info*100, 100,  
                                               bus_n/users_with_info*100, ac_n/users_with_info*100, 
                                               hh_n/users_with_info*100, gov_n/users_with_info*100,
                                               np_n/users_with_info*100)) %>% 
  mutate(of_total = round(of_total, 2),
         of_classifiable = round(of_classifiable, 2))
total_counts
```
```{r}
(2006.833+4126.500+12232.833+105067.833+261086.000) / users_with_info
```





