---
title: "Static Network Analyses"
author: "Brandon L. Kramer"
date: "10/23/2019"
output: html_document
---

```{r loading edgelist data}
rm(list = ls())
# install.packages(c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr"))

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "bc3net", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr")) {library(pkg, character.only = TRUE)}

# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(),
                 dbname = "sdad_data",
                 host = "postgis_2",
                 port = 5432L,
                 user = Sys.getenv("db_userid"),
                 password = Sys.getenv("db_pwd"))

# query the static edgelist data from github data 
static_edgelist <- dbGetQuery(conn, "SELECT login, slug, count FROM github.st_bp_edgelist")

# query the static edgelist data from github data 
node_attributes <- dbGetQuery(conn, "SELECT login, country_code FROM github.users_gh_cc")

# disconnect from postgresql
dbDisconnect(conn)
```

Let's make a network and add the country codes to the nodelist. 

```{r}
# renaming columms for igraph 
static_edgelist <- static_edgelist %>% dplyr::rename(weight = count)

# this creates a graph and removes duplicated edges and self-loops 
g <- igraph::simplify(igraph::graph.data.frame(static_edgelist, directed=TRUE))

# after creating that network, we need to construct a nodelist 
static_nodelist <- data.frame(ID = c(1:(igraph::vcount(g))), nName = igraph::V(g)$name)

# adding country codes to the nodelist 
static_nodelist <- dplyr::full_join(static_nodelist, node_attributes, by = c("nName" = "login")) %>% 
  dplyr::mutate(new_col = ifelse(test = is.na(x = country_code), yes = paste("repo"), no = country_code)) %>% 
  dplyr::select(-country_code) %>% 
  dplyr::rename(name = nName, country_code = new_col) 

# renaming multiple countries 
static_nodelist <- static_nodelist %>% 
  dplyr::mutate(country_code_vis = ifelse(test = str_detect(string = static_nodelist$country_code,
                                      pattern = ","), paste("multiple"), no = country_code)) %>% 
  dplyr::mutate(country_code_di = ifelse(test = str_detect(string = static_nodelist$country_code,
                                      pattern = ","), paste("multiple"), no = "single")) %>% 
  dplyr::select(ID, name, country_code_di, country_code, country_code_vis)

# trimming white space (just in case)
static_nodelist$country_code <- stringi::stri_trim_both(static_nodelist$country_code)
static_nodelist$country_code_di <- stringi::stri_trim_both(static_nodelist$country_code_di)
static_nodelist$country_code_vis <- stringi::stri_trim_both(static_nodelist$country_code_vis)

# getting a count of countries and repos 
static_nodelist %>% 
  dplyr::count(country_code, sort = TRUE) 
```

Let's write the nodelist and edgelist back to the database to pull that later. 

```{r writing edgelists to sql}
# reconnecting to the database 
conn <- dbConnect(drv = PostgreSQL(),
                 dbname = "sdad_data",
                 host = "postgis_2",
                 port = 5432L,
                 user = Sys.getenv("db_userid"),
                 password = Sys.getenv("db_pwd"))

# writing the new users_gh_cc table to postgis_2
dbWriteTable(conn, c("github", "intl_st_bp_nodes"), static_nodelist)
dbWriteTable(conn, c("github", "intl_st_bp_edges"), static_edgelist)

# disconnect from postgresql database  
dbDisconnect(conn)
```

The next logical step is to run more analyses on the networks, but these analyses are are so computationally intensive that we have to use UVA's Rivanna system. See the next files for that code. 

























