---
title: "R Notebook"
output: html_notebook
---

```{sql}

CREATE MATERIALIZED VIEW gh.desc_ctrs_summary_yxy AS (
SELECT login, EXTRACT(YEAR FROM committed_date)::int AS YEAR, COUNT(DISTINCT slug) AS repos, COUNT(*) AS commits, SUM(additions) AS additions, SUM(deletions) AS deletions
FROM gh.commits_pre
GROUP BY login, EXTRACT(YEAR FROM committed_date)::int
); 

```



```{sql write_sna_intl_ctr_nodelist}

---NEED TO TEST THIS TO MAKE SURE IT WORKS 
CREATE MATERIALIZED VIEW gh.sna_intl_ctr_nodelist_full AS (
SELECT login, repos, commits, deletions, country_code, country_code_di, country_code_vis 
FROM gh.sna_ctr_nodelist_full
WHERE country_code IS NOT NULL 
); 

```

```{r}


# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

# query the country_codes
country_codes <- dbGetQuery(conn, "SELECT login, country_code, country_code_di, country_code_vis 
                                   FROM gh.login_ctry_codes")

# query the 
ctrs_summary_yrly <- dbGetQuery(conn, "SELECT login, year, repos, commits, additions, deletions  
                                       FROM ctrs_summary_yrly")

# disconnect from postgresql database 
dbDisconnect(conn)

```

```{r}


# BE SURE TO ADD IN COUNTRY CODES TO NODELIST 

full_nodelist <- full_nodelist %>% 
  inner_join(country_codes, by = "login") %>% 
  select(login, country_code, country_code_di, country_code_vis, everything())



```

