---
title: "hipolabs cleaning"
author: "Morgan Klutzke"
date: "6/23/2020"
output: html_document
---

```{r packages}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "igraph", "visNetwork", "data.table", "R.utils", "RPostgreSQL", "cowplot", "maditr", "stringr", "stringi")) {library(pkg, character.only = TRUE)}
```
```{r loading data}
# connect to postgresql to get our data
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))


hipolabs <- dbGetQuery(conn, "SELECT institution, country, domains FROM hipolabs.universities")
```

```{r}
# disconnect from postgresql database 
dbDisconnect(conn)
```

Cleaning hipolabs data before using it with github users

```{r}
# remove duplicates, make all lowercase
institutions_hipolabs <- hipolabs %>% 
  as.data.table() %>% 
  dt_mutate(institution = str_to_lower(institution)) %>% 
  distinct() %>%
  add_row(institution = "misc. student") %>%
  add_row(institution = "university of tokyo", country = "Japan", domains = "u-tokyo.ac.jp") %>%
  add_row(institution = "aalto university", country = "Finland", domains = "aalto.fi") %>%
  add_row(institution = "international institute of information technology, hyderabad", country = "India", domains = "iiit.ac.in") %>%
  add_row(institution = "broad institute", country = "United States", domains = "broadinstitute.org") %>%
  dt_mutate(institution = if_else(institution == "xi'an university of electronic science and technology", "xidian university", institution))


```

```{r}
# group together different country and domain values for the same institution
test <- institutions_hipolabs[duplicated(institutions_hipolabs$institution), ] %>% rename(c(country2 = country, domains2 = domains))
test2 <- test[duplicated(test$institution), ] %>% rename(c(country3 = country2, domains3 = domains2))
test3 <- test2[duplicated(test2$institution), ] %>% rename(c(country4 = country3, domains4 = domains3))
test4 <- test3[duplicated(test3$institution), ] %>% rename(c(country5 = country4, domains5 = domains4))
test5 <- test4[duplicated(test4$institution), ] %>% rename(c(country6 = country5, domains6 = domains5))

test <- test[!duplicated(test$institution), ]
test2 <- test2[!duplicated(test2$institution), ]
test3 <- test3[!duplicated(test3$institution), ]
test4 <- test4[!duplicated(test4$institution), ]
test5 <- test5[!duplicated(test5$institution), ]

institutions_hipolabs <- institutions_hipolabs[!duplicated(institutions_hipolabs$institution), ] %>% 
  left_join(test) %>%
  left_join(test2) %>%
  left_join(test3) %>%
  left_join(test4) %>%
  left_join(test5) %>%
  mutate_all(str_replace_na)

institutions_hipolabs <- institutions_hipolabs %>%
  dt_mutate(country2 = if_else(country == country2, "NA", country2)) %>%
  dt_mutate(country3 = if_else(country == country3, "NA", country3)) %>%
  dt_mutate(domains2 = if_else(domains == domains2, "NA", domains2)) %>%
  dt_mutate(domains3 = if_else(domains == domains3, "NA", domains3)) %>%
  dt_mutate(domains4 = if_else(domains == domains4, "NA", domains4)) %>%
  dt_mutate(domains5 = if_else(domains == domains5, "NA", domains5))

institutions_hipolabs <- institutions_hipolabs %>%
  dt_mutate(country_combined = str_c(country, country2, country3, country4, country5, country6, sep = ", ")) %>%
  dt_mutate(domains_combined = str_c(domains, domains2, domains3, domains4, domains5, domains6, sep = ", ")) %>%
  transmute(institution = institution, country = country_combined, domains = domains_combined)

institutions_hipolabs <- institutions_hipolabs %>% 
  dt_mutate(country = str_replace_all(country, ", NA", "")) %>%
  dt_mutate(domains = str_replace_all(domains, ", NA", ""))
```


To do:
* Add a new column for alternative names, split with pipes or commas
* Add a column of shortened names for visuals
