---
title: "08_city_network_descriptive_by_continent"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r loading edgelist data, warning=FALSE, echo=FALSE}
rm(list = ls())

# load packages 
for (pkg in c("tidyverse", "data.table", "R.utils", "RPostgreSQL", 
              "igraph", "netrankr", "centiserve", "expm", "intergraph",
              "cowplot", "maditr", "lubridate", "countrycode")) {library(pkg, character.only = TRUE)}
# connect to postgresql to get data (in rivanna)
conn <- dbConnect(drv = PostgreSQL(), 
                  dbname = "sdad", 
                  host = "10.250.124.195", 
                  port = 5432, 
                  user = Sys.getenv("db_userid"), 
                  password = Sys.getenv("db_pwd"))

city_edgelist<- dbGetQuery(conn, "SELECT * FROM gh.sna_city_all_edgelist_0819")

ctrs_city <- dbGetQuery(conn, "SELECT *
                              FROM gh.sna_ctr_city_codes")


#write.csv(city_edgelist, file = "sna_city_northamerica_edgelist_0819.csv", row.names=F)
# disconnect from postgresql
dbDisconnect(conn)

#write.csv(city_edgelist, file = "sna_city_all_edgelist_0819.csv", row.names = F)
```

```{r}
#compose edgelist that limits to U.S. collaborations
#The nodes in this edgelsit include cities collaborate with at least one city in the U.S.
# edgelist <- city_edgelist%>%
#   mutate(target_is_us = if_else(str_detect(target, "us_"), T, F))%>%
#   mutate(source_is_us = if_else( str_detect(source, "us_"), T, F))%>%
#   filter(target_is_us | source_is_us)%>%
#   select(-target_is_us, -source_is_us)
#write.csv(edgelist, file = "sna_city_all_us_edgelist_0819.csv", row.names = F)
edgelist <- city_edgelist

#number of unique sources
source <- edgelist$source
source <- unique(source)
length(source)

#number of unique targets
target <- edgelist$target
target <- unique(target)
length(target)

#construct nodelist for viz on gephi
nodelist <- c(source, target)
length(nodelist)
nodelist <- unique(nodelist)
length(nodelist)

```


```{r}

# ctrs_city$c_continent_code <- as.character(ctrs_city$c_continent_code)
# ctrs_city$c_continent_code[is.na(ctrs_city$c_continent_code )] <- "NAM"
# table(ctrs_city$c_continent_code)


ctrs_city <- ctrs_city[!duplicated(ctrs_city$c_city_code), ]


city_nodelist <- ctrs_city%>%
  select(c_city_code, raw_country_code, raw_city, c_country_name, c_continent_name, raw_long, raw_lat)%>%
  filter(c_city_code %in% nodelist)%>%
  mutate(raw_city = toTitleCase(raw_city))%>%
  rename(Id = c_city_code, country = c_country_name, city = raw_city, continent = c_continent_name, latitude = raw_lat, longitude=raw_long)

#write.csv(city_nodelist, file = "sna_city_all_nodelist_0819.csv", row.names = F)
```

#### Major Countries in the U.S. Centralized Network
In the following plot, we are showing the countries that are collaborating with the U.S. Germany, having 453 cities that are collaborating with the U.S., is the major collaborator with the U.S., following by UK, Brazil, and India. 
```{r eval=FALSE, fig.height=6, fig.width=10, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}



#number of unique sources
source <- city_edgelist$source
source <- unique(source)

#number of unique targets
target <- city_edgelist$target
target <- unique(target)


#identify U.S. cities and other cities that U.S. cities collaborate with
city_nodelist_us <- c(source, target)

city_nodelist_us <- unique(city_nodelist_us)  #exclude duplicates
#length(city_nodelist_us) #8092 unique cities in the network 

#obtain user information
ctrs_city <- city_clean_final[!duplicated(city_clean_final$c_city_code), ]
city_nodelist <- ctrs_city%>%
  select(c_city_code, raw_country_code, raw_city, c_country_name, c_continent_name)%>%
  filter(c_city_code %in% city_nodelist_us)%>%
  mutate(raw_city = toTitleCase(raw_city))%>%
  rename(Id = c_city_code, country = c_country_name, city = raw_city, continent = c_continent_name)

#length(unique(city_nodelist$country)) 165 countries
# city_nodelist%>%
#   filter(country == "US")%>%
#   group_by(country)%>%
#   summarize(ttl_number_cities = n()) #ttl number of cities in the U.S
            
cities_in_network <- city_nodelist%>%
  group_by(country)%>%
  summarize(ttl_number_cities = n(), continent =  first(na.omit(continent)))%>%
  arrange(desc(ttl_number_cities))%>%
  filter(ttl_number_cities > 80)%>%
  filter(country != "US")

cities_in_network$country <- factor(cities_in_network$country, levels = cities_in_network$country[order(cities_in_network$ttl_number_cities)])
min = min(cities_in_network$ttl_number_cities)
max = max(cities_in_network$ttl_number_cities)

ggplot(cities_in_network, aes(x = country, y = ttl_number_cities, fill = continent))+
  geom_bar(stat = "identity")+
  theme_bw()  +
  scale_fill_manual(values = c(uva_color_palette[9], uva_color_palette[1], uva_color_palette[3], uva_color_palette[5]))+
  theme(axis.text.x = element_text(angle = 45))+
  labs(#title = "Countreis in U.S. Centralized Network", 
       x = "Country", y = "Total Number of Cities", fill = "Continent")+
  theme(axis.text.x = element_text(size = 12, hjust = 1, vjust = 1),
        axis.text.y = element_text(size = 11, hjust = .5, vjust = .5),  
        axis.title.x = element_text(size = 15, hjust = .5, vjust = .5),
        axis.title.y = element_text(size = 15, hjust = .5, vjust = .5),
        legend.title=element_text(size=14),
        legend.text = element_text(size=13))+
  theme(legend.position="top")
```


```{r}
city_network <- simplify(graph.data.frame(city_edgelist, directed = FALSE), 
                         remove.loops = FALSE, 
                         edge.attr.comb = igraph_opt("edge.attr.comb"))
is_weighted(city_network)  #weighted by number of commits
is_directed(city_network)  #not directed
is_connected(city_network) #weakly connected
count_components(city_network)
components <- components(city_network)
groups(components)
```

# Network statistics
```{r global network stats}
# loading the network (if the instance crashes while doing network_stats)
net_stats_start <- data.frame(event="net_stats_start", time=now("EST"))
analysis_year = "0819"
network_stats <- data.frame(year=analysis_year)                                         

# node and edge counts  
network_stats$node_count <- gorder(city_network)  
network_stats$edge_count <- gsize(city_network)
network_stats$commits <- sum(city_edgelist$weight)

#degree
summary_degree <-  t(unclass(summary(degree(city_network)))) #mode parameter (in/out/all) of the degree function is ignored for undirected network
colnames(summary_degree) <- str_replace_all(colnames(summary_degree), "[[:punct:]]", " ")
colnames(summary_degree) <- str_replace_all(colnames(summary_degree), fixed(" "), "") 
colnames(summary_degree) <- tolower(colnames(summary_degree))
colnames(summary_degree) <- paste(colnames(summary_degree), "_deg", sep="")
network_stats <- cbind(network_stats,summary_degree)
network_stats$sd_deg <- sd(degree(city_network))

#degree distribution
deg <- as.data.frame(degree(city_network))
colnames(deg) = "degree"
ggplot(deg, aes(x=degree)) + 
  geom_histogram(binwidth = 80)+
  labs(title="Degree Distribution of City Network in North America")+
 theme_light()

#Betweenness centrality
#Definition: It measures the number of times a node lies on the shortest path between other nodes.
#Measure: Identify all the shortest paths and then count how many times each node falls on one.
#Finding the nodes/cities that are 'bridges' between nodes in the network, who influence the flow around the system
#Limitation: A high betweenness count could indicate someone holds authority over disparate clusters in a network, or just that they are on the periphery of both clusters.
network_stats$mean_btw <- mean(round(sna::betweenness(intergraph::asNetwork(city_network), cmode="undirected", gmode = "graph"), 4))

####################################
# isolates and triads(different types of triangles)
network_stats$isolates <- sum(igraph::degree(simplify(city_network))==0)
oss_triads <- igraph::triad.census(city_network)  
#we only have the following statistics, the rest are 0 due to nondirected graph
network_stats$triads_003 <- oss_triads[1]  #A, B, C, the empty graph.
network_stats$triads_102 <- oss_triads[3] #A<->B, C, a graph with a mutual connection between two vertices
network_stats$triads_201 <- oss_triads[11] #A<->B<->C
network_stats$triads_300 <- oss_triads[16] #A<->B<->C, A<->C, the complete graph (closed triads)
net_counts <- data.frame(event="net_counts", time=now("EST"))

#time log
time_log <- rbind(net_stats_start, net_counts); rm(net_stats_start, net_counts)


####################################
# density and transitivity
#The diameter of a graph is the length of the longest geodesic(shortest path). Weights is NA, otherwise in this weighted graph, we will be calculating a path with the minimum sum of edge weights
network_stats$diameter <- diameter(city_network, directed=FALSE, 
                                   unconnected=if (network_stats$isolates == 0) {FALSE} else {TRUE}, weights=NA)
#mean_distance calculates the average path length in a graph, by calculating the shortest paths between all pairs of vertices (both ways for directed graphs). This function does not consider edge weights currently and uses a breadth-first search.
network_stats$mean_distance <- mean_distance(city_network, directed = FALSE, 
                                   unconnected = if (network_stats$isolates == 0) {FALSE} else {TRUE})

#edge density: ratio of the number of edges and the number of possible edges
network_stats$density <- edge_density(city_network, loops=FALSE) 

#Transitivity measures the probability that the adjacent vertices of a vertex are connected. This is sometimes also called the clustering coefficient.
#the ratio of the triangles and the connected triples in the graph
network_stats$transitivity <- transitivity(city_network, weights = TRUE, type = "undirected") #undirected=global
net_globals <- data.frame(event="net_globals", time=now("EST"))
time_log <- rbind(time_log, net_globals); rm(net_globals)

####################################
# community detection (using louvain method)
#Finding community structure by multi-level optimization of modularity
louvain <- cluster_louvain(city_network)
network_stats$louvain <- modularity(louvain)
network_stats$louvain_scaled <- modularity(louvain) / gorder(city_network)
network_stats$louvain_logged <- modularity(louvain) / log(gorder(city_network))

# community detection (using fast & greedy method)
fstgrdy <- fastgreedy.community(city_network)
network_stats$fstgrdy <- modularity(fstgrdy)
network_stats$fstgrdy_scaled <- modularity(fstgrdy) / gorder(city_network)
network_stats$fstgrdy_logged <- modularity(fstgrdy) / log(gorder(city_network))

# added later 
#Centralize a graph according to the degrees of vertices
#graph level centrality index
network_stats$centr_deg <- round(centr_degree(city_network)$centralization, 3)

#graph level centrality index according to the closeness of vertices
network_stats$centr_clo <- round(centr_clo(city_network, mode = "all")$centralization, 3)
#graph level centrality index according to the betweenness of vertices
network_stats$centr_btw <- round(centr_betw(city_network, directed = FALSE)$centralization, 3)
#graph level centrality index according to the  eigenvector centrality of vertices
network_stats$centr_eigen <- round(centr_eigen(city_network, directed = FALSE)$centralization, 3)
network_stats$centr_scores <- cbind(year, centr_deg, centr_clo, centr_btw, centr_eigen)

# decomposition statistics 
decomposition_stats <- table(sapply(decompose.graph(city_network), vcount))

net_comm_det <- data.frame(event="net_comm_det", time=now("EST"))
time_log <- rbind(time_log, net_comm_det); rm(net_comm_det)


```

# Construct a nodelist 
```{r}
nodelist <- data.frame(id = c(1:(igraph::vcount(city_network))), login = igraph::V(city_network)$name)

# degree, weighted degree, k core and modularity 
node_stats_start <- data.frame(event="node_stats_start", time=now("EST"))
time_log <- rbind(time_log, node_stats_start); rm(node_stats_start)
nodelist$deg_cent <- igraph::degree(city_network, mode = "all")

#strength: summing up the edge weights of the adjacent edges for each vertex
nodelist$wtd_deg_cent <- strength(city_network)

#betweenness centrality
nodelist$btw_cent <- round(sna::betweenness(intergraph::asNetwork(city_network), cmode="undirected"), 4)

#closeness centrality
nodelist$close_cent <- closeness(city_network, mode = "all") 

#eigen value centrality
nodelist$eigen_cent <- eigen_centrality(city_network)$vector

nodelist$alpha_cent <- alpha_centrality(city_network)
nodelist$power_cent <- power_centrality(city_network)
nodelist$load_cent <- sna::loadcent(get.adjacency(city_network,sparse=F))
nodelist$info_cent <- sna::infocent(get.adjacency(city_network,sparse=F))
nodelist$stress_cent <- sna::stresscent(get.adjacency(city_network,sparse=F))
nodelist$subgraph_cent <- subgraph_centrality(city_network)
nodelist$page_rank <- page_rank(city_network)$vector
nodelist$auth_score <- authority.score(city_network)$vector
nodelist$hub_score <- hub.score(city_network)$vector
nodelist$local_trans <- transitivity(city_network, type = "local")
nodelist$eccentricity <- eccentricity(city_network)
nodelist$k_core <- coreness(city_network)
components <- components(city_network)
nodelist$component <- components$membership
nodelist$louvain_comm <- louvain$membership
nodelist$fstgrdy_comm <- fstgrdy$membership
nodelist$gilschmidt <- sna::gilschmidt(get.adjacency(city_network,sparse=F))
nodelist$hyper_even <- netrankr::hyperbolic_index(city_network,type = "even")
nodelist$hyper_odd <- netrankr::hyperbolic_index(city_network,type = "odd")
nodelist$bottleneck <- centiserve::bottleneck(city_network)
#nodelist$current_flow <- centiserve::closeness.currentflow(simplify(city_network))
nodelist$close_latora <- centiserve::closeness.latora(city_network)
nodelist$close_res <- centiserve::closeness.residual(city_network)
nodelist$comm_bet <- centiserve::communibet(city_network)
#nodelist$decay <- centiserve::decay(city_network)
nodelist$diff_deg <- centiserve::diffusion.degree(city_network)     
nodelist$entropy <- 1/centiserve::entropy(city_network)
nodelist$geokpath <- centiserve::geokpath(city_network)
nodelist$laplacian <- centiserve::laplacian(city_network)
nodelist$leverage <- centiserve::leverage(city_network)             
nodelist$lin_cent <- centiserve::lincent(city_network)
nodelist$lobby <- centiserve::lobby(city_network)
nodelist$markov_cent <- centiserve::markovcent(city_network)           
nodelist$mnc <- centiserve::mnc(city_network)
nodelist$dmnc <- centiserve::dmnc(city_network) 
nodelist$epc <- centiserve::epc(city_network) 
nodelist$radiality <- centiserve::radiality(city_network)            
nodelist$topocoefficient <- 1/centiserve::topocoefficient(city_network) 

node_stats_end <- data.frame(event="node_stats_end", time=now("EST"))
time_log <- rbind(time_log, node_stats_end); rm(node_stats_end, louvain, components)

setwd("/sfs/qumulo/qhome/zz3hs/git/dspg20oss/src/geographic/data")

saveRDS(network_stats, str_c("global_netstats_",analysis_year,".rds"))  

saveRDS(decomposition_stats, str_c("decomposition_stats_",analysis_year,".rds")) 
saveRDS(nodelist, str_c("nodelist_",analysis_year,".rds"))  
saveRDS(time_log, str_c("timelog_",analysis_year,".rds"))
```

```{r}
nodelist_z <- nodelist%>%
  mutate(deg_cent_z = scale(deg_cent, center = TRUE, scale = TRUE),
         wtd_deg_cent_z = scale(wtd_deg_cent, center = TRUE, scale = TRUE),
         btw_cent_z = scale(btw_cent, center = TRUE, scale = TRUE),
        close_cent_z = scale(close_cent, center = TRUE, scale = TRUE),
         eigen_cent_z = scale(eigen_cent, center = TRUE, scale = TRUE)
)%>%
  rename(city = login)%>%
  select(city, deg_cent_z,wtd_deg_cent_z, ,btw_cent_z, close_cent_z, eigen_cent_z)


nodelist_z_gather <- nodelist_z%>%
  gather("centrality_measure", "centrality_score_z", -city)
```


```{r}
library(lsa)
# greedy method (hiearchical, fast method)
c1 = cluster_fast_greedy(city_network)
coords = layout_with_fr(city_network)
# modularity measure
modularity(c1)

plot(c1, city_network, layout=coords,  vertex.label=NA)
```

